### ISSUE TITLE
Sending eth_decrypt multiple times throws "Cannot read property 'from' of undefined" error

### ISSUE THREAD

**Issue by jessgusclark** [MetaMask/metamask-extension#10231]
**Describe the bug**
Sending multiple requests of `eth_decrypt` to MetaMask at once returns the following error: `Message: Cannot read property 'from' of undefined`. The data is decrypted, but after the first item, this message is thrown each time before decrypting the next value.

**Steps to reproduce (REQUIRED)**

I have built a [small demo application](https://jessgusclark.github.io/decrypt-error/build) to demo the error, with the [code published here](https://github.com/jessgusclark/decrypt-error). The implementation code is in the [App.js file](https://github.com/jessgusclark/decrypt-error/blob/main/src/App.js).

1. **Click connect** to connect MetaMask to the App
2. Under the Encrypt heading **insert data into the input field and click the Encrypt Button**. Provide the app the public encryption key.
3. Under the Decrypt heading, **click Decrypt All**. In Metamask, decrypt item. No Error
4. **Encrypt a second string** in Encryption following step 2.
5. **Click 'Decrypt All'**. Metamask decrypts the first message, then shows an error, if you close the error, then it requests to decrypt the second message.

**Expected behavior**
The error should not show. It should prompt to decrypt each piece of information one at a time. Two pieces of data should be two requests to decrypt.

**Screenshots**
![MetaMask Error](https://github.com/jessgusclark/decrypt-error/raw/main/docs/metamask-error.jpg)

**Browser details (please complete the following information):**
- OS: Windows 
- Browser: ChromeVersion 87.0.4280.141 (Official Build) (64-bit)
- MetaMask Version 8.1.11

**Additional context (Error Messages, etc.)**

Full error message:

```
Message: Cannot read property 'from' of undefined

Code: TypeError

Stack:
TypeError: Cannot read property 'from' of undefined
  at Function.mapToProps (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:634958)
  at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:20773)
  at h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:19379)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:19586
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:12990
  at Object.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:64645)
  at useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:148:5250)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:12934)
  at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:59367)
  at Ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:67589)
  at Va (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:67408)
  at El (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:107905)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:184:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:45648)
  at au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:81:87618)
  at Object.notify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:24588)
  at e.t.notifyNestedSubs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:24155)
  at e.t.handleChangeWrapper (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:99:24223)
  at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:63292)
  at Object.dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:57268)
  at dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:77709)
  at clearConfirmTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:635276)
  at onClick (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:632984)
```

**Comment by tmashuang** [comment]
Unable to reproduce with the provided example dapp on the latest version, v9.0.4. v9,0.3 was pushed targeting issues with the `eth_decypt` methods, #10252 and #10243.

**Comment by jessgusclark** [comment]
Hello @tmashuang,

Thank you for looking into this. I wonder what is different about my setup since I am still getting the error.

I upgraded to the latest version of Metamask v9.0.4 and tried it again and still have the issue. I am attaching a short video of the error. 

When decrypting a single value, there isn't an issue, it only happens when multiple requests are sent at the same time.

https://user-images.githubusercontent.com/766679/106615881-92003c00-6575-11eb-9c51-cd54b06be736.mp4

**Comment by danfinlay** [comment]
Looks like the confirm component for the decrypt method is not properly handling a queue of these. The workaround would be to wait for user response after each call before making another `decrypt` call, until we fix this.

Thanks for the report!
