### ISSUE TITLE
YARN start doesnt working

### ISSUE THREAD

**Issue by eskrano** [MetaMask/metamask-extension#10983]
Hello all!

Trying to compile wallet and run it locally, cloned dev version and running on nodejs & windows 10

Got this errors

`scripts:core:dev:initSentry: Error#1: LavaMoat - required package not in whitelist: package "@gulp-sourcemaps\map-sources" requested "through2" as "through2"        
  at requireRelative (LavaMoat/core/kernel:518:15)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)
  at Object.eval (D:\wallet-project\node_modules\@gulp-sourcemaps\map-sources\index.js:4:15)
  at internalRequire (LavaMoat/core/kernel:457:25)
  at requireRelative (LavaMoat/core/kernel:498:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)
  at Object.eval (D:\wallet-project\node_modules\gulp-sourcemaps\index.js:7:15)
  at internalRequire (LavaMoat/core/kernel:457:25)
  at requireRelative (LavaMoat/core/kernel:498:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:470:16)

scripts:core:dev:ui: error Command failed with exit code 1.
scripts:core:dev:ui: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
MetaMask build: Encountered an error while running task "dev".
Error: MetaMask build: runInChildProcess for task "scripts:core:dev:background" encountered an error 1
    at ChildProcess.<anonymous> (D:\wallet-project\development\build\task.js:89:13)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at ChildProcess.cp.emit (D:\wallet-project\node_modules\cross-spawn\lib\enoent.js:34:29)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Google doesn't help me to solve this error, anyone can help me? 

Thanks

**Comment by ryanml** [comment]
Hi @eskrano - it looks like you may have done a regular yarn install. You should use the command `yarn setup` to do that before running `yarn start`. Let me know if that fixes your issue, thanks!

**Comment by eskrano** [comment]
> Hi @eskrano - it looks like you may have done a regular yarn install. You should use the command `yarn setup` to do that before running `yarn start`. Let me know if that fixes your issue, thanks!

Hello! Installed to ubuntu successfully, building it correctly, but how i can run it in dev mode like webpack dev server with hot reload? Where does it hosted in dev mode? 

Thanks!

**Comment by danjm** [comment]
After running `yarn setup` and `yarn start`, builds will automatically update upon making changes. We don't have hot reloading in the browser at this time. If you are trying to add your local build to the browser, follow these guides:
- https://github.com/MetaMask/metamask-extension/blob/develop/docs/add-to-chrome.md
- https://github.com/MetaMask/metamask-extension/blob/develop/docs/add-to-firefox.md
