### ISSUE TITLE
MetaMask encountered an error, Incorrect locale information provided

### ISSUE THREAD

**Issue by fabiodurgante** [MetaMask/metamask-extension#11047]
hey my metamask dont open i reinstall and nothing somebody help me ???

error 
MetaMask encountered an error, Incorrect locale information provided
rangeError: Incorrect locale information provided
  at new DateTimeFormat (<anonymous>)
  at r.getTranslatedUINoficiations (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:86362)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:410446
  at Array.map (<anonymous>)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:410388)
  at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:59367)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:104449)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:84094)
  at zu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:112010)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:113243
  at lu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87674)
  at Ku (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:113228)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:115151)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:1356094

**Comment by shangsj** [comment]
遇到了同样的问题： Incorrect locale information provided

>我找到解决办法了，https://github.com/MetaMask/metamask-extension/releases/tag/v9.4.0
>先在chrome里把metamask删除了。下载9.4的版本压缩包，然后解压，在扩展程序里安装。

来自：https://ask.csdn.net/questions/7428010

亲测有用。
