### ISSUE TITLE
Metamask extension is throwing an exception under certain conditions - rolling back to 9.4.0 works

### ISSUE THREAD

**Issue by joelgriffiths** [MetaMask/metamask-extension#11044]
9.5.0 appears to have introduced a bug that completely locks up the Metamask extension in Chrome. The only solution I've found is to reinstall the extension, and not try to work with the same contract. When I roll back to 9.4.0, the problem goes away.

In my case, it happens when I try to add liquidity to a dopple.finance LP farm. A number of other people have had similar issues on Dopple.finance on the BSC. I try to add LP liquidity to the DOP-BNB LP Farm, and this exception pops up. It appears the only way to fix the issue is to re-install metamask entirely (which is a problem in itself) as there are no other options provided to leave the error page.

After searching for a bit, I found this stackexchange post talking about a similar issue:
https://ethereum.stackexchange.com/questions/98738/metamask-9-5-0-has-bug-when-transferring-to-my-other-account-on-test-network

My error is similar, but the exception shows this message with a different string:
This method only supports 0x-prefixed hex strings but input was: Https://dopple.finance

**Screenshots**
https://i.stack.imgur.com/Om36r.png
https://ibb.co/GWbzxxD

**Browser details (please complete the following information):**
 - Chrome 90.0.4430.93
 - MetaMask Version: 9.5.0
 - BSC Network

**Additional context (Error Messages, etc.)**

**Comment by tmashuang** [comment]
Relate to https://github.com/MetaMask/metamask-extension/pull/10886.

**Comment by joelgriffiths** [comment]
Here is the full text of the error. I forgot to include it earlier.
```
Error: This method only supports 0x-prefixed hex strings but input was: Https://dopple.finance
  at Object.r.assertIsHexString (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:210305)
  at Object.r.toChecksumAddress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:201511)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:653574)
  at h.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:478592)
  at Ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70734)
  at Ka (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70529)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:105704)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87618)
  at Object.notify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24588)
  at e.t.notifyNestedSubs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24155)
  at e.t.handleChangeWrapper (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24223)
  at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:63254)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:57230
  at dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:59495)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:1350479
  at s.handleResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:4332)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at s.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at s.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:113:216469)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:31429)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34607
  at t.exports.v.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34634)
  at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:23642)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at t.exports.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at t.exports.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57176)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57026

```
