### ISSUE TITLE
Error trying to send AVAX (Avalanche Mainnet) to another wallet

### ISSUE THREAD

**Issue by Jonasslv** [MetaMask/metamask-extension#11075]
**Describe the bug**
When using metamask (Version 9.5.1 on Avalanche C-Chain Mainnet trying to send AVAX (native token, considered the ETH by EVM) it issues an error and the transaction is not made.

**Steps to reproduce (REQUIRED)**
Open Wallet, go in Send, Try to put an address then it just gives an error message.

**Expected behavior**
I was expecting it let me put an address and amount and press the send button so I can send AVAX to other address.

**Browser details (please complete the following information):**
 - OS: Windows 10 Pro 64bits Version 21H1
 - Hardware Wallet: Not Using
 - Browser: Brave V 1.24.84 Chromium: 90.0.4430.93 64 bits
 - MetaMask Version: 9.5.1

**Additional context (Error Messages, etc.)**
Message: This method only supports 0x-prefixed hex strings but input was: AVAX

Code: Error

Stack:
Error: This method only supports 0x-prefixed hex strings but input was: AVAX
  at Object.r.assertIsHexString (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:210305)
  at Object.r.toChecksumAddress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:201511)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:653608)
  at h.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:478626)
  at Ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70734)
  at Ka (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70529)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:105704)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:114643
  at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:114649)
  at fe (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:5411)
  at Rr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:29682)
  at Cr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:30610)
  at Tr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:29898)
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at le (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:114479)
  at Er (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:29321)
  at HTMLDocument.c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/initSentry.js:1:10460)

**Comment by blackboxtrading** [comment]
same thing happens to HECO, OKEXChain, etc etc

**Comment by tmashuang** [comment]
Would anyone experiencing this issue able to check if the latest release candidate, with a solution to fix this, fixes this issue? 
https://github.com/MetaMask/metamask-extension/pull/11073#issuecomment-840150263

**Comment by blackboxtrading** [comment]
where can we download the latest release?

**Comment by tmashuang** [comment]
In the link I posted.

**Comment by Jonasslv** [comment]
> In the link I posted.



> Would anyone experiencing this issue able to check if the latest release candidate, with a solution to fix this, fixes this issue?
> [#11073 (comment)](https://github.com/MetaMask/metamask-extension/pull/11073#issuecomment-840150263)

Just tested, it worked!

**Comment by blackboxtrading** [comment]
Do I have to build it myself...?

**Comment by Jonasslv** [comment]
> Do I have to build it myself...?

No, you download the build for chrome example, enable the chrome dev mode and click to load an unpacked extension.

**Comment by blackboxtrading** [comment]
Could you tell me where can I download the build...? I am not familar with github.. This issue could cost me greatly financially

**Comment by blackboxtrading** [comment]
I don't understand why it breaks all of sudden, I did not upgrade anything

**Comment by blackboxtrading** [comment]
when are you going to release the fix? can I update from chrome webstore?

**Comment by tmashuang** [comment]
Fixed by #11071 and included in [v9.5.2](https://github.com/MetaMask/metamask-extension/releases/tag/v9.5.2).
