### ISSUE TITLE
MetaMask encountered an error when paste a recipient address using custom RPC

### ISSUE THREAD

**Issue by DimmOFF** [MetaMask/metamask-extension#11079]
**Description:**

Want to send some token to another wallet in Expanse network. Press send icon, then paste a recipient address and I see the error message. I guess it is because of the latest update 

**Steps to reproduce:**

1. Add new Network:
Network Name: Expanse
New RPC URL: https://node.expanse.tech/
Chain ID: 2
Currency Symbol (optional): EXP
Block Explorer URL (optional): https://explorer.expanse.tech/
2. Press send icon.
3. Paste valid recipient address. 

**Actual behavior:** The error occurs 'MetaMask encountered an error'

**Browser details:**

OS: Windows 10
Browser Chrome 90.0.4430.93
MetaMask Version 9.5.1

**Screenshots**
![image](https://user-images.githubusercontent.com/2872443/118087571-6b506d80-b3ce-11eb-8b0e-c0cf6d425ce4.png)

Message: This method only supports 0x-prefixed hex strings but input was: EXP
Code: Error
Stack:
Error: This method only supports 0x-prefixed hex strings but input was: EXP
  at Object.r.assertIsHexString (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:210305)
  at Object.r.toChecksumAddress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:201511)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:653608)
  at h.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:478626)
  at Ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70734)
  at Ka (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70529)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:105704)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:114643
  at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:114649)
  at fe (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:5411)
  at Rr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:29682)
  at Cr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:30610)
  at Tr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:29898)
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at le (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:114479)
  at Er (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:29321)
  at HTMLDocument.c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/initSentry.js:1:10460)

**Comment by darvinrio** [comment]
the same thing happened while using matic for me , and i think alot of people have complained the same for different chains in the past 12 hours or so

**Comment by obslayer** [comment]
I met the same error after updating. Waiting for fix.

**Comment by obslayer** [comment]
9.5.2 fixed this issue

**Comment by DimmOFF** [comment]
Fixed by #11071 and included in v9.5.2
