### ISSUE TITLE
Matic network is broken in v9.5.1

### ISSUE THREAD

**Issue by rbisset82** [MetaMask/metamask-extension#11084]
Following the recent update to 9.5.1 it now isn't possible to send to another wallet on the Matic/Polygon network. 

Message: This method only supports 0x-prefixed hex strings but input was: MATIC

Code: Error

Stack:
Error: This method only supports 0x-prefixed hex strings but input was: MATIC
  at Object.r.assertIsHexString (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:210305)
  at Object.r.toChecksumAddress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:72:201511)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:653608)
  at h.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:478626)
  at Ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70734)
  at Ka (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:70529)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:105704)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87618)
  at Object.notify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24588)
  at e.t.notifyNestedSubs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24155)
  at e.t.handleChangeWrapper (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24223)
  at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:63254)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:57230
  at dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:59495)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:1350071
  at Object.dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:57221)
  at Object.dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:77703)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:1355915
  at s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3953)
  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:90211)
  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:90736)
  at s.handleResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:4155)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at s.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at s.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:113:216651)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:31429)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34607
  at t.exports.v.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34634)
  at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:23642)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at t.exports.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at t.exports.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57176)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57026

**Comment by brad-decker** [comment]
This is fixed in v9.5.2 which is in the process of rolling out, hang tight! Thanks for reporting!
