### ISSUE TITLE
Getting error "new BigNumber() not a base 16 number: undefined" when changing Account in MetaMask on V. 9.5.2

### ISSUE THREAD

**Issue by JF0001** [MetaMask/metamask-extension#11110]
After installing MetaMask Version 9.5.2 on the Chrome Browser, I am obtaining the error hereafter upon changing to an account that is already logged into my Dapp, in the MetaMask extension. As indicated, this error occurs only when the account is already logged into my Dapp. My Dapp monitors if an account is changed in MetaMask using `window.ethereum.on('accountsChanged', accounts =>` and calls a sign method in order to authenticate the user on the back-end when an account change is detected. My Dapp did not encounter this issue before upgrading to version 9.5.2 and I have not made any modification to my code since then. By closing and reopening the popup everything works, but this is obviously annoying for users. Also, please note that this occurs only when I am on the "Activity" tab in MetaMask and not when I am on the "Assets" tab, however, if I am on the "Assets" tab, the sign popup does not appear until I close and reopen MetaMask. Thank you for your help and time. J

MetaMask encountered an error
Try again by closing and reopening the popup, or contact support here.

Message: new BigNumber() not a base 16 number: undefined

Code: BigNumber Error

Stack:
BigNumber Error: new BigNumber() not a base 16 number: undefined
  at X (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:52:39805)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:52:45322)
  at new G (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:52:37269)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:632872)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:633556)
  at r.useCancelTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:654727)
  at E (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:382661)
  at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:59367)
  at jl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:104449)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:90053)
  at pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:89978)
  at iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87326)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45768
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:172:3472)
  at Vo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45477)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45713)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:45648)
  at au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:75:87618)
  at Object.notify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24588)
  at e.t.notifyNestedSubs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24155)
  at e.t.handleChangeWrapper (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:93:24223)
  at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:63254)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:57230
  at dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:59495)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:1350100
  at Object.dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:57221)
  at Object.dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:77703)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:152:1355944
  at s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3953)
  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:90211)
  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:90736)
  at s.handleResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:4155)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at s.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at s.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:113:216651)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:31429)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34607
  at t.exports.v.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:34634)
  at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:23642)
  at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:21106)
  at t.exports.i.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:59:24092)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18447)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:18262)
  at t.exports.y.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:137:19073)
  at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57176)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:81:57026

**Comment by brad-decker** [comment]
Thanks for reporting! This will be resolved with the forthcoming 9.5.3 hot fix that we hope to have ready Monday. This should *only* happen in full screen mode, I believe, if you can confirm and the actual sign pop up *should* work.

**Comment by JF0001** [comment]
Thank you @brad-decker Wonderful! Yes, I am experiencing it in the pop up. I haven't tried the full screen mode.
Thanks again. J

**Comment by JF0001** [comment]
This issue has been solved with Version 9.5.4. Thank you @brad-decker !
