### ISSUE TITLE
Upgrading to 10.0 for EIP1599 support breaks Polygon dApps

### ISSUE THREAD

**Issue by ryanmolden** [MetaMask/metamask-extension#11814]
After updating my Chrome Metamask extension to 10.0 I can no longer interact with any dApps on Polygon. Whenever a transaction is initiated it comes up with an error screen saying gas estimation failed and both the Confirm AND the Edit link are disabled meaning I can't even manually enter gas, all I can do is reject the transaction.

This is extra bad as I can't roll back to a previous version in any way that I can see, so all my dApps on Polygon are just broken.

**Steps to reproduce (REQUIRED)**
Go to any dApp on polygon (say Adamant Finance) and attempt to do a transaction (for me it is harvesting rewards specifically).

**Expected behavior**
I can do the transaction

**Screenshots**
I cannot do the transaction

**Browser details (please complete the following information):**
Windows
Chrome version 92.0.4515.131
Metamask Version 10.0

**Comment by danjm** [comment]
@ryanmolden If you are willing, it would be helpful if you could grab your state logs when you are on the confirm screen, and securely submit them to us via our customer support channel.s

1. Get to the state where the confirm and edit button are disabled
2. open the developer tools
3. enter `logState(true)` in the developer console, this will copy json text to your clipboard
4. paste into a text file and save
5. submit the file via the form found here: https://metamask.zendesk.com/hc/en-us/requests/new

**Comment by ryanmolden** [comment]
Submitted, the UI isn't super clear but I think the submitted case/ticket # is 274999

**Comment by danjm** [comment]
thank-you!

**Comment by ryanmolden** [comment]
Interestingly I just found if I leave the confirmation dialog up for like 20+ seconds it eventually allows me to use the edit link (yay), originally it flashes and says it failed so I was rejecting the txns / closing the prompt dialog, but apparently leaving it for a bit allows me to manually edit it, so unblocked, but still a pretty poor experience :P

**Comment by ryanmolden** [comment]
Spoke too soon, after manually entering the gas and saving and confirming it fails with this message

Message: fromMillis requires a numerical input, but received a undefined with value undefined

Code: Error

Stack:
Error: fromMillis requires a numerical input, but received a undefined with value undefined
  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:1012)
  at t.n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:1375)
  at t [as constructor] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:2393)
  at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:2987)
  at Function.e.fromMillis (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:59007)
  at r.formatDate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:22:8393)
  at m.renderActivity (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:5511)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:6410
  at Array.map (<anonymous>)
  at m.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:6393)
  at Zi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:70924)
  at Xi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:70719)
  at Cl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:105712)
  at _u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:90255)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:90180)
  at fu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:87528)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:45966
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:35:3472)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:45675)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:45911)
  at Xo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:45846)
  at le (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:114533)
  at On (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:10:29309)
  at HTMLDocument.c (chrome-extension://n

**Comment by danjm** [comment]
thanks for the extra info

**Comment by guanbinrui** [comment]
I have got an error message while I was using [Quickswap](
![image](https://user-images.githubusercontent.com/52657989/129208761-50a24a9f-b966-43c0-85be-da03329f90b1.png)
).

![image](https://user-images.githubusercontent.com/52657989/129208769-5e7bb1a0-1e8b-4b1a-99f0-e87bb76b5c28.png)

**Comment by danjm** [comment]
Hi @ryanmolden

We are working on a fix here. While we do so, and if you are still experiencing the issue, you might have success by changing the RPC url for the polygon network to one of the one's listed here https://docs.matic.network/docs/develop/network-details/network/

**Comment by JHGrove3** [comment]
Is this related to the bug I just submitted for xDai network signing?

https://github.com/MetaMask/metamask-extension/issues/11847
