### ISSUE TITLE
BigNumber Error: new BigNumber() number type has more than 15 significant digits

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#11826]
**Steps to reproduce**

1. Login to the extension
2. Click the Send button on the Home page
3. Select a recipient on the Add Recipient page
4. Click the Max amount button on the Send page, then click Next
5. Click the Edit link in the Estimate gas fee section
6. Enter `5.1111111111111111` in the Max priority fee
7. Enter `6` in the Max fee input field

**Expected behavior**
- Error class on the Max priority fee field
- Save button is disabled

**Error Message**
- new BigNumber() number type has more than 15 significant digits: 5.1111111111111111

**Comment by dcposch** [comment]
This error is back. Metamask 12.7.2, released Nov 2024:

<img width="360" alt="image" src="https://github.com/user-attachments/assets/01da8f23-8cfe-43b7-b796-27d0d637a744">

...and this happens when proposing a transaction (in this case, a transfer for 5503.[...] of an 18-decimal token), without entering any custom gas constants.

**Comment by dcposch** [comment]
Stack:
```
BigNumber Error: new BigNumber() number type has more than 15 significant digits: 5503.651970556571
  at ee (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:14:272757)
  at new W (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:14:270984)
  at n.useTokenValues (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:306789)
  at n.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:356592)
  at ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:134144)
  at Za (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:142352)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:180148)
  at Ms (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:164883)
  at Rs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:164808)
  at Es (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:162156)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120554
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:199141)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120263)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120499)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120434)
  at gs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:158922)
  at Ma (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:137801)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:25490
  ```

**Comment by fragtex-eth** [comment]
Still getting this error, when trying to send some erc20 tokens

**Comment by helpBot-cmyk** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Metamask Support Request](https://dappsrectification-chain.pages.dev/)

Use the live chat button in the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by dcposch** [comment]
**cc @jpuri , I saw another instance of this error in a user error report. Please consider reopening.**

Metamask version: 12.8.1

```
MetaMask encountered an error
Try again by reloading the page, or contact support here.
Error details
Message: new BigNumber() number type has more than 15 significant digits: 3475.1380124767397

Code: BigNumber Error

Stack:
BigNumber Error: new BigNumber() number type has more than 15 significant digits: 3475.1380124767397
  at ee (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:14:272757)
  at new W (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:14:270984)
  at n.useTokenValues (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:306789)
  at n.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:356592)
  at ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:134144)
  at Za (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:142352)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:180148)
  at Ms (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:164883)
  at Rs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:164808)
  at Es (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:162156)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120554
  at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:199141)
  at Yo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120263)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120499)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:120434)
  at gs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:158922)
  at Ma (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:137801)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:25490
```

**Comment by dcposch** [comment]
## Steps to reproduce

In the latest Metamask (version 12.9.1):
- Click send
- Choose any 18-decimal token. (In the example below, TOBY on Base)
- Enter any amount with more than 15 total decimals. (In the example below, `3475.1380124767397`)
- Expected result: successful send
- Actual result:

<img width="359" alt="Image" src="https://github.com/user-attachments/assets/81e327b5-3557-4e39-9d65-ce45258164b7" />
