### ISSUE TITLE
Firefox blank metamask window.

### ISSUE THREAD

**Issue by Gershon-A** [MetaMask/metamask-extension#12022]
Metamask on FireFox does not open - shown blank window

**Steps to reproduce **

1. Click on `Metamask` firefox extension.

**Browser details (please complete the following information):**
 - OS:  Windows
 - Browser: Firefox Browser 91.0.2 (64-bit)
 - MetaMask Version: 10.0.3

**Additional context (Error Messages, etc.)**
From the FireFox debug:

```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). 2 moz-extension:2:391199
Error: Please use $(ref:runtime.lastError). binary.js:1
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:970
Removing intrinsics.%StringPrototype%.at sentry-install.js:8:36389
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:2105:39
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Error: An unexpected error occurred
sentry-install.js:8:36389
uncaught exception: null
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:970
Removing intrinsics.%StringPrototype%.at sentry-install.js:8:36389
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:2105:39
g_CS[e] is null 4 background.js:1
[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 74"  data: no] ExtensionCommon.jsm:74:12
    runSafeSyncWithoutClone resource://gre/modules/ExtensionCommon.jsm:74
    cssPromise resource://gre/modules/ExtensionContent.jsm:524
g_CS[e] is null background.js:1
g_CS[e] is null 10 background.js:1
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:970
Removing intrinsics.%StringPrototype%.at sentry-install.js:8:36389
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). moz-extension:2105:39
```

![alt text](https://i.imgur.com/FyBHI73.png "Logo Title Text 1")
The same MetaMask Version: 10.0.3 on the same machine worked with Brave and Chrome.

**Comment by Eninspace** [comment]
Same issue
Metamask on FireFox does not open - shown blank window

Browser details (please complete the following information):

    OS: Windows
    Browser: Firefox Browser 91.0.2 (64-bit)
    MetaMask Version: 10.0.3

Additional context (Error Messages, etc.)

```
10:53:33.326 Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:970
10:53:33.358 Removing intrinsics.%StringPrototype%.at sentry-install.js:8:36389
10:53:33.384 unreachable code after return statement
ui-3.js:7:238933
10:53:33.384 unreachable code after return statement
ui-3.js:7:239657
10:53:33.384 unreachable code after return statement
ui-3.js:7:243345
10:53:33.621 unreachable code after return statement
ui-3.js:7:238933
10:53:33.839 Content Security Policy: The page's settings blocked the loading of a resource at eval («script-src»). moz-extension:2105:39
```

**Comment by kevinghim** [comment]
Related to #9196

**Comment by Gershon-A** [comment]
Update: I've removed Metamask from FireFox and re-installed it. Seems to have fixed the blank issue.
Lucky Me, I have all my accounts data backed up.

**Comment by RomanHiden** [comment]
I am having exact same issue with exact same errors on 95.0 (64-bit) ubuntu
