### ISSUE TITLE
`params` is required, despite the JSON-RPC spec saying it is optional.

### ISSUE THREAD

**Issue by MicahZoltu** [MetaMask/metamask-extension#1216]
http://www.jsonrpc.org/specification#request_object
> params
> [...] This member MAY be omitted.

1. Open a chrome browser window with MetaMask extension active
2. Open the dev console.
3. Type: `window.web3.currentProvider.sendAsync({jsonrpc: "2.0", id: 1, method: "net_version"}, (error, result) => console.log(error, result));`
4. Notice the error.
5. Type: `window.web3.currentProvider.sendAsync({jsonrpc: "2.0", id: 1, method: "net_version", params: []}, (error, result) => console.log(error, result));`
6. Notice no error.

Error message:
```
TypeError: Cannot read property '0' of undefined
    at SanitizerSubprovider.handleRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:102944:32)
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:101039:18)
    at NonceTrackerSubprovider.handleRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:102847:7)
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:101039:18)
    at DefaultFixtures.FixtureProvider.handleRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:102400:5)
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:101039:18)
    at Web3ProviderEngine._handleAsync (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:101026:3)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:101010:12
```

**Comment by bdresser** [comment]
Closing due to inactivity - if this is still relevant, feel free to open a new issue.

**Comment by MicahZoltu** [comment]
@bdresser I just tested again and this bug is still present in the latest version of MetaMask on Chrome.

**Comment by Gudahtt** [comment]
It looks like this was fixed sometime before v7? I can no longer reproduce on v8.0.0 in any case.
