### ISSUE TITLE
MetaMask 遇到了一个错误

### ISSUE THREAD

**Issue by xinian1239527** [MetaMask/metamask-extension#12810]
信息：Function.prototype.apply was called on undefined, which is a undefined and not a function

代码：TypeError

栈：
TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
  at chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-3.js:1:169487
  at chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-3.js:1:170997
  at Object.assign.cameraDistance (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-2.js:1:493320)
  at c (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-3.js:1:170164)
  at createLogoViewer (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-3.js:1:170521)
  at t.exports (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-2.js:1:493273)
  at new d (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-2.js:1:316555)
  at Ii (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:76780)
  at Xa (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:93570)
  at Cu (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:131188)
  at _s (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:115731)
  at bs (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:115656)
  at fs (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:113004)
  at chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:71442
  at n.unstable_runWithPriority (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:8:33220)
  at Ko (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:71151)
  at Zo (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:71387)
  at Xo (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:71322)
  at ps (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:113377)
  at el (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:138712)
  at render (chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:140629)
  at chrome-extension://iknmhdbnilhicodlehiagpkmnfkahggl/ui-0.js:1:5615

**Comment by xinian1239527** [comment]
![image](https://user-images.githubusercontent.com/94932675/143112023-7dcf8d12-6d2a-4b9a-9118-d7cfd1ad6255.png)

**Comment by ModChRam** [comment]
I have the same issue. Cant change network, cant do anything.

Most work arounds seem to focus on chrome-extension://EXTENSIONID/home.html#settings

but this url cant be reached.

**Comment by CryptoKira** [comment]
Got the error too. 
Need a fix asap @kumavis

**Comment by xinian1239527** [comment]
Version 10.5.2
it is ok

**Comment by xinian1239527** [comment]
Version 10.6.2 it is not

**Comment by kumavis** [comment]
what browsers are y'all using?

![image](https://user-images.githubusercontent.com/1474978/143136474-3c3a6aaa-380c-4ece-8cd1-723488371ba5.png)

**Comment by ModChRam** [comment]
Chrome 75.0.3770.80
Metamask 10.6.1

**Comment by kumavis** [comment]
@ModChRam your chrome version is extremely old and insecure!

**Comment by xinian1239527** [comment]
Chromium: 80.0.3987.163 Res: 2110.492

**Comment by CryptoKira** [comment]
LINUX Brave Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)

**Comment by kumavis** [comment]
my brave is Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (64-bit)

**Comment by kumavis** [comment]
please please please update your browsers

we'll publish a fix for older browsers soon

but you are not safe running old browsers

**Comment by xinian1239527** [comment]
The browser is up to date

**Comment by kumavis** [comment]
@xinian1239527 no, **chromium** is at least
> Version 96.0.4664.45 (Official Build) (64-bit)

**Comment by CryptoKira** [comment]
updated my browser, working now.

**Comment by kumavis** [comment]
insecure versions can be found here https://browser-update.org/browsers.html

**Comment by btz1024** [comment]
> please please please update your browsers
> 
> we'll publish a fix for older browsers soon
> 
> but you are not safe running old browsers

I just updated my chrome, the metamask error remains. Should I restart chrome ?

**Comment by sunilpawar1144** [comment]
Hello

I am getting the same error, I am trying to understand what is the final solution ?

Can someone please help

Thanks

**Comment by btz1024** [comment]
> > > please please please update your browsers
> > > we'll publish a fix for older browsers soon
> > > but you are not safe running old browsers
> > 
> > 
> > I just updated my chrome, the metamask error remains. Should I restart chrome ?
> 
> retarted chrome and computer, error remains.

Google Chrome 已是最新版本
版本 81.0.4044.92（正式版本） （64 位）
MetaMask
版本
10.6.1

**Comment by btz1024** [comment]
> > > > please please please update your browsers
> > > > we'll publish a fix for older browsers soon
> > > > but you are not safe running old browsers
> > > 
> > > 
> > > I just updated my chrome, the metamask error remains. Should I restart chrome ?
> > 
> > 
> > retarted chrome and computer, error remains.
> 
> Google Chrome 已是最新版本 版本 81.0.4044.92（正式版本） （64 位） MetaMask 版本 10.6.1

Chrome  81.0.4044.92
MetaMask  10.6.1

**Comment by sasguo** [comment]
> > > > > 请更新您的浏览器，
> > > > > 我们将很快发布针对旧浏览器的修复程序，
> > > > > 但您无法安全地运行旧浏览器
> > > > 
> > > > 
> > > > 我刚刚更新了我的 chrome，元掩码错误仍然存​​在。我应该重新启动 chrome 吗？
> > > 
> > > 
> > > 重新启动chrome和计算机，错误仍然存​​在。
> > 
> > 
> > Google Chrome 已是最新版本 81.0.4044.92（正式版本）（64 位） MetaMask 版本 10.6.1
> 
> 铬 81.0.4044.92 元 掩码 10.6.1

Hello, I also encountered the same problem, now can not open the met
![错误](https://user-images.githubusercontent.com/95101745/143622436-fab80b7f-1352-424c-8851-2ecb6b42f29b.png)
amask you solve it? Thank you
