### ISSUE TITLE
lavamoat whitelist error when building master

### ISSUE THREAD

**Issue by superqd** [MetaMask/metamask-extension#13253]
When I pull the latest master branch copy and try to build, I get the following error.

1. I ran yarn setup
2. I ran yarn build dev
3. Got the error:

Error: LavaMoat - required node builtin package not in whitelist: package "@nodelib\fs.stat" requested "fs" as "fs"
  at requireRelative (LavaMoat/core/kernel:519:15)
  at requireRelativeWithContext (LavaMoat/core/kernel:471:16)
  at Object.eval (D:\projects\nft\metamask\node_modules\@nodelib\fs.stat\out\adapters\fs.js:4:12)
  at internalRequire (LavaMoat/core/kernel:458:25)
  at requireRelative (LavaMoat/core/kernel:499:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:471:16)
  at Object.eval (D:\projects\nft\metamask\node_modules\@nodelib\fs.stat\out\settings.js:4:12)
  at internalRequire (LavaMoat/core/kernel:458:25)
  at requireRelative (LavaMoat/core/kernel:499:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:471:16)

I am running node 14.15.1, yarn 1.22.17.

I also tried running this:

yarn add @nodelib\fs.stat

I then ran yarn build dev again, and got this error:

TypeError: Cannot assign to read only property 'name' of function 'function createError(opts) {
        var result = new Error();

        Object.defineProperty(result, 'type', {...<omitted>... }'
  at extend (D:\projects\nft\metamask\node_modules\xtend\mutable.js:12:29)
  at TypedError (D:\projects\nft\metamask\node_modules\error\typed.js:26:5)
  at Object.eval (D:\projects\nft\metamask\node_modules\body\any.js:10:28)
  at internalRequire (LavaMoat/core/kernel:458:25)
  at requireRelative (LavaMoat/core/kernel:499:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:471:16)
  at Object.eval (D:\projects\nft\metamask\node_modules\tiny-lr\src\server.js:36:12)
  at internalRequire (LavaMoat/core/kernel:458:25)
  at requireRelative (LavaMoat/core/kernel:499:27)
  at requireRelativeWithContext (LavaMoat/core/kernel:471:16)

Any ideas?  I'm very unfamiliar with lavamoat...

**Comment by BoxedFruits** [comment]
I've been having the same problem

**Comment by BoxedFruits** [comment]
i switched to linux and everything runs for the most part now. it still taking forever to build things though

**Comment by superqd** [comment]
I have not tried this on linux, but it still fails on Windows

**Comment by EmanCanCode** [comment]
I had the same error. I have used Linux and it worked for me. ubuntu v20.04

**Comment by jesseharte** [comment]
Possible duplicate of #10748.

**Comment by weizman** [comment]
Encountered the same issue, here's my experience:

In my case, it seems that the issue pops up whenever I change something that has to do with the project's dependencies, such as `yarn install` when a package changes or something like that.

What fixed it immediately for me was to simply rerun `yarn setup` command before trying to build the project.

Let me know if that helped

**Comment by dhruvv173** [comment]
hey @superqd were you able to find a way around this?
