### ISSUE TITLE
[Bug]: Connected sites cannot read properties of null

### ISSUE THREAD

**Issue by leemason** [MetaMask/metamask-extension#13782]
### Describe the bug

In my most used account (most connected sites) i can no longer load/view the connected sites (latest version as of today).

This does not happen on all accounts, only my most used one.

Initial diagnosis appears to be an issue with sentry reporting which consistently reports a 429 error. But of course sentry is trying to report another issue so it's unclear whats happening.

Two guesses are:

1. i have a large number of connected sites and this is causing an issue (unlikley, i have quite a few connected sites but i do clear them quite frequently)
2. maybe some unhandled error cases loading the favicons for the connected sites to display in the ui is causing an issue.

This is quite an issue as i find myself frequently disconnecting/reconnecting different accounts as not all sites handle it very well so until this is resolved i may be a difficult situation unable to use the sites in question.

In addition to reporting the bug i would also like to know if there is a location i can manually clear some of my connected sites (im a developer so dont mind getting down and dirty if required).

And finally a request ive actually had for a long time before this bug came about is if there would be a way to mass clear connected sites, its quite a pain having to disconnect 1 by 1 when there are 5+ sites you want to remove.

### Steps to reproduce

1. try to load connected sites
2. be shown the error reporting screen

### Error messages or log output

```shell
Message: Cannot read properties of null (reading 'length')

Code: TypeError

Stack:
TypeError: Cannot read properties of null (reading 'length')
  at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:151830)
  at hi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:88703)
  at Ru (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:133461)
  at Es (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:119377)
  at bs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:119302)
  at fs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:116650)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:75108
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:257189)
  at Ko (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:74817)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:75053)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:74988)
  at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:143503)
  at On (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:1:58475)
  at HTMLDocument.a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:10429)
```

### Version

10.10.1

### Browser

Brave

### Operating system

MacOS

**Comment by testaccount12345948** [comment]
Did you ever find a solution to this?

**Comment by leemason** [comment]
nope, still broken for me

**Comment by testaccount12345948** [comment]
I found a temporary fix and that was to delete the extension and reinstall it, but having the same issue again today.

**Comment by danjm** [comment]
This should be fixed in v10.11.2, which should be released very soon

**Comment by danjm** [comment]
Is anyone who is experiencing this connecting MetaMask to another extension? Or regularly using another extension alongside metamask?

**Comment by leemason** [comment]
> Is anyone who is experiencing this connecting MetaMask to another extension? Or regularly using another extension alongside metamask?

In which way? I have tons of extensions but not really used in sync with metamask directly. I do connect metamask to localhost quite frequently, and i do have an extension that calls metamask directly but i havent used it in a long time, definatly not used it long before this issue started appearing.

Do you have a pr reference to the fix?

**Comment by danjm** [comment]
fixed by https://github.com/MetaMask/metamask-extension/pull/13974
