### ISSUE TITLE
[Bug]: Uncaught exception closing speed up/cancel modal

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14293]
### Describe the bug

An unhandled exception is thrown when the user closes the speed up/cancel transaction modal

### Steps to reproduce

1. Switch to Rinkeby Test Network
2. Settings -> Experimental -> Enable Enhanced Gas Fee UI
3. Create a send transaction
4. Submit the transaction with extremely low gas (0.1 max base fee, 0.1 Priority fee)
5. Click Speed up/Cancel
6. Click Close

### Error messages or log output

```shell
TypeError: e.forEach is not a function
  at closeModal(metamask/ui-2.js:1:318291)
  at onClose(metamask/ui-6.js:1:2746)
  at Object.h(metamask/ui-0.js:1:29475)
  at k(metamask/ui-0.js:1:29618)
  at ? (metamask/ui-0.js:1:29764)
  at x(metamask/ui-0.js:1:29850)
  at C(metamask/ui-0.js:1:30276)
  at P(metamask/ui-0.js:1:30111)
  at R(metamask/ui-0.js:1:30459)
  at En(metamask/ui-0.js:1:57440)
  at le(metamask/ui-0.js:1:142928)
  at Rn(metamask/ui-0.js:1:58055)
  at Mn(metamask/ui-0.js:1:59012)
  at Dn(metamask/ui-0.js:1:58300)
  at n.unstable_runWithPriority(metamask/ui-0.js:1:268218)
  at Ko(metamask/ui-0.js:1:74065)
  at se(metamask/ui-0.js:1:142705)
  at On(metamask/ui-0.js:1:57723)
  at HTMLDocument.a(metamask/sentry-install.js:1:10465)
```

### Version

10.13.0

### Browser

Chrome

### Operating system

MacOS

**Comment by bschorchit** [comment]
The error message appears in the UI to the user or only on the dev console? @PeterYinusa 
Asking as we're trying to understand if this is a release blocker or not.
