### ISSUE TITLE
[Bug]: Unhandled exception thrown when rejecting the watch asset confirmation - Uncaught (in promise) Error: User rejected to watch the asset.

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14428]
### Describe the bug

An unhandled exception is thrown when the user rejects the add suggested token confirmation

### Steps to reproduce

1. Login to the extension
2. Connect to the test dapp https://metamask.github.io/test-dapp/
3.Click `Create Token` and confirm the transaction
4. Click `Add Token to Wallet` and reject the transaction

### Error messages or log output

```shell
Error: User rejected to watch the asset.
  at s.<anonymous>(metamask/common-1.js:1:377067)
  at Object.y(metamask/common-0.js:1:192399)
  at h(metamask/common-0.js:1:191086)
  at s.emit(metamask/common-0.js:1:194081)
  at g.rejectWatchAsset(metamask/common-1.js:1:378005)
  at a.<anonymous>(metamask/background-0.js:1:157359)
  at h(metamask/common-0.js:1:191086)
  at a.s.emit(metamask/common-0.js:1:194081)
  at b(metamask/common-0.js:18:57392)
  at v(metamask/common-0.js:18:57207)
  at a._.push(metamask/common-0.js:18:58021)
  at t.exports._write(metamask/common-0.js:18:170606)
  at _(metamask/common-0.js:18:49493)
  at ? (metamask/common-0.js:18:52677)
  at t.exports.y.write(metamask/common-0.js:18:52704)
  at t.exports.m(metamask/common-0.js:18:62592)
  at h(metamask/common-0.js:1:191086)
  at t.exports.s.emit(metamask/common-0.js:1:194081)
  at b(metamask/common-0.js:18:57392)
  at v(metamask/common-0.js:18:57207)
  at t.exports._.push(metamask/common-0.js:18:58021)
  at t.exports._onMessage(metamask/common-0.js:1:22163)
  at ? (metamask/common-0.js:1:22010)
```

### Version

10.12.4

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
Fixed in v10.15.0
