### ISSUE TITLE
[Bug]: Insufficient number of substitutions for key "insufficientCurrency" with locale "en"

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#14446]
### Describe the bug

Error thrown when insufficient currency actionable message is shown

<img width="1616" alt="insufficientCurrency error" src="https://user-images.githubusercontent.com/53189696/163449489-0660836b-77ee-4794-9dff-a1af9c110022.png">

### Steps to reproduce

1. Switch to Polygon Mainnet - Matic
2. Settings > Experimental > Enable Enhanced Gas Fee UI
3. Click the Send button on the overview page
4. Enter a recipient
5. Click the Max amount button, click Next
6. Click Edit Gas fee, select Advance, increase the Max base fee and Priority fee, click Save

### Error messages or log output

```shell
Error: Insufficient number of substitutions for key "insufficientCurrency" with locale "en"
  at common-1.js:32:57040
  at Array.map (<anonymous>)
  at n.getMessage (common-1.js:32:56853)
  at ui-0.js:1:153698
  at x.render (ui-6.js:1:111571)
  at Ji (ui-0.js:1:100781)
  at Zi (ui-0.js:1:100576)
  at Cs (ui-0.js:1:135439)
  at ku (ui-0.js:1:120100)
  at bu (ui-0.js:1:120025)
  at fu (ui-0.js:1:117373)
  at ui-0.js:1:75831
  at n.unstable_runWithPriority (ui-0.js:1:267446)
  at Ko (ui-0.js:1:75540)
  at Jo (ui-0.js:1:75776)
  at Zo (ui-0.js:1:75711)
  at du (ui-0.js:1:117665)
  at Object.notify (ui-0.js:1:273522)
  at e.t.notifyNestedSubs (ui-0.js:1:273089)
  at e.t.handleChangeWrapper (ui-0.js:1:273157)
  at y (common-5.js:1:247924)
  at common-5.js:1:248652
  at dispatch (common-5.js:1:246089)
  at common-1.js:7:49947
  at Object.dispatch (common-5.js:1:248643)
  at ui-0.js:1:5386
  at a.<anonymous> (ui-0.js:1:1017)
  at u (common-0.js:1:104935)
  at a.emit (common-0.js:1:105471)
  at s.handleResponse (ui-0.js:1:1374)
  at h (common-0.js:1:182417)
  at a.s.emit (common-0.js:1:185412)
  at b (common-0.js:16:74743)
  at _ (common-0.js:16:74558)
  at a.v.push (common-0.js:16:75372)
  at t.exports._write (common-0.js:18:110259)
  at v (common-0.js:16:66844)
  at common-0.js:16:70028
  at t.exports.y.write (common-0.js:16:70055)
  at t.exports.g (common-0.js:16:79943)
  at h (common-0.js:1:182417)
  at t.exports.s.emit (common-0.js:1:185412)
  at b (common-0.js:16:74743)
  at _ (common-0.js:16:74558)
  at t.exports.v.push (common-0.js:16:75372)
  at t.exports._onMessage (common-0.js:1:14123)
  at common-0.js:1:13970
```

### Version

10.12.4

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
From v10.13.0 this error has changed to `Insufficient number of substitutions for key "insufficientCurrencyBuyOrDeposit" with locale "en"`
