### ISSUE TITLE
[Bug]: Cannot build metamask locally using `yarn start` 

### ISSUE THREAD

**Issue by nik-suri** [MetaMask/metamask-extension#14592]
### Describe the bug

I am following the instructions in the README file to start metamask in development mode. I have completed the following steps:
1. `nvm use`
2. `yarn setup`

Now when I attempt to run `yarn start`, I am met with a host of errors:

### Steps to reproduce

1. Clone the metamask git repository.
2. Follow the steps in the README

I am running on WSL Ubuntu 20.04.3 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64).
Node v14.19.1
Yarn 1.22.18

### Error messages or log output

```shell
yarn run v1.22.18
$ yarn build:dev --apply-lavamoat=false
$ node development/build/index.js dev --apply-lavamoat=false
Running task "dev"...
Starting 'dev'...
Starting 'clean'...
Finished 'clean'
Starting 'styles:dev'...
Finished 'styles:dev'
Starting 'scripts:core:dev:standardEntryPoints'...
Starting 'scripts:core:dev:contentscript'...
Starting 'scripts:core:dev:disable-console'...
Starting 'scripts:core:dev:sentry'...
Starting 'scripts:core:dev:phishing-detect'...
Starting 'static:dev'...
Starting 'manifest:dev'...
Starting 'reload'...
Finished 'reload'
Finished 'manifest:dev'
Finished 'static:dev'
[19:41:04] /home/nik-suri/code/metamask-extension/ui/css/output/index.css reloaded.
[19:41:04] /home/nik-suri/code/metamask-extension/ui/css/output/index-rtl.css reloaded.
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index.css reloaded.
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index-rtl.css reloaded.
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index.css reloaded.
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index-rtl.css reloaded.
(node:7144) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink './dist/firefox/index-rtl.css'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index.css reloaded.
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index-rtl.css reloaded.
scripts:core:dev:contentscript:
... Uhoh. Got error listen EADDRINUSE: address already in use :::35729 ...
Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Server.listen (/home/nik-suri/code/metamask-extension/node_modules/tiny-lr/src/server.js:264:19)
    at Function.exports.listen (/home/nik-suri/code/metamask-extension/node_modules/gulp-livereload/index.js:95:18)
    at devReload (/home/nik-suri/code/metamask-extension/development/build/etc.js:24:16)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:135:11
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:50
    at Array.map (<anonymous>)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:33

You already have a server listening on 35729
You should stop it and try again.

(node:7144) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod './dist/firefox/index-rtl.css'
(node:7144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index.css reloaded.
(node:7144) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink './dist/firefox/index-rtl.css'
(node:7144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:7144) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod './dist/opera/index.css'
(node:7144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
[19:41:05] /home/nik-suri/code/metamask-extension/ui/css/output/index-rtl.css reloaded.
scripts:core:dev:standardEntryPoints:
... Uhoh. Got error listen EADDRINUSE: address already in use :::35729 ...
Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Server.listen (/home/nik-suri/code/metamask-extension/node_modules/tiny-lr/src/server.js:264:19)
    at Function.exports.listen (/home/nik-suri/code/metamask-extension/node_modules/gulp-livereload/index.js:95:18)
    at devReload (/home/nik-suri/code/metamask-extension/development/build/etc.js:24:16)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:135:11
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:50
    at Array.map (<anonymous>)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:33

You already have a server listening on 35729
You should stop it and try again.

scripts:core:dev:disable-console:
... Uhoh. Got error listen EADDRINUSE: address already in use :::35729 ...
Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Server.listen (/home/nik-suri/code/metamask-extension/node_modules/tiny-lr/src/server.js:264:19)
    at Function.exports.listen (/home/nik-suri/code/metamask-extension/node_modules/gulp-livereload/index.js:95:18)
    at devReload (/home/nik-suri/code/metamask-extension/development/build/etc.js:24:16)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:135:11
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:50
    at Array.map (<anonymous>)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:33

You already have a server listening on 35729
You should stop it and try again.

(node:7144) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod './dist/firefox/index-rtl.css'
(node:7144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
scripts:core:dev:sentry:
... Uhoh. Got error listen EADDRINUSE: address already in use :::35729 ...
Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Server.listen (/home/nik-suri/code/metamask-extension/node_modules/tiny-lr/src/server.js:264:19)
    at Function.exports.listen (/home/nik-suri/code/metamask-extension/node_modules/gulp-livereload/index.js:95:18)
    at devReload (/home/nik-suri/code/metamask-extension/development/build/etc.js:24:16)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:135:11
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:50
    at Array.map (<anonymous>)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:33

You already have a server listening on 35729
You should stop it and try again.

scripts:core:dev:phishing-detect:
scripts:core:dev:phishing-detect: ... Uhoh. Got error listen EADDRINUSE: address already in use :::35729 ...
scripts:core:dev:phishing-detect: Error: listen EADDRINUSE: address already in use :::35729
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Server.listen (/home/nik-suri/code/metamask-extension/node_modules/tiny-lr/src/server.js:264:19)
    at Function.exports.listen (/home/nik-suri/code/metamask-extension/node_modules/gulp-livereload/index.js:95:18)
    at devReload (/home/nik-suri/code/metamask-extension/development/build/etc.js:24:16)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:135:11
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:50
    at Array.map (<anonymous>)
    at /home/nik-suri/code/metamask-extension/development/build/task.js:153:33
scripts:core:dev:phishing-detect:
scripts:core:dev:phishing-detect: You already have a server listening on 35729
scripts:core:dev:phishing-detect: You should stop it and try again.
scripts:core:dev:phishing-detect:
scripts:core:dev:disable-console: MetaMask build: Encountered an error while running task "dev".
scripts:core:dev:disable-console: [Error: ENOENT: no such file or directory, chmod 'dist/firefox/_locales/zh_CN/messages.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path: 'dist/firefox/_locales/zh_CN/messages.json'
}
scripts:core:dev:disable-console: error Command failed with exit code 1.
scripts:core:dev:disable-console: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
MetaMask build: Encountered an error while running task "dev".
Error: MetaMask build: runInChildProcess for task "scripts:core:dev:disable-console" encountered an error "1".
    at ChildProcess.<anonymous> (/home/nik-suri/code/metamask-extension/development/build/task.js:119:13)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Version

10.13.0

### Build type

Beta

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Linux

### Additional context

Not reaching the browser. This is a build issue.

**Comment by Anastacia-43** [comment]
HI @nik-suri  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> METAMASK SUPPORT

**Comment by Anastacia-43** [comment]
HI @nik-suri  have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#)

**Comment by Gudahtt** [comment]
Thanks for the report @nik-suri !

It looks like `gulp-livereload` was failing to start because something else was using that port. It's possible you had the build running in a different terminal, or maybe an earlier build attempt was still running in the background.

We are planning on [making the "live reload" behavior optional soon](https://github.com/MetaMask/metamask-extension/issues/12767), so once that change is implemented it will be easier to workaround this problem.

I'll close this for now because I believe this is an issue with your environment rather than a bug, but please let us know if you manage to get this working and we can investigate further if necessary.

**Comment by umaresso** [comment]
i have the same issue
