### ISSUE TITLE
[Bug]: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'gas')

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#15183]
### Describe the bug

Unhandled exception is thrown when progressing to the confirm screen for an ERC20 Token Send. Needs further investigation for reliable reproduction steps

### Steps to reproduce

Needs further investigation, will look into this tomorrow

### Error messages or log output

```shell
TypeError: Cannot read properties of undefined (reading 'gas')
  at Object.updateGasLimit(metamask/common-8.js:1:88306)
  at ? (metamask/common-8.js:1:93089)
  at ? (metamask/common-1.js:1:13536)
  at produce(metamask/common-5.js:3:34153)
  at ? (metamask/common-1.js:1:13513)
  at Array.reduce(<anonymous>)
  at ? (metamask/common-1.js:1:13382)
  at ? (metamask/common-7.js:1:71714)
  at y(metamask/common-7.js:1:72633)
  at ? (metamask/common-7.js:1:69260)
  at dispatch(metamask/common-7.js:1:70860)
  at ? (metamask/common-1.js:1:20981)
  at ? (metamask/common-1.js:1:1722)
  at Object.next(metamask/common-1.js:1:1827)
  at r(metamask/common-1.js:1:21050)
```

### Version

10.18.0

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
Fixed
