### ISSUE TITLE
[Bug]: Jsonrpc errors get burried inside error.message string

### ISSUE THREAD

**Issue by BelfordZ** [MetaMask/metamask-extension#15250]
## Problem

Errors returned from ethereum JSON-RPC api providers, when not expected by ethjs-query, are in a hard to use format.

Since using localhost, or using addEthereumNetwork opens the door to a wide variety of enpoints, we should do our best to return error messages.

Heres an example of a bad nonce error out users & developers will see:

```
{
  "id": 0,
  "error": {
    "code": -32603,
    "message": "[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"message\":\"VM Exception while processing transaction: invalid opcode\",\"code\":-32000,\"data\":{\"0x877c456d0b406f0706f405b0d2eb4e0ebc69629a539503e7ad94a7f9b6ba36af\":{\"error\":\"invalid opcode\",\"program_counter\":13,\"return\":\"0x\"},\"stack\":\"c: VM Exception while processing transaction: invalid opcode\\n    at Function.c.fromResults (/home/zb/code/masa/smart-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:4:192416)\\n    at w.processBlock (/home/zb/code/masa/smart-contracts/node_modules/ganache-cli/build/ganache-core.node.cli.js:42:50915)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\",\"name\":\"c\"}}}}'"
  }
}
```

## Solution

1. Fix the issue in the one place that people run into and complain about the most
  - Pros:
    - [already done](https://github.com/MetaMask/metamask-extension/pull/15205)
    - smallest possible scope of change
  - Cons:
    - leaves other places possibly also giving these bad errors
    - does little to address the actual problem, more of a bandaid.

1. Update ethjs-query to no longer wrap errors inside `result.value`, and handle unrecognized errors better by not stringifying the error.
  - Pros:
    - simple and fixes the issue in all places at once
  - Cons:
    - the project has not made a release in 4 years, and from comments on issues, is frozen.

1. 'Strangle' ethjs-query by making a wrapper for it, handling the errors as we want, and replacing all the calls to new EthjsQuery in extension.
  - Pros:
    - Dont need to unfreeze ethjs
    - Doesn't affect any other places that are using ethjs-query
    - keeps the difference between errors returned by different node impls contained
    - simple to implement
    - gives us a single place to change when/if we decide to replace ethjsquery
  - Cons:
    - Doesn't get rid of or improve the underlying lib being no longer supported
    - another layer of abstraction between api call -> result

1. Replace ethjs-query with [ethers](https://github.com/ethers-io/ethers.js) (which is what ethjs-query recommends using)
  - Pros:
    - externally maintained and widely used
  - Cons:
    - includes a lot more than we need
    - doenst give us the same thing - would require a lot of work to get it working
    - scope of change fairly significant

1. Replace ethjs-query with an openrpc [generated client](https://www.npmjs.com/package/@etclabscore/ethereum-json-rpc).
  - Pros:
    - Generated from an openrpc document which describes the 'base ethereum json rpc'.
    - uses client-js, so all the same features (batching and what not)
    - json schema validation on parameters makes us able to give standardized errors about bad params before hitting rpc endpoint
    - fully typed (also generates all the types involved in eth json rpc)
    - matches interface being used in ethjs-query
    - clearly communicates to client / test client developers what json-rpc api metamask is expecting of them.
  - Cons:
    - Using generated code isnt everyones cup of tea
    - scope of change fairly significant

## Proposed way forward

1. implement option 2 first.
1. use the strangled interface to impl client-js or generated client as a replacement

### Steps to reproduce

(this is just one way to make it happen, but it happens on infura endpoints when making contract calls with a gas setting thats too low)
1. start ganache or hardhat
2. switch metamask to localhost
3. go to test dapp, deploy failing contract, get the deployed contract address from devtools console
1. go to https://metamask.github.io/api-playground/api-documentation/
1. click try it now button on request permissions
1. click play
1. open metamask, copy your metamask addr 
1. click try it now on the sendTransaction method
1. use the testdapp failing contract address as the `to` address
2. use your address for "from"
3. use value "0x0"
4. click play
5. send transaction
6. observe error that is received

### Version

10.17.0

### Browser

Chrome

### Operating system

Linux

**Comment by shanejonas** [comment]
could also add

6. replace ethjs-query with client-js

**Comment by bschorchit** [comment]
@worldlyjohn was thinking about something similar so we also get more digested error messages on Mixpanel and can more easily work on addressing the underlying issues.

**Comment by kumavis** [comment]
im open to 1, 1b, 2, 5

**Comment by BelfordZ** [comment]
2 seems ideal. Will move forward with that
