### ISSUE TITLE
[Bug]: new BigNumber() not a number: [object Object]

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#15415]
### Describe the bug

Extension crashes when switching networks back and forth during the send flow

https://user-images.githubusercontent.com/53189696/182387612-4059d1c1-6518-4576-be7a-29efb6f2c393.mov

Error 1:
BigNumber Error: new BigNumber() not a number: [object Object]

Error 2:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'gas')

### Steps to reproduce

1. build v10.18.0 `yarn dist`
2. login the extension
3. switch to rinkeby test network
4. In the *background* console: set the Network throttling setting to `Slow 3G`
5. click the send button on the home page
6. fill in an address
7. enter an amount e.g. 0.00001
8. switch back and forth between rinkeby and ropsten test networks

### Error messages or log output

```shell
Error 1:

sentry-install.js:1 BigNumber Error: new BigNumber() not a number: [object Object]
  at ee (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:95509)
  at A (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:100989)
  at new $ (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:93411)
  at new $ (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:92842)
  at Object.dec (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:21036)
  at g (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:21620)
  at R (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:22164)
  at O (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:192391)
  at n.getRenderableEstimateDataForSmallButtonsFromGWEI (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:190090)
  at Function.mapToProps (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-8.js:1:72316)
  at r (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:198635)
  at h (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:197277)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:197349
  at e.d [as onStateChange] (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:191741)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204035
  at dl (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:88105)
  at Object.notify (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204004)
  at t.notifyNestedSubs (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203571)
  at e.d [as onStateChange] (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:191810)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204035
  at dl (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:88105)
  at Object.notify (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204004)
  at t.notifyNestedSubs (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203571)
  at e.d [as onStateChange] (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:191810)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204035
  at dl (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:88105)
  at Object.notify (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204004)
  at t.notifyNestedSubs (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203571)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at y (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:72695)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:69260
  at dispatch (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:70860)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:270025
  at Object.dispatch (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:69251)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-6.js:1:345509
  at a.<anonymous> (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:26:142673)
  at u (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:3:1144)
  at a.emit (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:3:1680)
  at l.handleResponse (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:26:143057)
  at l (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:210820)
  at s.emit (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:213815)
  at w (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:41385)
  at v (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:41200)
  at b.push (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:42014)
  at t.exports._write (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-6.js:8:435312)
  at b (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:54430)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:57614
(anonymous) @ sentry-install.js:1
mu @ ui-3.js:1
Pu.n.payload @ ui-3.js:1
xi @ ui-3.js:1
Ti @ ui-3.js:1
Ja @ ui-3.js:1
Cu @ ui-3.js:1
xl @ ui-3.js:1
gl @ ui-3.js:1
fl @ ui-3.js:1
(anonymous) @ ui-3.js:1
n.unstable_runWithPriority @ ui-3.js:26
Ko @ ui-3.js:1
Zo @ ui-3.js:1
Jo @ ui-3.js:1
dl @ ui-3.js:1
notify @ ui-3.js:1
t.notifyNestedSubs @ ui-3.js:1
t.handleChangeWrapper @ ui-3.js:1
y @ common-7.js:1
(anonymous) @ common-7.js:1
dispatch @ common-7.js:1
(anonymous) @ common-8.js:1
(anonymous) @ common-7.js:1
(anonymous) @ ui-6.js:1
(anonymous) @ ui-3.js:26
u @ common-7.js:3
a.emit @ common-7.js:3
handleResponse @ ui-3.js:26
l @ common-1.js:20
s.emit @ common-1.js:20
w @ common-7.js:1
v @ common-7.js:1
b.push @ common-7.js:1
_write @ common-6.js:8
b @ common-7.js:1
(anonymous) @ common-7.js:1
y.write @ common-7.js:1
m @ common-7.js:1
l @ common-1.js:20
s.emit @ common-1.js:20
w @ common-7.js:1
v @ common-7.js:1
b.push @ common-7.js:1
_onMessage @ common-3.js:10
(anonymous) @ common-3.js:10
Show 16 more frames
sentry-install.js:1 BigNumber Error: new BigNumber() not a number: [object Object]
  at ee (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:95509)
  at A (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:100989)
  at new $ (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:93411)
  at new $ (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:92842)
  at Object.dec (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:21036)
  at g (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:21620)
  at R (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:22164)
  at O (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:192391)
  at n.getRenderableEstimateDataForSmallButtonsFromGWEI (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:190090)
  at Function.mapToProps (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-8.js:1:72316)
  at r (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:198635)
  at h (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:197277)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:197349
  at e.d [as onStateChange] (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:191741)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204035
  at dl (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:88105)
  at Object.notify (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204004)
  at t.notifyNestedSubs (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203571)
  at e.d [as onStateChange] (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:191810)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204035
  at dl (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:88105)
  at Object.notify (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204004)
  at t.notifyNestedSubs (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203571)
  at e.d [as onStateChange] (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:191810)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204035
  at dl (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:88105)
  at Object.notify (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:204004)
  at t.notifyNestedSubs (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203571)
  at t.handleChangeWrapper (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:1:203639)
  at y (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:72695)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:69260
  at dispatch (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:70860)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-8.js:1:270025
  at Object.dispatch (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:69251)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-6.js:1:345509
  at a.<anonymous> (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:26:142673)
  at u (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:3:1144)
  at a.emit (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:3:1680)
  at l.handleResponse (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/ui-3.js:26:143057)
  at l (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:210820)
  at s.emit (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-1.js:20:213815)
  at w (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:41385)
  at v (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:41200)
  at b.push (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:42014)
  at t.exports._write (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-6.js:8:435312)
  at b (chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:54430)
  at chrome-extension://noifopoklcadhlkenlkefaikmclmlild/common-7.js:1:57614


Error 2:

common-8.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'gas')
  at common-8.js:1:94768
  at common-1.js:1:13536
  at produce (common-5.js:3:34153)
  at common-1.js:1:13513
  at Array.reduce (<anonymous>)
  at common-1.js:1:13382
  at common-7.js:1:71714
  at y (common-7.js:1:72633)
  at common-7.js:1:69260
  at dispatch (common-7.js:1:70860)
  at common-1.js:1:20981
  at common-1.js:1:1722
  at Object.next (common-1.js:1:1827)
  at r (common-1.js:1:21050)
```

### Version

10.18.0

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by seaona** [comment]
Looks might be related to https://github.com/MetaMask/metamask-extension/issues/14794 @PeterYinusa

**Comment by Pwoseidon** [comment]
I have the same issue but can't figure out how to get back into my main net wallet :(
Can someone please explain how I can fix this issue?

Thank you



`Message: new BigNumber() not a number: undefined

Code: BigNumber Error

Stack:
BigNumber Error: new BigNumber() not a number: undefined
  at ee (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:95509)
  at A (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:100989)
  at new $ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:20:93411)
  at n.calcTokenAmount (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-8.js:1:135233)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:325171
  at Object.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:64058)
  at r.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:1:35852)
  at r.useTokenDisplayValue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:325083)
  at r.useTransactionDisplayData (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:335009)
  at A (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:357363)
  at ha (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:59891)
  at Cu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:104649)
  at xl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90565)
  at gl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90490)
  at fl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:87838)
  at al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:84606)
  at Gl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:112210)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:113409
  at pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88186)
  at es (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:113394)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:115311)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:345761`


<img width="351" alt="Screen Shot 2022-08-16 at 10 02 20 pm" src="https://user-images.githubusercontent.com/84986106/184984570-00743587-55a9-44ce-acc9-4c741caaf7a7.png">

**Comment by agrohs** [comment]
Why is this issue closed!??!

**Comment by adonesky1** [comment]
@Pwoseidon did this issue occur in the send flow for you? Can you tell us the version of Metamask that you were using as well as the browser?

**Comment by amitOodles** [comment]
@adonesky1 i am facing the above issue on one of my contracts. I have the following function in my contract

    `
    function safeTransferFrom(address from, address to, uint256 tokenId) public {
        safeTransferFrom(from, to, tokenId, "");
    } 
    function safeTransferFrom(address from, address to, uint256 tokenId, bytes memory _data) public {
        transferFrom(from, to, tokenId);
        require(_checkOnERC721Received(from, to, tokenId, _data), "ERC721: transfer to non ERC721Receiver implementer");
    }

    function _checkOnERC721Received(address from, address to, uint256 tokenId, bytes memory _data)
        internal returns (bool)
    {
        if (!to.isContract()) {
            return true;
        }

        bytes4 retval = IERC721Receiver(to).onERC721Received(msg.sender, from, tokenId, _data);
        return (retval == _ERC721_RECEIVED);
    }

    function transferFrom(address from, address to, uint256 tokenId) public {
        //solhint-disable-next-line max-line-length
        require(_isApprovedOrOwner(msg.sender, tokenId), "ERC721: transfer caller is not owner nor approved");

        _transferFrom(from, to, tokenId);
    }`

The issue is that when i am calling the transferFrom function directly metamask allows me to send a transaction, but when i am using safeTransferFrom function (any of the overloaded version), i get the following error in metamask (related to BigNumber) and it keeps on loading.

**My Metamask version is 10.18.4
Browser is Firefox bv 104.0**

![Screenshot from 2022-09-24 16-51-15](https://user-images.githubusercontent.com/20085459/192095153-51d6edfd-1e93-478a-981d-82fdfa2effc7.png)
