### ISSUE TITLE
[Bug]: Metamask throws error and make dApps impossible to use

### ISSUE THREAD

**Issue by alvinsartor** [MetaMask/metamask-extension#15479]
### Describe the bug

Metamask (inpage.js) is throwing an error making it impossible to use dApps:

![image](https://user-images.githubusercontent.com/21270278/183049430-e5315bd4-873a-45eb-8355-8e918893e366.png)
![image](https://user-images.githubusercontent.com/21270278/183049555-1f200a5e-8133-4693-8736-1f22558ba6c8.png)

### Steps to reproduce

1. Connect Metamask to a dApp (https://app.daemons.fi / https://app.aave.com / https://app.sushi.com)
2. Reload page

### Error messages or log output

```shell
Uncaught (in promise) TypeError: Cannot assign to read only property 'chainId' of object '#<l>'
    at l._handleChainChanged (inpage.js:1:39117)
    at l._handleChainChanged (inpage.js:1:46662)
    at l._handleChainChanged (inpage.js:1:44260)
    at l._initializeState (inpage.js:1:37927)
    at l._initializeStateAsync (inpage.js:1:46258)
inpage.js:1 Uncaught (in promise) TypeError: Cannot assign to read only property 'selectedAddress' of object '#<l>'
    at l._handleAccountsChanged (inpage.js:1:39788)
    at r (inpage.js:1:38276)
    at o._handle (inpage.js:17:2422)
2inpage.js:1 Uncaught TypeError: Cannot assign to read only property 'chainId' of object '#<l>'
    at l._handleChainChanged (inpage.js:1:39117)
    at l._handleChainChanged (inpage.js:1:46662)
    at l._handleChainChanged (inpage.js:1:44260)
    at s.<anonymous> (inpage.js:1:45866)
    at i (inpage.js:1:56067)
    at s.emit (inpage.js:1:56607)
    at inpage.js:1:55131
    at d.write [as _write] (inpage.js:1:55154)
    at w (inpage.js:17:29867)
    at inpage.js:17:33045
```

### Version

10.18

### Browser

Brave

### Operating system

Windows

**Comment by ChristopherTrimboli** [comment]
Can confirm this is effecting me too. 
I think it is Brave Browser specific. Edge works fine for me.

**Comment by brad-decker** [comment]
@ChristopherTrimboli are you also on windows?

**Comment by pokoynik** [comment]
Same for me, starting today, Brave browser, windows.

**Comment by brad-decker** [comment]
Hey everyone @alvinsartor @pokoynik @ChristopherTrimboli -- there is another issue #15460 for the same issue. This thread confirms that this is a Brave specific bug and there is a fix in the works. Please use that thread for further communication on this issue.
