### ISSUE TITLE
[Bug]: Metamask fails to load if no response from RPC

### ISSUE THREAD

**Issue by JABirchall** [MetaMask/metamask-extension#15629]
### Describe the bug

Metamask extention doesnt load, console errors log no response from RPC. 

### Steps to reproduce

I dunno

### Error messages or log output

```shell
Setting up Sentry Remote Error Reporting for 'production': SENTRY_DSN sentry-install.js:1:1041
Removing intrinsics.Object.hasOwn sentry-install.js:1:102934
Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). moz-extension:9430:29
Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). moz-extension:4421:4
undefined sentry-install.js:1:102934
    h moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/sentry-install.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    default moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-6.js:1
    send moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-3.js:26
    a moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/sentry-install.js:1
    (Async: setTimeout handler)
    a moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/sentry-install.js:1
    newValue moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:10535
    send moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-3.js:26
    get moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-3.js:26
    default moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-6.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    <anonymous> moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    <anonymous> moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    internalRequire moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:10966
    runModule moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:11357
    entryExports moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:11347
    loadBundle moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:11346
    <anonymous> moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
Uncaught (in promise) Error: No response from RPC
runtime-lavamoat.js:8939:17
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    InterpretGeneratorResume self-hosted:1458
    AsyncFunctionNext self-hosted:668
    (Async: async)
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    default moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-6.js:1
    send moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-3.js:26
    a moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/sentry-install.js:1
    (Async: setTimeout handler)
    a moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/sentry-install.js:1
    apply self-hosted:2705
    newValue moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:10535
    send moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-3.js:26
    get moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-3.js:26
    default moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-6.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    g moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    <anonymous> moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    AsyncFunctionNext self-hosted:668
    (Async: async)
    <anonymous> moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1
    internalRequire moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:10966
    runModule moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:11357
    entryExports moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:11347
    map self-hosted:180
    loadBundle moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/runtime-lavamoat.js:11346
    <anonymous> moz-extension://e6834f0f-3a74-4f6a-ad7f-cf3a09d748b9/ui-9.js:1

​
```

### Version

10.18.3

### Browser

Firefox

### Operating system

Windows

### Additional context

I shouldn't be effectivly locked out of my wallet if the RPC is down, I can't even change the RPC now.

**Comment by JABirchall** [comment]
Screenshot for context

![](https://i.imgur.com/4uMGm2q.png)

**Comment by JABirchall** [comment]
Ive had to completly remove metamask and reinstall it again to be able to change RPC.

The and orginal RPC wasnt even down, it was working fine. dont know why metamask giving error the rpc was not responding.

**Comment by bschorchit** [comment]
Possibly related to https://github.com/MetaMask/metamask-extension/issues/9196

**Comment by cinjon** [comment]
I'm running into this as well when testing with wdio. Sometimes it will work, most of the time I get the following:

<img width="1192" alt="Screen Shot 2022-08-27 at 2 18 53 PM" src="https://user-images.githubusercontent.com/615351/187032023-cec114fa-4b43-4031-9474-273300dfc285.png">
.

**Comment by cinjon** [comment]
What is metamask using to do automated web integration tests? I have a reasonably small wdio setup that fails ~80% of the time due to this issue.

**Comment by cinjon** [comment]
@JABirchall Any chance you figured this out?

**Comment by iteyelmp** [comment]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/6647261/226299377-48d76407-f97e-40eb-b33a-9d43762008f6.png">
Is there any solution to this problem? I get this error when I execute transactions synchronously in batches. After an error occurs, shutting down and restarting, and closing the browser will not work. You can only uninstall and reinstall.

**Comment by iteyelmp** [comment]
10 batch tasks are bound to trigger the error.

**Comment by JABirchall** [comment]
> @JABirchall Any chance you figured this out?

Nope, uninstalling and reinstalling metamask fixed the issue. So maybe its a longeverty thing. Something (logs, data, vault, transcation, etc) gets too big and metamask cant load because of it.

**Comment by iteyelmp** [comment]
OK, thanks. But the wallet of the dapp user cannot be deleted. So I don't know how to fix this problem.

**Comment by hongda3141** [comment]
same story in my linux :
![Screenshot from 2023-03-27 07-17-53](https://user-images.githubusercontent.com/25719952/227811854-662ac997-b1a9-4cfe-b040-c1cd4b0c3bf9.png)
and log:
![Screenshot from 2023-03-27 07-29-45](https://user-images.githubusercontent.com/25719952/227811872-089aaea0-285e-4021-b4af-221833864c77.png)

every time I must restart, it will work, but I have some auto login code that must success for not restart, how to fix this "had trouble starting" error?

**Comment by smichea** [comment]
same pb here on win11 , the extension never loads and definitely cannot uninstall

**Comment by JABirchall** [comment]
Yea, i suppose this is a big issue for some people since they havnt backed up their seed and cant just uninstall/reinstall to fix the problem.

**Comment by smichea** [comment]
I have the password and private key but [this procedure](https://support.metamask.io/hc/en-us/articles/360018766351) doesnt help to recover the seed. because of the failure to load when you try 
the command
```
chrome.storage.local.get('data', result => {
 var vault = result.data.KeyringController.vault
 console.log(vault)
})
```
you get 
```
Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
``

**Comment by linuxh3lper** [comment]
> I have the password and private key but [this procedure](https://support.metamask.io/hc/en-us/articles/360018766351) doesnt help to recover the seed. because of the failure to load when you try the command
> 
> ```
> chrome.storage.local.get('data', result => {
>  var vault = result.data.KeyringController.vault
>  console.log(vault)
> })
> ```
> 
> you get
> 
> ```
> Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
> ``
> ```

Hi [smichea](https://github.com/smichea), when you use firefox... see this guide:
https://community.metamask.io/t/metamask-blank-screen-on-firefox-but-no-seed/12971/32

**Comment by noxonsu** [comment]
same problem

```
ui-10.js:26 Error: No response from RPC
  at ui-10.js:1:228215
  at e.<computed> (sentry-install.js:1:682)
  at s (sentry-install.js:1:13706)
_ @ ui-10.js:26
runtime-lavamoat.js:7100 SES_UNHANDLED_REJECTION: Error: No response from RPC
  at ui-10.js:1:228215
  at e.<computed> (sentry-install.js:1:682)
  at s (sentry-install.js:1:13706)
handleRejection @ runtime-lavamoat.js:7100
finalizeDroppedPromise @ runtime-lavamoat.js:6928
```

**Comment by rodrigoaguilera** [comment]
I have been affected by this bug. What worked for me is inspecting the sqlite db for the id column in the `file` table then decreasing the fnumber in the filename accordingly. A firefox restart and metamask is working again
As described here
https://github.com/MetaMask/metamask-extension/issues/9196

**Comment by JABirchall** [comment]
> I have been affected by this bug. What worked for me is inspecting the sqlite db for the id column in the `file` table then decreasing the fnumber in the filename accordingly. A firefox restart and metamask is working again As described here #9196

Thats a different issue.

**Comment by lebed2045** [comment]
same issue,
<img width="1168" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/1270800/7edf706d-d8cc-433b-847d-86d16e822cf5">

**Comment by nisdas** [comment]
Is there any update on this, or recovery steps that we can do to get metamask working again ? I really want to avoid removing/reinstalling the extension here

**Comment by JackBekket** [comment]
> I have the password and private key but [this procedure](https://support.metamask.io/hc/en-us/articles/360018766351) doesnt help to recover the seed. because of the failure to load when you try the command
> 
> ```
> chrome.storage.local.get('data', result => {
>  var vault = result.data.KeyringController.vault
>  console.log(vault)
> })
> ```
> 
> you get
> 
> ```
> Uncaught Error: LavaMoat - property "chrome" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
> ``
> ```

Same problem

So how can I get access to vault if I don't want to reinstall metamask?

**Comment by JABirchall** [comment]
@DDDDDanica seems this is still a persistant issue affecting more users. 

Any timeline for when this is going to be looked at?

**Comment by gauthierpetetin** [comment]
Lowering this to a sev2 as we're not handling it as a sev1 at the moment, but we shall work on it at the beginning of Q4.

**Comment by JABirchall** [comment]
> This issue has been automatically marked as stale because it has not had recent activity in the last 90 days. It will be closed in 45 days if there is no further activity. The MetaMask team intends on reviewing this issue before close, and removing the stale label if it is still a bug. We welcome new comments on this issue. We do not intend on closing issues if they report bugs that are still reproducible. Thank you for your contributions.

There is no way metamask is getting away with this bug going ignored!

**Comment by Astrit11** [comment]
I started getting this issue as well and there is no way to escape this issue I will have to uninstall and install it again but that should not be the case since I don't know seed phrase,did anyone succeeded to resolve without uninstall/install? 

Btw created a new issue here:
https://github.com/MetaMask/metamask-extension/issues/22355

**Comment by yaerna1984** [comment]
Does it at least load when there is a response from RPC? Mine keeps spinning.

**Comment by 09306677806** [comment]
#فعالیت دارم و زنده ام منتها منو نادیده گرفتین لطفا منو ازین حالت بیرون
بیارین شهرزاد ماهرو*#

در تاریخ یکشنبه ۷ ژوئیه ۲۰۲۴،‏ ۱۹:۳۴ github-actions[bot] <
***@***.***> نوشت:

**Comment by 09306677806** [comment]
#هرچی هکر هر روز به من نفوذ میکنه بس کنید خجالت بکشید دیگه*

در تاریخ یکشنبه ۷ ژوئیه ۲۰۲۴،‏ ۲۰:۳۵ Shahrzad Mahro <
***@***.***> نوشت:

**Comment by OMGart** [comment]
same in 12.13.1

**Comment by 0x000hx** [comment]
so basically if you have many transaction accepted, then it somehow bugs out and you got no choice but to reinstall with your data wiped?

**Comment by OMGart** [comment]
> so basically if you have many transaction accepted, then it somehow bugs out and you got no choice but to reinstall with your data wiped?

let me suggest you a simpler solution, if you have made too many transfers, immediately -> Settings -> Advanced -> Clear activity tab data.
reinstalling it is not a solution for me.

**Comment by 0x000hx** [comment]
> > so basically if you have many transaction accepted, then it somehow bugs out and you got no choice but to reinstall with your data wiped?
> 
> let me suggest you a simpler solution, if you have made too many transfers, immediately -> Settings -> Advanced -> Clear activity tab data. reinstalling it is not a solution for me.

well, for me as well. ive been developing an app and had to accept many transaction requests, now i get this:

![Image](https://github.com/user-attachments/assets/e5a45d0a-47bd-4468-b72e-c95ffb83992f)

**Comment by OMGart** [comment]
The RPC server cannot fulfill the request you sent. Whatever you are doing, break it down into parts and clear the tx data history as I described above.

**Comment by 0x000hx** [comment]
> The RPC server cannot fulfill the request you sent. Whatever you are doing, break it down into parts and clear the tx data history as I described above.

yeah how do I do that with blank metamask window? I am going to try to change the default network and rpc url and see if that changes the behavior. gonna need to work with the db in the extension storage I assume

**Comment by JABirchall** [comment]
I already abandoned metamask after i got this a second time a few years ago.

Everyone should switch to https://github.com/floating/frame its much more secure than metamask, better gas calculations, hot, cold and hardware wallet support. etc etc.

Its overall a better wallet. 

Stop using metamask.

**Comment by mqklin** [comment]
My MetaMask endless loading right now. 60+ accounts there. What should I do?

**Comment by OMGart** [comment]
we [orange:❤️] 🦊

**Comment by mqklin** [comment]
@0x000hx do you have an idea on how to switch Network in MM without logging in first?

**Comment by momodaka** [comment]
I met same issue , how to switch network

**Comment by epop-cs** [comment]
@JABirchall,

Sorry for the lack of updates on your issue.
Since the last comment, we've released a few more versions, and I'd like to know if you're still able to reproduce it.
If it does, please be so kind and share with us: a screen recording of all your actions, along with the console logs from the reproduction. Having this information will help our team advance with the investigation.
Can you please let us know?
