### ISSUE TITLE
[non-blocking BUG]: Failed to parse transaction data (TransactionController#addUnapprovedTransaction)

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#15775]
### Describe the bug

Caught error parsing transaction data for both home.html and popup.html when sending a transaction using both the MV2 and MV3 builds. 

This does not break user flow. App continues to work as expected with this since we catch the error

```
Failed to parse transaction data. TypeError: Cannot destructure property 'name' of '(data && parseStandardTokenTransactionData(...))' as it is undefined.
  at determineTransactionType (transaction.utils.js:149:8)
  at TransactionController.addUnapprovedTransaction (index.js:765:45)
  at async TransactionController.newUnapprovedTransaction (index.js:324:27)
  at async MetamaskController.newUnapprovedTransaction (metamask-controller.js:2521:12)
  at async sendTransaction (wallet.js:66:1)
  at async createAsyncMiddleware.js:46:1 undefined
```

**Notice, txParams does not have `data` in this screenshot (popup.html):** 
<img width="1241" alt="Screenshot 2022-09-08 at 11 38 45 PM" src="https://user-images.githubusercontent.com/20778143/189287173-f98fb8f3-06af-4b14-be69-e9a35ea4b75c.png">

**home.html screenshot 1:**
<img width="1641" alt="Screenshot 2022-09-08 at 11 29 33 PM" src="https://user-images.githubusercontent.com/20778143/189286843-02bf4c2c-aaf3-4903-9aeb-a20d0b899584.png">

**home.html screenshot 2:**
<img width="1644" alt="Screenshot 2022-09-08 at 11 35 36 PM" src="https://user-images.githubusercontent.com/20778143/189286846-16452dfe-ceb5-47fb-b215-b6e70c2bda73.png">

### Steps to reproduce

1. Deploy a Contract or Send a Transaction with either the popup.html or home.html pages
2. Observe devtools console (For MV2, observe the console for background.js)

### Version

10.18.4

### Browser

Chrome

### Operating system

MacOS

**Comment by digiwand** [comment]
Thought this could be related to MV3, turns out this is also an MV2 issue. To repro, observe the background.js console while sending a transaction
