### ISSUE TITLE
[Bug]: [MV3] Cannot destructure balance after terminating service worker

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#16314]
### Describe the bug

**Problem**: when I terminate the service worker after sending  a transaction, I land on the MM error page and see `Cannot destructure balance` error. This is an intermittent failure, but it appears quite commonly (+3 times for ~10 tries)

![cannot-destructure-balance](https://user-images.githubusercontent.com/54408225/198878355-57726127-43bb-4b7c-829b-d091be72e30f.png)

### Steps to reproduce

This is tested over [this PR](https://github.com/MetaMask/metamask-extension/pull/15558)
1. Unlock MM
2. Change to a testnet
3. Perform a Send tx
4. Terminate Service worker -- occasionally, you will be landed to the error page

### Version

https://github.com/MetaMask/metamask-extension/pull/15558

### Browser

Chrome

### Operating system

Linux

**Comment by segun** [comment]
I tried to replicate this, but I couldn't, instead of this error, I'm getting another error that is similar

```
https://github.com/MetaMask/metamask-extension/blob/develop/ui/hooks/useGasFeeErrors.js#L285

Uncaught TypeError: Cannot read properties of undefined (reading 'balance')
The error may be correlated with this previous error:
TypeError: Cannot read properties of undefined (reading 'balance')
  at Object.isBalanceCached [as current] (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/common-9.js:3029:85)
  at Subscription.checkForUpdates [as onStateChange] (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:33878:47)
  at Subscription.handleChangeWrapper (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:34199:12)
  at chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:34125:20
  at batchedUpdates$1 (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:24393:12)
  at Object.notify (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:34121:7)
  at Subscription.notifyNestedSubs (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:34194:20)
  at captureWrapperProps (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:32881:5)
  at chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:32869:23
  at commitHookEffectList (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:22037:26)


  at isBalanceCached (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/common-9.js:3029:85)
  at useSelectorWithStoreAndSubscription (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:33858:23)
  at useSelector (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:33934:12)
  at EthOverview (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-6.js:17496:55)
  at renderWithHooks (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:16267:18)
  at updateFunctionComponent (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:18354:20)
  at beginWork$1 (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:20183:16)
  at HTMLUnknownElement.callCallback (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:343:14)
  at Object.invokeGuardedCallbackDev (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:392:16)
  at invokeGuardedCallback (chrome-extension://pfnkndiibjpendhnikmjbegomajogkom/ui-4.js:447:31)
isBalanceCached @ selectors.js:347
useSelectorWithStoreAndSubscription @ useSelector.js:39
useSelector @ useSelector.js:115
EthOverview @ eth-overview.js:48
renderWithHooks @ react-dom.development.js:16260
updateFunctionComponent @ react-dom.development.js:18347
beginWork$1 @ react-dom.development.js:20176
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
beginWork$$1 @ react-dom.development.js:25780
performUnitOfWork @ react-dom.development.js:24695
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
batchedUpdates$1 @ react-dom.development.js:24392
notify @ Subscription.js:25
notifyNestedSubs @ Subscription.js:98
handleChangeWrapper @ Subscription.js:103
dispatch @ redux.js:305
dispatch @ instrument.ts:901
(anonymous) @ index.js:14
dispatch @ redux.js:667
(anonymous) @ actions.js:1433
(anonymous) @ index.js:11
dispatch @ devTools.js:333
(anonymous) @ index.js:43
(anonymous) @ metaRPCClientFactory.js:40
safeApply @ index.js:70
SafeEventEmitter.emit @ index.js:56
handleResponse @ metaRPCClientFactory.js:75
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_write @ index.js:68
doWrite @ _stream_writable.js:428
writeOrBuffer @ _stream_writable.js:417
Writable.write @ _stream_writable.js:334
ondata @ _stream_readable.js:619
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_onMessage @ index.js:26
(anonymous) @ index.js:11
backend.js:12979 The above error occurred in the <EthOverview> component:
    in EthOverview (created by Home)
    in div (created by Home)
    in div (created by Home)
    in div (created by Home)
    in div (created by Home)
    in Home (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Home)) (created by Context.Consumer)
    in Route (created by Authenticated)
    in Authenticated (created by ConnectFunction)
    in ConnectFunction (created by Routes)
    in Switch (created by Routes)
    in div (created by Routes)
    in div (created by Routes)
    in Routes (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Routes)) (created by Index)
    in LegacyI18nProvider (created by Index)
    in I18nProvider (created by Index)
    in LegacyMetaMetricsProvider (created by Index)
    in MetaMetricsProvider (created by Index)
    in Router (created by HashRouter)
    in HashRouter (created by Index)
    in Provider (created by Index)
    in Index

React will try to recreate this component tree from scratch using the error boundary you provided, Index.
overrideMethod @ backend.js:12979
logCapturedError @ react-dom.development.js:21843
logError @ react-dom.development.js:21880
update.payload @ react-dom.development.js:23247
getStateFromUpdate @ react-dom.development.js:13644
processUpdateQueue @ react-dom.development.js:13767
updateClassInstance @ react-dom.development.js:14521
updateClassComponent @ react-dom.development.js:18420
beginWork$1 @ react-dom.development.js:20186
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24695
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
batchedUpdates$1 @ react-dom.development.js:24392
notify @ Subscription.js:25
notifyNestedSubs @ Subscription.js:98
handleChangeWrapper @ Subscription.js:103
dispatch @ redux.js:305
dispatch @ instrument.ts:901
(anonymous) @ index.js:14
dispatch @ redux.js:667
(anonymous) @ actions.js:1433
(anonymous) @ index.js:11
dispatch @ devTools.js:333
(anonymous) @ index.js:43
(anonymous) @ metaRPCClientFactory.js:40
safeApply @ index.js:70
SafeEventEmitter.emit @ index.js:56
handleResponse @ metaRPCClientFactory.js:75
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_write @ index.js:68
doWrite @ _stream_writable.js:428
writeOrBuffer @ _stream_writable.js:417
Writable.write @ _stream_writable.js:334
ondata @ _stream_readable.js:619
emitOne @ events.js:106
emit @ events.js:184
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_onMessage @ index.js:26
(anonymous) @ index.js:11
backend.js:15929 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools @ backend.js:15929
(anonymous) @ backend.js:15911
backend.js:15929 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools @ backend.js:15929
(anonymous) @ backend.js:15911
backend.js:15929 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools @ backend.js:15929
(anonymous) @ backend.js:15911
backend.js:15929 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools @ backend.js:15929
(anonymous) @ backend.js:15911
backend.js:15929 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools @ backend.js:15929
(anonymous) @ backend.js:15911
backend.js:15929 WebSocket connection to 'ws://localhost:8097/' failed: 
connectToDevTools @ backend.js:15929
(anonymous) @ backend.js:15911
sctransport.js:10 WebSocket connection to 'ws://localhost:8000/socketcluster/' failed: 
```

**Comment by jpuri** [comment]
The PR fixes it: https://github.com/MetaMask/metamask-extension/pull/16393
