### ISSUE TITLE
[Bug]: mm extension crashes upon clicking the buy eth call to action on the transaction confirmation screen

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#16418]
### Describe the bug

mm extension crashes upon clicking the buy eth call to action on the transaction confirmation screen

https://user-images.githubusercontent.com/53189696/200575926-4317341c-c8e7-4cd3-85cf-19675f7bf2f3.mov

### Steps to reproduce

1. login to mm
2. switch network to ethereum mainnet
3. switch accounts to an account with 0 eth
4. navigate to https://etherscan.io/address/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d#writeContract
5. connect your wallet, click `connect to web3`
6. in section 9 setapprovalforall, enter your wallet address in the operator field and true in the approved field
7. click `Write`
8. Click `Buy Eth`

### Error messages or log output

```shell
Message: Cannot destructure property 'contents' of 'e' as it is undefined.

Code: TypeError

Stack:
TypeError: Cannot destructure property 'contents' of 'e' as it is undefined.
  at j.render (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-5.js:1:167525)
  at Za (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:71258)
  at Ja (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:71053)
  at Cu (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:105916)
  at El (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:90577)
  at gl (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:90502)
  at fl (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:87850)
  at chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:46308
  at n.unstable_runWithPriority (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:26:82287)
  at Ko (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:46017)
  at Zo (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:46253)
  at Jo (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:46188)
  at ue (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:114703)
  at _n (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/ui-3.js:1:29663)
  at HTMLDocument.a (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/sentry-install.js:1:11376)
```

### Version

10.22.0

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by dragana8** [comment]
@PeterYinusa This will be fixed with this PR: https://github.com/MetaMask/metamask-extension/pull/16220

**Comment by seaona** [comment]
QAd, issue is fixed now
