### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'length') Metamask Flask

### ISSUE THREAD

**Issue by CocDap** [MetaMask/metamask-extension#17059]
### Describe the bug

Having issue when connecting with WSS provider in Snap

### Steps to reproduce

1. I am following this open-source: `https://github.com/ChainSafe/metamask-snap-polkadot`

2. `yarn install`-> `yarn run demo` : Successfully
3.  Snap is installed -> Accept permissions  -> Websocket error 
<img width="335" alt="image" src="https://user-images.githubusercontent.com/48429826/209302829-8a1ec40d-48d2-4e7d-9c7b-c8ccc1228a20.png">
 

### Error messages or log output

```shell
metamask.github.io/iframe-execution-environment/0.9.1/lockdown.umd.min.js:1 TypeError: Cannot read properties of undefined (reading 'length')
  at p.value (eval at <anonymous> (eval at <anonymous> (metamask.github.io/iframe-execution-environment/0.9.1/lockdown.umd.min.js:1:19217)), <anonymous>:14170:105)
  at WebSocket.<anonymous> (metamask.github.io/iframe-execution-environment/0.9.1/bundle.js:2:717975)
```
```


### Version

10.22.2-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

**Comment by CocDap** [comment]
@FrederikBolding It's working on Flask version `10.23.2`. Thanks 

Btw, It is working when I changed `wss` to `https` configuration on Flask version `10.22.2`.
