### ISSUE TITLE
[Bug]: snaps: use `mcl-wasm` inside a snap.

### ISSUE THREAD

**Issue by firnprotocol** [MetaMask/metamask-extension#17064]
### Describe the bug

I am trying to build a snap which uses @herumi's incredible [`mcl-wasm`](https://github.com/herumi/mcl-wasm) library inside of it.

right now I get the error:
```javascript
{ code: -32603, message: 'scriptDirectory.indexOf is not a function' }
```

in my own repo (not MWE), i also get:
```javascript
{ code: -32603, message: 'job: "QJzV3WHYNMUl-Igr-dgpi" has no mapped snap.' }
```
where the job identifier is a random alphanumeric string.

perhaps this has something to do with the fact that `mcl-wasm` uses WASM? thanks in advance.

### Steps to reproduce

an MWE is given in the repository [`firnprotocol/snap-mcl-wasm-mwe`](https://github.com/firnprotocol/snap-mcl-wasm-mwe). this repo differs from [`MetaMask/template-snap-monorepo`](https://github.com/MetaMask/template-snap-monorepo) by [a minimal code change](https://github.com/firnprotocol/snap-mcl-wasm-mwe/commit/d4ec8459a86b553768418587d984740c075dff19) of about 3 lines. to reproduce:
1. clone [my MWE](https://github.com/firnprotocol/snap-mcl-wasm-mwe)
2. run `yarn start`
3. navigate to `localhost:8000` in a browser tab with Flask enabled (i needed to use a separate chrome profile from the one with regular metamask).
4. click "connect" and "send message".

### Error messages or log output

```shell
{ code: -32603, message: 'scriptDirectory.indexOf is not a function' }

in my main repo (not MWE), it's different: during build i get

➤ YN0000: [snap]: SES_UNHANDLED_REJECTION: [TypeError <Object <Object <[Object: null prototype] {}>>>: scriptDirectory.indexOf is not a function
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53750:37)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53598:29)
➤ YN0000: [snap]:   at Generator.next (<anonymous>)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53381:73)
➤ YN0000: [snap]:   at new Promise (<anonymous>)
➤ YN0000: [snap]:   at __awaiter (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53360:16)
➤ YN0000: [snap]:   at Object.initializeMcl (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:53597:74)
➤ YN0000: [snap]:   at 324.ethers (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:59973:27)
➤ YN0000: [snap]:   at o (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:38:19)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluateFactory (/Users/firnprotocol/snap/node_modules/ses/dist/ses.cjs:1427:10)), <anonymous>:40:20)]
➤ YN0000: [snap]: Eval Success: evaluated 'dist/bundle.js' in SES!
```

### Version

10.22.2-flask.0

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

**Comment by firnprotocol** [comment]
actually, i wonder if the root cause is whether `mcl-wasm` can run inside [SES](https://www.npmjs.com/package/ses). cc. @herumi. huge thanks for your attention in advance.

**Comment by firnprotocol** [comment]
moving to https://github.com/herumi/mcl-wasm/issues/28.
