### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'preventDefault')

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#17439]
https://metamask.sentry.io/issues/3894018406/?referrer=github_plugin

```
TypeError: Cannot read properties of undefined (reading 'preventDefault')
  at handleCreate (ui/pages/onboarding-flow/create-password/create-password.js:145:11)
  at buttonProps.onKeyUp (ui/components/ui/button/button.component.js:49:21)
...
(14 additional frame(s) were not displayed)
```

**Comment by PeterYinusa** [comment]
Steps to repro:
- Open the extension for the first time
- Click `Create a new wallet`
- Click `I agree`
- Enter a password
- Repeat password in Confirm Password field
- Press the `Tab` key on your keyboard, until you reach the `Create new wallet` button
- Press the `Enter` key on your keyboard

https://user-images.githubusercontent.com/53189696/214936347-2d8a4179-e407-4340-adbe-826e9431baff.mov
