### ISSUE TITLE
[Bug]: NFT dropdown for owned and previously owned NFTs displays/hiddens NFTs after some seconds

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#17848]
### Describe the bug

**Problem**: when I click on the NFT dropdown for owned or previously owned NFTs I can see how the display/hide is switched after some seconds

https://user-images.githubusercontent.com/54408225/220414648-eb4c8078-9915-4ddd-aaac-3991b24f3bd6.mp4

### Steps to reproduce

1. Enable NFT build
2. Go to Test Dapp
3. Connect MM
4. Deploy Collectibles
5. Mint Collectibles
6. Import NFTs
7. Click dropdown for hiding currently owned NFTs -- after some seconds the NFTs are displayed again
8. Transfer one collectible
9. Click dropwdown for showing previously owned NFTs -- after some seconds the NFTs are hidden again

### Version

NFT build

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by Sylvia24** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by DigitalsupportTeam** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by darkwing** [comment]
The following error is being seen in the console when toggling visibility of a collection.

```
Uncaught Error: Invariant failed: A state mutation was detected between dispatches, in the path 'metamask.nftsDropdownState.0x0836f5ed6b62baf60706fe3adc0ff0fd1df833da.0x1'.  This may cause incorrect behavior. (https://redux.js.org/style-guide/style-guide#do-not-mutate-state)
  at invariant (redux-toolkit.cjs.development.js:279:1)
  at redux-toolkit.cjs.development.js:382:1
  at Object.measureTime (redux-toolkit.cjs.development.js:218:1)
  at redux-toolkit.cjs.development.js:378:1
  at updateNftDropDownStateKey (nfts-items.js:121:5)
  at onClick (nfts-items.js:136:13)
  at HTMLUnknownElement.callCallback (react-dom.development.js:336:1)
  at Object.invokeGuardedCallbackDev (react-dom.development.js:385:1)
  at invokeGuardedCallback (react-dom.development.js:440:1)
  at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:454:1)
```
