### ISSUE TITLE
[Bug]: MM crashes when attempting to sign transactions on chrome v78

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18077]
### Describe the bug

Extension crashes when attempting to sign a transaction on chrome v78

<img width="1524" alt="popup replaceAll" src="https://user-images.githubusercontent.com/53189696/224074848-60c9cb0e-a3d3-4122-96ab-3bdb8a43c22a.png">

<img width="1524" alt="home replaceAll" src="https://user-images.githubusercontent.com/53189696/224074823-c6f5f8ee-a806-4756-856b-0aa0e94b720f.png">

### Steps to reproduce

1. log in
2. navigate to the [test-dapp](https://metamask.github.io/test-dapp/)
3. connect your account
4. click the personal sign

### Error messages or log output

```shell
Error details
Message: e.replaceAll is not a function

Code: TypeError

Stack:
TypeError: e.replaceAll is not a function
  at r.sanitizeString (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/common-4.js:1:236138)
  at chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-5.js:1:269873
  at Array.map (<anonymous>)
  at C.renderBody (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-5.js:1:269614)
  at C.render (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-5.js:1:271966)
  at Za (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:71391)
  at Ja (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:71186)
  at Cu (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:106049)
  at Tl (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:90710)
  at gl (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:90635)
  at fl (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:87983)
  at chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:46441
  at n.unstable_runWithPriority (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:417870)
  at $o (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:46150)
  at Zo (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:46386)
  at Jo (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:46321)
  at ue (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:114836)
  at Pn (chrome-extension://oncjinogblopmnajjjkkajbmppfdcahg/ui-3.js:1:29796)
```

### Version

10.26

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by PeterYinusa** [comment]
Applies to;
- Eth Sign
- Personal Sign
- Sign Typed Data
