### ISSUE TITLE
[Bug]: Metamask not showing confirmed or failed transaction notifications on chrome and brave

### ISSUE THREAD

**Issue by farzad-eth** [MetaMask/metamask-extension#18235]
### Describe the bug

In new update of metamask transaction notifications not showing on chrome and brave
![b213a91efe5661849086e58594b0d8753625e3db](https://user-images.githubusercontent.com/87241134/226352003-d717e9bc-b101-49c8-9610-98f2b2509ca2.jpeg)
![metamask](https://user-images.githubusercontent.com/87241134/226352106-b92e413e-c618-4f5c-ad08-c650c4d243d3.png)

### Steps to reproduce

1.Confirmed or failed transaction notification not showing on chrome and brave in new version of metamask

### Version

10.26.1

### Build type

None

### Browser

Chrome, Brave

### Operating system

Windows

**Comment by 4luxon** [comment]
10.26.2 too not work notifications

**Comment by matthewwalsh0** [comment]
This is due to LavaMoat scuttling causing the internal browser code to fail.

I can confirm this is also affecting OS X.

```
LavaMoat - property "Image" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
  at get (runtime-lavamoat.js:11200:17)
  at loadImageDataForNonServiceWorker (extensions::imageUtil:72:13)
  at loadImageData (extensions::imageUtil:113:5)
  at Object.loadAllImages (extensions::imageUtil:134:5)
  at replaceNotificationOptionURLs (extensions::notifications:89:13)
  at extensions::notifications:116:5
  at common-3.js:3:767697
  at new Promise (<anonymous>)
  at Proxy.<anonymous> (common-3.js:3:767377)
  at Object.apply (common-3.js:3:766796)
  at r.default._showNotification (common-1.js:1:27013)
```

**Comment by matthewwalsh0** [comment]
See #18323 for fix.
