### ISSUE TITLE
[Bug]: Cannot switch to Polygon/Optimism/Arbitrum one

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18304]
### Describe the bug

Cannot switch to Polygon/Optimism/Arbitrum one

<img width="1370" alt="Switch Network" src="https://user-images.githubusercontent.com/53189696/227282634-d3ae2a2b-86c0-42d1-ab6e-a0b19a5018d4.png">

### Steps to reproduce

1. Log in to MM
2. Add a network `Polygon/Optimism/Arbitrum one`
3. Switch to the newly added network from the Network picker `Dismiss the switch network prompt when adding the network`

### Error messages or log output

```shell
TypeError: Cannot destructure property 'blockExplorerUrl' of 'undefined' as it is undefined.
  at Object.setRpcTarget (ui-4.js:1:1089143)
  at onClick (ui-4.js:1:1083305)
  at onClick (ui-4.js:1:1079119)
  at e.<computed> (sentry-install.js:1:677)
  at Object.m (ui-3.js:1:1548)
  at e.<computed> (sentry-install.js:1:677)
  at T (ui-3.js:1:1691)
  at e.<computed> (sentry-install.js:1:677)
  at ui-3.js:1:1837
  at x (ui-3.js:1:1923)
  at C (ui-3.js:1:2349)
  at k (ui-3.js:1:2184)
  at j (ui-3.js:1:2532)
  at _n (ui-3.js:1:29513)
  at se (ui-3.js:1:115013)
  at jn (ui-3.js:1:30128)
  at Mn (ui-3.js:1:31085)
  at Rn (ui-3.js:1:30373)
  at n.unstable_runWithPriority (ui-3.js:1:417870)
  at $o (ui-3.js:1:46150)
  at ue (ui-3.js:1:114790)
  at Pn (ui-3.js:1:29796)
(
```

### Version

10.27

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
Resolved in 129535095ac85ece970d6bdca4568241a1198afe
