### ISSUE TITLE
[Bug]: Error: Request method wallet_switchEthereumChain is not supported

### ISSUE THREAD

**Issue by CiprianDraghici** [MetaMask/metamask-extension#18310]
### Describe the bug

I am trying to switch the Metamask chain. If the chain is not available then I am trying to create one,
but no request is working.

For the majority of users, everything is fine but there are a few of them that have this strange error

### Steps to reproduce

I cannot reproduce it on my laptops (macOS 13.2.1  and ubuntu 22.04) unfortunately.
This is a very strange issue that was reported only by 2 of my users. 
They have the latest Metamask extension version installed on Google Chrome. I can't find a way to reproduce the issue using their environment on my machines.

Used these links as references
https://docs.metamask.io/guide/rpc-api.html#unrestricted-methods
https://docs.cloud.coinbase.com/wallet-sdk/docs/switching-chains

### Error messages or log output

``` 
Error: Request method wallet_switchEthereumChain is not supported
    at a.request (requestProvider.js:2:503657)
    at main.c334f3b1.js:2:3646856
    at d (main.c334f3b1.js:2:1893339)
    at Generator.<anonymous> (main.c334f3b1.js:2:1894682)
    at Generator.next (main.c334f3b1.js:2:1893702)
    at r (main.c334f3b1.js:2:1887797)
    at s (main.c334f3b1.js:2:1888000)
    at main.c334f3b1.js:2:1888059
    at new Promise (<anonymous>)
    at main.c334f3b1.js:2:1887940
```

<img width="845" alt="image" src="https://user-images.githubusercontent.com/11082863/227359999-4e0981d8-8ebf-4061-a9cc-3604c4e1d69b.png">
<img width="928" alt="image" src="https://user-images.githubusercontent.com/11082863/227360111-66588ced-4988-42b9-8f3d-0eb46e9eba2a.png">

### Version

10.26.2

### Build type

None

### Browser

Chrome

### Operating system

Windows, MacOS, Linux

### Additional context

Does anyone have any idea why this is happening?

**Comment by CiprianDraghici** [comment]
The issue was triggered because of multiple wallet extensions installed on the same browser.

Fix reference:
https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance
