### ISSUE TITLE
[Bug]: waitForTransaction with ethers provider generates PortDuplexStream error

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/metamask-extension#18340]
### Describe the bug

When I call `waitForTransaction` on an ethers provider (specifically an `InfuraProvider`) I am seeing a `PortDuplexStream` error:

```
MetaMask: Content script lost connection to "MetaMask Background Multiplex". Error: PortDuplexStream - disconnected
  at t.exports._write (contentscript.js:29:133244)
  at v (contentscript.js:44:25955)
  at contentscript.js:44:29133
  at b.write (contentscript.js:44:29160)
  at t.exports.m (contentscript.js:44:18143)
  at h (contentscript.js:20:21091)
  at o.emit (contentscript.js:20:24077)
  at _ (contentscript.js:44:12946)
  at w (contentscript.js:44:12761)
  at v.push (contentscript.js:44:13572)
contentscript.js:1 MetaMask: Content script lost connection to "MetaMask Background Legacy Multiplex". Error: PortDuplexStream - disconnected
  at t.exports._write (contentscript.js:29:133244)
  at v (contentscript.js:44:25955)
  at contentscript.js:44:29133
  at b.write (contentscript.js:44:29160)
  at t.exports.m (contentscript.js:44:18143)
  at h (contentscript.js:20:21091)
  at o.emit (contentscript.js:20:24077)
  at _ (contentscript.js:44:12946)
  at w (contentscript.js:44:12761)
  at v.push (contentscript.js:44:13572)
contentscript.js:1 MetaMask: Muxed traffic for channel "metamask-provider" failed. undefined
contentscript.js:1 MetaMask: Muxed traffic between channels "provider" and "metamask-provider" failed. undefined
contentscript.js:1 MetaMask: Muxed traffic for channel "publicConfig" failed. undefined
```

The relevant Javascript calling code is:

```javascript
      const chainNumber = getNumber(chain);
      const isLocalChain = chainNumber == 1337;

      const provider = isLocalChain
        ? new JsonRpcProvider()
        : new InfuraProvider(
          chainNumber,
          process.env.INFURA_API_KEY,
        );
      const txReceipt = await provider.waitForTransaction(txHash);
```

### Steps to reproduce

1. Install MetaMask Flask >= 10.25.0
2. Visit https://tss.ac
3. Generate a key share
4. Sign a transaction (Goerli is recommended)
5. Submit the transaction to the network 
6. You should see the error in the browser console

### Error messages or log output

```shell
SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  Window null
 Setting up Sentry Remote Error Reporting for 'production-flask': SENTRY_DSN
 Removing intrinsics.%ArrayPrototype%.toReversed
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%ArrayPrototype%.toSorted
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%ArrayPrototype%.toSpliced
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%ArrayPrototype%.with
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toReversed
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSorted
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%ArrayPrototype%.@@unscopables.toSpliced
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%StringPrototype%.isWellFormed
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%StringPrototype%.toWellFormed
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%FunctionPrototype%.apply.prototype
visitProperties @ runtime-lavamoat.js:8914
 Tolerating undeletable intrinsics.%FunctionPrototype%.apply.prototype === undefined
visitProperties @ runtime-lavamoat.js:8924
 Removing intrinsics.%FunctionPrototype%.bind.prototype
visitProperties @ runtime-lavamoat.js:8914
 Tolerating undeletable intrinsics.%FunctionPrototype%.bind.prototype === undefined
visitProperties @ runtime-lavamoat.js:8924
 Removing intrinsics.%TypedArrayPrototype%.toReversed
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%TypedArrayPrototype%.toSorted
visitProperties @ runtime-lavamoat.js:8914
 Removing intrinsics.%TypedArrayPrototype%.with
visitProperties @ runtime-lavamoat.js:8914
 Property eval will not be hardened because it is scuttled by LavaMoat protection. Visit https://github.com/LavaMoat/LavaMoat/pull/360 to learn more.
(anonymous) @ lockdown-more.js:74
 missing dep: ethjs>ethjs-unit>bn.js requested buffer
getRelativeModuleId @ runtime-lavamoat.js:11626
 missing dep: ethjs>number-to-bn>bn.js requested buffer
getRelativeModuleId @ runtime-lavamoat.js:11626
 WARNING: Missing strong random number source
 missing dep: ethjs-contract>ethjs-abi>bn.js requested buffer
getRelativeModuleId @ runtime-lavamoat.js:11626
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "networkDidChange" listeners added. Use emitter.setMaxListeners() to increase limit.
m @ common-1.js:22
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 14 "update" listeners added. Use emitter.setMaxListeners() to increase limit.
m @ common-1.js:22
 SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  global <iframe src=​"https:​/​/​metamask.github.io/​phishing-warning/​v2.0.1/​#extensionStartup" sandbox=​"allow-scripts allow-same-origin">​…​</iframe>​
 SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  global <iframe id=​"hWudpiOYTIpnuCLxL0MYa" src=​"https:​/​/​metamask.github.io/​iframe-execution-environment/​0.12.0" sandbox=​"allow-scripts">​…​</iframe>​
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  global <iframe src=​"https:​/​/​metamask.github.io/​eth-ledger-bridge-keyring" allow=​"hid 'src'">​…​</iframe>​
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
bundle.js:373 MetaMask < = > Ledger Bridge initialized from https://metamask.github.io/eth-ledger-bridge-keyring/!
 Parent: Sending Command Object
 Job "hWudpiOYTIpnuCLxL0MYa" terminated.
 SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  global <iframe id=​"q0bgNQO8n0oLedkbdujGD" src=​"https:​/​/​metamask.github.io/​iframe-execution-environment/​0.12.0" sandbox=​"allow-scripts">​…​</iframe>​
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Job "q0bgNQO8n0oLedkbdujGD" terminated.
 SNOW INTERCEPTED NEW WINDOW CREATION IN METAMASK APP:  global <iframe id=​"qfBAL5hZdY7oEmCGiHMhm" src=​"https:​/​/​metamask.github.io/​iframe-execution-environment/​0.12.0" sandbox=​"allow-scripts">​…​</iframe>​
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "data" listeners added. Use emitter.setMaxListeners() to increase limit.
m @ common-1.js:22
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Parent: Sending Command Object
 Job "qfBAL5hZdY7oEmCGiHMhm" terminated.
```

### Version

10.26.1

### Build type

Flask

### Browser

Chrome

### Operating system

MacOS

### Additional context

This code used to work fine so not sure when this error was introduced.

**Comment by danjm** [comment]
@tmpfs I see from the error output that this happened when you were interacting with MetaMask Flask. Does the same occur when interacting with the main extension build?

**Comment by tmpfs** [comment]
@danjm, i can't tell you right now as this code is deeply embedded in a dapp which works in conjunction with a snap which in turn requires Flask.

We would need to reproduce this in isolation to determine if the problem is Flask specific.

**Comment by tmpfs** [comment]
I don't know exactly which version this problem arrived in but i am pretty sure this code was working correctly before i upgraded to `10.25.0`. Sorry can't be more specific.
