### ISSUE TITLE
[Bug]: Almost unusable after most recent updates

### ISSUE THREAD

**Issue by RnbWd** [MetaMask/metamask-extension#18378]
### Describe the bug

The app is constantly freezing. I need to reset my browser after about 10 transactions. I need to open and close the extension multiple times between transactions because the loading screen will not disappear. It loses sync with hardware wallets and the only way to regain connection is to reset metamask. Also the app has become about 20x slower than it used to be when loading transactions. Almost 50% of the time I open the app and there's an error message with a javascript function method that doesn't exist crashing the app. Each time I update the extension there are more bugs than the previous version.

### Steps to reproduce

1. Use metamask for anything, preferably with a hardware wallet. 

### Version

10.27.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
@RnbWd @NinjaTurtle007 Can you share any error messages that you are seeing?

**Comment by seaona** [comment]
Might be the same as https://github.com/MetaMask/metamask-extension/issues/17467

**Comment by NinjaTurtle007** [comment]
@danjm There are no error messages just hanging on the loading circle screen indefinitely

**Comment by seaona** [comment]
@NinjaTurtle007 whenever MetaMask stays loading, could you right click it, go to Inspect, and open the console? 
In case you see any errors could you paste them here? Let us know if this makes sense. Thank you in advance

**Comment by RazvanPacala** [comment]
The following errors appears in the console when this behavior is occurring:
```
Error in event handler: Error: StreamProvider - Unknown response id for response: [object Object]
  at a._onResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:489340)
  at a._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:489565)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:34397)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:37581
  at y.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:37608)
  at t.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:26357)
  at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:99:215887)
  at o.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:99:218882)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:21157)
  at v (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:20972)
  at _.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:21786)
  at a.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:8:959973)
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:34397)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:37581
  at y.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:37608)
  at t.exports.m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:26357)
  at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:99:215887)
  at o.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:99:218882)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:21157)
  at v (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:20972)
  at _.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:21786)
  at t.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:255693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:12:255540
```

Screenshot: https://www.screencast.com/t/r1k08mNarro

The behavior is indefinite loading either at the start or after confirming a transaction (the app should close but remains in loading state). 
This has been tested on Mozilla Firefox//Microsoft Edge/Google Chrome/Safari (latest version to date).

**Comment by danielhursan** [comment]
I have this issue as well, on both 10.25 and 10.27.
On 10.23.2 (December 23rd, 2022) it used to work correctly, so some but recently introduced.
@seaona , any ETA from the team on fixing this issue? We might have to postpone release to production because of it :(

**Comment by gregors** [comment]
same as #18234 as well! I be this issue has been reported more than a few times in separate issues.

**Comment by danjm** [comment]
v10.28.2 has now been released to 100% of chrome users. Please comment here if you still experience issues like described above on v10.28.2

**Comment by danjm** [comment]
Was fixed in v10.282
