### ISSUE TITLE
[Bug]: eth_signTypedData_v4 should take an object as well as string for `data`

### ISSUE THREAD

**Issue by shanejonas** [MetaMask/metamask-extension#18462]
### Describe the bug

When trying to use `eth_signTypedData_v4` it should work using an object syntax and not have to `JSON.stringify` the `data` parameter before passing to metamask.

In [EIP-712](https://eips.ethereum.org/EIPS/eip-712#eth_signtypeddata) it does not expect that the 2nd parameter (data) is JSON.stringified

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/364566/230124519-cb1234c2-1f3f-45e1-8e1f-8eaa4809fced.png">

Also comments for `signTypedMessage` in the code says this should work.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/364566/230122617-33509366-1e91-4ae0-b7f9-41857e52cf94.png">

### Steps to reproduce

1. go to https://metamask.github.io/api-playground/api-documentation/#eth_signTypedData_v4
2. make sure your wallet is connected to the page (via the ui or call requestPermissions via the playground)
3. use your address in `eth_signTypedData_v4` as the first parameter
![image](https://user-images.githubusercontent.com/364566/230121969-93714b40-48da-4c36-b764-6c65923fe994.png)

### Error messages or log output

```shell
SyntaxError: "[object Object]" is not valid JSON
  at JSON.parse (<anonymous>)
  at SignatureRequest.<anonymous> (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-6.js:13411:16)
  at SignatureRequest.memoized [as memoizedParseMessage] (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/common-4.js:10628:27)
  at SignatureRequest.render (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-6.js:13506:14)
  at finishClassComponent (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-4.js:18478:31)
  at updateClassComponent (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-4.js:18431:24)
  at beginWork$1 (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-4.js:20194:16)
  at HTMLUnknownElement.callCallback (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-4.js:344:14)
  at Object.invokeGuardedCallbackDev (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-4.js:393:16)
  at invokeGuardedCallback (chrome-extension://famgliladofnadeldnodcgnjhafnbnhj/ui-4.js:448:31)
```

### Version

develop

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Chrome

### Operating system

MacOS

### Additional context

this is on `develop`.

looks like it errors on the [`signature-request.component.js`](https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/app/signature-request/signature-request.component.js#L123)

I was able to get it to work locally by changing [this line](https://github.com/MetaMask/metamask-extension/blob/develop/ui/components/app/signature-request/signature-request.component.js#L123) to:

```
    const d = typeof data === 'object' ? data : JSON.parse(data);
    const { message, domain = {}, primaryType, types } = d;
```

which doesn't feel like the best solution

**Comment by vandan** [comment]
Asking DevEx to take a look at this one. It's blocking our ability to incorporate signTypedData_v4 into the API playground.
