### ISSUE TITLE
[Bug]: Unable to find value of key "notifications18Title" for locale "en"

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18666]
### Describe the bug

Missing translation

```
"notifications18Title": {
    "message": "Stay safe with security alerts"
  },
```

### Steps to reproduce

1. build [v10.29.0](https://github.com/MetaMask/metamask-extension/pull/18488)
2. install mm
3. complete onboarding
4. check what's new title for the security provider 

### Error messages or log output

```shell
ui-7.js:1 Error: Unable to find value of key "notifications18Title" for locale "en"
  at a.getMessage (ui-7.js:1:105330)
  at ui-6.js:1:380631
  at r.getTranslatedUINotifications (common-4.js:1:63787)
  at ui-5.js:1:450390
  at Array.map (<anonymous>)
  at k (ui-5.js:1:450330)
  at ha (ui-3.js:1:60036)
  at Cu (ui-3.js:1:104794)
  at Tl (ui-3.js:1:90710)
  at gl (ui-3.js:1:90635)
  at fl (ui-3.js:1:87983)
  at ui-3.js:1:46441
  at n.unstable_runWithPriority (ui-3.js:1:417870)
  at $o (ui-3.js:1:46150)
  at Zo (ui-3.js:1:46386)
  at Jo (ui-3.js:1:46321)
  at dl (ui-3.js:1:88275)
  at Object.notify (ui-3.js:1:209185)
  at t.notifyNestedSubs (ui-3.js:1:208752)
  at t.handleChangeWrapper (ui-3.js:1:208820)
  at v (ui-3.js:1:406399)
  at ui-3.js:1:404472
  at e.<computed> (sentry-install.js:1:682)
  at dispatch (ui-3.js:1:407382)
  at ui-10.js:1:39390
  at async onClick (ui-8.js:1:324510)
```

### Version

v10.29

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by danjm** [comment]
this was fixed here https://github.com/MetaMask/metamask-extension/pull/18526, just needed to be pulled into the v10.29.0 branch, which it has
