### ISSUE TITLE
Uncaught Error: Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by zincoshine** [MetaMask/metamask-extension#1874]
**Get Uncaught Error: Invalid number of arguments to Solidity function**, while accessing gnosis multisig wallet on the link **https://wallet.gnosis.pm/#/wallets**
  Briefly describe the issue you've encountered
  *  Expected Behavior: The website should list me all the pending/completed transactions on the multisig wallet.
  *  Actual Behavior: The transactions are not listed correctly, while on javascript console I see the following error: 

> Uncaught Error: Invalid number of arguments to Solidity function
>     at Object.InvalidNumberOfSolidityArgs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8252:27907)
>     at c.validateArgs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8253:5768)
>     at c.toPayload (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8253:5933)
>     at c.request (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8253:7503)
>     at Object.wallet.callRequest (https://wallet.gnosis.pm/services/Wallet.js:163:38)
>     at Object.wallet.getTransaction (https://wallet.gnosis.pm/services/Wallet.js:959:23)
>     at https://wallet.gnosis.pm/controllers/walletDetailCtrl.js:308:24
>     at Array.map (native)
>     at https://wallet.gnosis.pm/controllers/walletDetailCtrl.js:302:17
>     at Object.callback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:8253:6604)

  *  Browser Used
Version 59.0.3071.115 (Official Build) (64-bit)
  *  Operating System Used
Ubuntu 16.04

  Screenshots are very helpful and will expedite your issue being resolved!

![metamask](https://user-images.githubusercontent.com/1627026/29079747-9da75516-7c7b-11e7-91f1-9d08c6d4f5bf.png)

The same website was working very well before the earlier release of metamask (prior to 4th August).
PS: Accessing the same link via Firefox version 54 and Metamask works!

**Comment by zincoshine** [comment]
Tested the same URL using Metamask chrome extension on Mac, it fails there as well. Apparently the link works fine on Chrome (latest build) on Windows.

**Comment by kumavis** [comment]
sounds like gnosis is not bundling their own `web3` per our best practices and is not hitting a version mismatch

**Comment by tcoulter** [comment]
Quick note: I found this issue occurred when Metamask was used properly (i.e., using the provider only) and a transaction was made when the extension was locked. Going to see if I can track it down now.

**Comment by tcoulter** [comment]
You can ignore my comment above. Turns out when Metamask is locked `web3.eth.accounts` is an empty array, and I was passing the first value in that empty array (`undefined`) into a contract call that required it. 

Turns out in my case the error was justified.
