### ISSUE TITLE
[Bug]: Failed to accept transaction approval request error thown when speeding up and cancelling transactions

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#18809]
### Describe the bug

The following error is thrown every time I speed up or cancel a send transaction.

```
Failed to accept transaction approval request Error: Approval request with id '7835395317773756' not found.
```

I cannot see any obvious side effects, but I wouldn't expect this to happen

Possibly related to https://github.com/MetaMask/metamask-extension/pull/18400 or https://github.com/MetaMask/metamask-extension/pull/18386

### Steps to reproduce

1. log in to the extension
2. click send button
3. enter an address
4. enter an amount
5. click next
6. confirm the transaction
7. speed up/ cancel the transaction

### Error messages or log output

```shell
sentry-install.js:1 Failed to accept transaction approval request Error: Approval request with id '7835395317773756' not found.
  at new n (background-0.js:1:17626)
  at u._deleteApprovalAndGetCallbacks (background-0.js:1:17159)
  at u.accept (background-0.js:1:15032)
  at n.ControllerMessenger.call (common-0.js:1:125534)
  at r.call (common-0.js:1:124155)
  at F._acceptApproval (background-3.js:10:223575)
  at F.approveTransaction (background-3.js:10:205792)
  at F.createSpeedUpTransaction (background-3.js:10:205300)
  at De.createSpeedUpTransaction (background-4.js:1:288459)
  at x.<anonymous> (background-4.js:1:132350)
  at l (common-1.js:7:217915)
  at s.emit (common-1.js:7:220910)
  at v (common-3.js:1:113484)
  at w (common-3.js:1:113299)
  at g.push (common-3.js:1:114113)
  at a.exports._write (common-3.js:1:54883)
  at g (common-3.js:1:126724)
  at common-3.js:1:129908
  at m.write (common-3.js:1:129935)
  at t.exports.l (common-3.js:1:118684)
  at l (common-1.js:7:217915)
  at s.emit (common-1.js:7:220910)
  at v (common-3.js:1:113484)
  at w (common-3.js:1:113299)
  at g.push (common-3.js:1:114113)
  at t.exports._onMessage (common-1.js:25:282267)
  at common-1.js:25:282114
```

### Version

10.30

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by PeterYinusa** [comment]
Completed in https://github.com/MetaMask/metamask-extension/pull/18846
