### ISSUE TITLE
Error: [ethjs-query] 

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#1886]
Hi,

today while trying to use metamask on ethereumjs-testrpc running on localhost I get this error upon calling sendTransaction on a contract method :

```
Error: [ethjs-query] while formatting outputs from RPC '{"number":"0x01","hash":"0xebe6c2414b3f0e5296198a4927b718ae94640a4e3f67a7e41825c0b5cb6ce5d1","parentHash":"0x54d71c4729af8f6ca632a6b215b4b7773928849dd7f46e650abb2c7e9ad0fd7e","nonce":"0x0","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","stateRoot":"0xab18f66801075b2e24aa9032285a658a10d8c066211fd1527129e5900286ff87","receiptRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","miner":"0x0000000000000000000000000000000000000000","difficulty":"0x0","totalDifficulty":"0x0","extraData":"0x0","size":"0x03e8","gasLimit":"0x47e7c4","gasUsed":"0x250985","timestamp":"0x598b12e1","transactions":[{"hash":"0x4d5017c4071b7c60200e86cd0b5b38e1dfd889ea3f9241a52193df99cf8dfc4d","nonce":"0x0","blockHash":"0xebe6c2414b3f0e5296198a4927b718ae94640a4e3f67a7e41825c0b5cb6ce5d1","blockNumber":"0x01","transactionIndex":"0x0","from":"0x3b26935917de7f5fac60f6d15ff02b1cf468dfb0","to":"0x0","value":"0x0","gas":"0x3d0900","gasPrice":"0x059682f000","input":"0x6060604052341561000c57fe5b5b6123488061001c6000396000f300606060405236156100965763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166308f75d178114610098578063497777d5146100b35780635598c576146100c85780637017f8d8146100e957806373931bbf14610121578063849a742b146101cb578063a361b184146101e5578063ee62800f146101fd578063f151e0881461022f575bfe5b34156100a057fe5b6100b160043560ff60243516610272565b005b34156100bb57fe5b6100b1600435610576565b005b34156100d057fe5b6100b160043560ff602435166044356064356106f6565b005b6100b160043563ffffffff6024358116906044351660ff6064351661ffff60843516600160a060020a0360a4351660c435610f26565b005b341561012957fe5b610134600435611372565b6040805161ffff909e168e5263ffffffff909c1660208e015260ff9a8b168d8d0152988a1660608d0152600097880b90970b60808c015294881660a08b0152600160a060020a0393841660c08b01529190921660e089015290851661010088015290931661012086015267ffffffffffffffff92831661014086015282166101608501521661018083015251908190036101a00190f35b34156101d357fe5b6100b16004356024351515611432565b005b34156101ed57fe5b6100b1600435602435611552565b005b6100b160043560ff6024351663ffffffff6044351661ffff60643516600160a060020a036084351660a43561176e565b005b6100b1600435600160a060020a0360243581169063ffffffff6044358116916064359091169060ff608435169061ffff60a435169060c4351660e435611d22565b005b600082815260208190526040902060058101546003604060020a90910460ff16108015906102b657506005810154600290604060020a900460ff165b0660ff166001145b80156102ec5750600181015433600160a060020a03908116911614806102ec5750600381015433600160a060020a039081169116145b5b801561032757506005810154600482015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff164203105b1561042a5760058101546000660100000000000090910460ff1611801561034f575060ff8216155b8061036e5750600581015460ff66010000000000009091048116908316115b1561039b57604080516101f9815290516000805160206122fd8339815191529181900360200190a1610425565b600581018054604060020a60ff8086166a0100000000000000000000026aff00000000000000000000199093169290921781810483166001019092160268ff00000000000000001990911617905560048101805467ffffffffffffffff421660a060020a027bffffffffffffffff0000000000000000000000000000000000000000199091161790555b61056d565b60058101546003604060020a90910460ff161080159061046057506005810154600290604060020a900460ff165b0660ff166001145b151561048e57604080516101f5815290516000805160206122fd8339815191529181900360200190a161056d565b600181015433600160a060020a03908116911614806104bd5750600381015433600160a060020a039081169116145b15156104eb57604080516101f6815290516000805160206122fd8339815191529181900360200190a161056d565b6005810154600482015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff1642031061054957604080516101f7815290516000805160206122fd8339815191529181900360200190a161056d565b604080516101f8815290516000805160206122fd8339815191529181900360200190a15b5b5b5b5b505050565b60008181526020819052604090206005810154600482015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff16420311156106cd5760058101546004604060020a90910460ff16108015906105f157506005810154600290604060020a900460ff165b0660ff166000145b8061060a57506005810154604060020a900460ff166001145b8061062357506005810154604060020a900460ff166002145b15610648576003810154610643908390600160a060020a031660fd612177565b6106c7565b60058101546003604060020a90910460ff161080159061067e57506005810154600290604060020a900460ff165b0660ff166001145b156106a3576004810154610643908390600160a060020a031660fe612177565b6106c7565b604080516102be815290516000805160206122fd8339815191529181900360200190a15b5b6106f1565b604080516102bd815290516000805160206122fd8339815191529181900360200190a15b5b5050565b600084815260208190526040812060058101549091906004604060020a90910460ff161080159061073d57506005820154600290604060020a900460ff165b0660ff166000145b80156107735750600282015433600160a060020a03908116911614806107735750600482015433600160a060020a039081169116145b5b80156107ae57506005820154600483015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff164203105b801561081457508154604080518681526c01000000000000000000000000600160a060020a0333160260208201527f010000000000000000000000000000000000000000000000000000000000000060ff89160260348201529051908190036035019020145b15610d4c5760058201805468ff0000000000000000198116604060020a9182900460ff908116600101811690920217918290556004840180547bffffffffffffffff0000000000000000000000000000000000000000191660a060020a4267ffffffffffffffff160217905560006701000000000000009092041611801561089d575060ff8516155b806108bd5750600582015460ff6701000000000000009091048116908616115b156108ea576040805161025e815290516000805160206122fd8339815191529181900360200190a1610f19565b5060058101805483835567ff000000000000001966ff000000000000196bff0000000000000000000000199092166b01000000000000000000000060ff898116918202929092179384166a01000000000000000000008504831666010000000000009586900484168190038416909502179283166701000000000000009384900483168a900390921690920217909255908110156109b85760058201805469ff00000000000000000019811660ff604860020a92839004600090810b60001901900b169091021790556109f7565b8460ff168160ff1611156109f75760058201805469ff00000000000000000019811660ff604860020a92839004600090810b600101900b169091021790555b5b6005820154600119604860020a909104600090810b900b1215610a35576004820154610a30908790600160a060020a031660ff612177565b610d3f565b60058201546002604860020a909104600090810b900b1315610a71576003820154610a30908790600160a060020a031660ff612177565b610d3f565b6005820154670100000000000000900460ff16158015610aa0575060058201546601000000000000900460ff16155b15610b275760058201546000604860020a909104810b810b1215610ade576004820154610ad9908790600160a060020a031660ff612177565b610a30565b60058201546000604860020a909104810b810b1315610b17576003820154610ad9908790600160a060020a031660ff612177565b610a30565b610a30866121d0565b5b5b610d3f565b60058201546601000000000000900460ff16158015610b5957506005820154600067010000000000000090910460ff16115b15610ba25760058201805460ff67010000000000000082048116604860020a808404600090810b9290920390910b9091160269ff00000000000000000019909116179055610c16565b60058201546000660100000000000090910460ff16118015610bd457506005820154670100000000000000900460ff16155b15610c1657600582018054604860020a808204600090810b60ff6601000000000000850481169190910190910b160269ff000000000000000000199091161790555b5b6005820154600119604860020a909104600090810b900b1215610c54576004820154610a30908790600160a060020a031660ff612177565b610d3f565b60058201546002604860020a909104600090810b900b1315610c90576003820154610a30908790600160a060020a031660ff612177565b610d3f565b6005820154670100000000000000900460ff16158015610cbf575060058201546601000000000000900460ff16155b15610d3f5760058201546000604860020a909104810b810b1215610cfd576004820154610a30908790600160a060020a031660ff612177565b610d3f565b60058201546000604860020a909104810b810b1315610d36576003820154610a30908790600160a060020a031660ff612177565b610d3f565b610d3f866121d0565b5b5b5b5b5b5b5b5b610f19565b60058201546004604060020a90910460ff1610801590610d8257506005820154600290604060020a900460ff165b0660ff166000145b1515610db05760408051610259815290516000805160206122fd8339815191529181900360200190a1610f19565b600282015433600160a060020a0390811691161480610ddf5750600482015433600160a060020a039081169116145b1515610e0d576040805161025a815290516000805160206122fd8339815191529181900360200190a1610f19565b6005820154600483015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff16420310610e6b576040805161025b815290516000805160206122fd8339815191529181900360200190a1610f19565b8154604080518681526c01000000000000000000000000600160a060020a0333160260208201527f010000000000000000000000000000000000000000000000000000000000000060ff8916026034820152905190819003603501902014610ef5576040805161025c815290516000805160206122fd8339815191529181900360200190a1610f19565b6040805161025d815290516000805160206122fd8339815191529181900360200190a15b5b5b5b5b5b505050505050565b6000878152602081905260409020600501543482900390604060020a900460ff16158015610f5d5750637fffffff8663ffffffff16105b8015610f7557508563ffffffff1664e8d4a510000281145b8015610f84575060058560ff16115b8015610f935750607f8560ff16105b156113615761020060405190810160405280600060010260001916815260200184600160a060020a031681526020016000600160a060020a0316815260200133600160a060020a031681526020016000600160a060020a031681526020014267ffffffffffffffff1681526020018863ffffffff1681526020018763ffffffff1681526020018561ffff1681526020018660ff1681526020018660ff168152602001600160ff168152602001600060000b8152602001600060ff168152602001600060ff168152602001600060ff16815250600060008a600019166000191681526020019081526020016000206000820151816000019060001916905560208201518160010160006101000a815481600160a060020a030219169083600160a060020a0316021790555060408201518160020160006101000a815481600160a060020a030219169083600160a060020a0316021790555060608201518160030160006101000a815481600160a060020a030219169083600160a060020a0316021790555060808201518160040160006101000a815481600160a060020a030219169083600160a060020a0316021790555060a08201518160040160146101000a81548167ffffffffffffffff021916908367ffffffffffffffff16021790555060c082015181600401601c6101000a81548163ffffffff021916908363ffffffff16021790555060e08201518160050160006101000a81548163ffffffff021916908363ffffffff1602179055506101008201518160050160046101000a81548161ffff021916908361ffff1602179055506101208201518160050160066101000a81548160ff021916908360ff1602179055506101408201518160050160076101000a81548160ff021916908360ff1602179055506101608201518160050160086101000a81548160ff021916908360ff1602179055506101808201518160050160096101000a81548160ff021916908360000b60ff1602179055506101a082015181600501600a6101000a81548160ff021916908360ff1602179055506101c082015181600501600b6101000a81548160ff021916908360ff1602179055506101e082015181600501600c6101000a81548160ff021916908360ff1602179055509050506112e3838361228d565b60408051600160a060020a033316815267ffffffffffffffff421660208201528082018a905263ffffffff808a1660608301528816608082015260ff871660a082015261ffff861660c082015290517f63d25197136f006859621d3c2998730e89d80a2dc56ffd56a5f69534b57346a49181900360e00190a1611367565b60006000fd5b5b5050505050505050565b60008181526020819052604081206005810154600382015460049092015461ffff6401000000008304169363ffffffff83169360ff660100000000000085048116946701000000000000008104821694604860020a820490940b93604060020a8204831693600160a060020a0390811693908216926a010000000000000000000081048216926b0100000000000000000000009091049091169067ffffffffffffffff60a060020a9091041642435b91939597999b9d90929496989a9c50565b60008281526020819052604090206005810154600482015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff16420311156114855761042583610576565b61056d565b811561152757600381015433600160a060020a03908116911614156114c45760048101546114bf908490600160a060020a031660fe612177565b610425565b600481015433600160a060020a03908116911614156114fd5760038101546114bf908490600160a060020a031660fd612177565b610425565b60408051610322815290516000805160206122fd8339815191529181900360200190a15b5b61056d565b60408051610321815290516000805160206122fd8339815191529181900360200190a15b5b5b505050565b60008281526020819052604090206005810154604060020a900460ff1660021480156115a85750600281015433600160a060020a03908116911614806115a85750600481015433600160a060020a039081169116145b5b80156115e357506005810154600482015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff164203105b156116485760058101805468ff00000000000000001916680300000000000000001790558181556004810180547bffffffffffffffff0000000000000000000000000000000000000000191660a060020a4267ffffffffffffffff160217905561056d565b6005810154604060020a900460ff166002146116865760408051610191815290516000805160206122fd8339815191529181900360200190a161056d565b600281015433600160a060020a03908116911614806116b55750600481015433600160a060020a039081169116145b15156116e35760408051610192815290516000805160206122fd8339815191529181900360200190a161056d565b6005810154600482015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff164203106117415760408051610193815290516000805160206122fd8339815191529181900360200190a161056d565b60408051610194815290516000805160206122fd8339815191529181900360200190a15b5b5b5b5b505050565b60008681526020819052604081206001810154348490039290600160a060020a038681169116148015906117b057506005820154604060020a900460ff166001145b80156117e157506004820154600160a060020a031615806117e15750600482015433600160a060020a039081169116145b5b80156118015750600582015460ff898116660100000000000090920416145b801561181f5750600582015461ffff87811664010000000090920416145b801561183757508663ffffffff1664e8d4a510000283145b8015611865575064e8d4a51000835b0482600401601c9054906101000a900463ffffffff1663ffffffff1611155b8015611887575064e8d4a51000835b600584015491900463ffffffff90911610155b80156118c157506005820154600483015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff164203105b15611a42575060048101805460028301805473ffffffffffffffffffffffffffffffffffffffff19908116600160a060020a038981169190911790925560058501805468ff00000000000000001916680200000000000000001790819055921633909116177bffffffffffffffff0000000000000000000000000000000000000000191660a060020a4267ffffffffffffffff16021790915563ffffffff1664e8d4a5100002828111156119a3576003820154604051600160a060020a039091169084830380156108fc02916000818181858888f1935050505015156119a357fe5b5b64e8d4a51000835b046002028260050160006101000a81548163ffffffff021916908363ffffffff1602179055506119dc858561228d565b60408051600160a060020a0333168152602081018b905263ffffffff89168183015260ff8a16606082015261ffff8816608082015290517fe27ceab0817b7300a9aec54ed263f6a22db8311ccf3b841a78d1c352fa9b3eb69181900360a00190a1611d0d565b6001820154600160a060020a0386811691161415611a82576040805161012d815290516000805160206122fd8339815191529181900360200190a1611d0d565b6005820154604060020a900460ff16600114611ac0576040805161012e815290516000805160206122fd8339815191529181900360200190a1611d0d565b6004820154600160a060020a03161580611aea5750600482015433600160a060020a039081169116145b1515611b18576040805161012f815290516000805160206122fd8339815191529181900360200190a1611d0d565b600582015460ff89811666010000000000009092041614611b5b5760408051610130815290516000805160206122fd8339815191529181900360200190a1611d0d565b600582015461ffff8781166401000000009092041614611b9d5760408051610131815290516000805160206122fd8339815191529181900360200190a1611d0d565b64ffffffffff64e8d4a5100063ffffffff891602168314611be05760408051610132815290516000805160206122fd8339815191529181900360200190a1611d0d565b64e8d4a51000835b60048401549190047c010000000000000000000000000000000000000000000000000000000090910463ffffffff161115611c455760408051610133815290516000805160206122fd8339815191529181900360200190a1611d0d565b64e8d4a51000835b600584015491900463ffffffff9091161015611c8b5760408051610134815290516000805160206122fd8339815191529181900360200190a1611d0d565b6005820154600483015464010000000090910461ffff908116603c021660a060020a90910467ffffffffffffffff16420310611ce95760408051610135815290516000805160206122fd8339815191529181900360200190a1611d0d565b60408051610136815290516000805160206122fd8339815191529181900360200190a15b5b5b5b5b5b5b5b5b5b5b505050505050505050565b6000888152602081905260409020600501543482900390604060020a900460ff16158015611d595750637fffffff8663ffffffff16105b8015611d7157508563ffffffff1664e8d4a510000281145b8015611d80575060058560ff16115b8015611d8f5750607f8560ff16105b156113615761020060405190810160405280600060010260001916815260200184600160a060020a031681526020016000600160a060020a0316815260200133600160a060020a0316815260200189600160a060020a031681526020014267ffffffffffffffff1681526020018863ffffffff1681526020018763ffffffff1681526020018561ffff1681526020018660ff1681526020018660ff168152602001600160ff168152602001600060000b8152602001600060ff168152602001600060ff168152602001600060ff16815250600060008b600019166000191681526020019081526020016000206000820151816000019060001916905560208201518160010160006101000a815481600160a060020a030219169083600160a060020a0316021790555060408201518160020160006101000a815481600160a060020a030219169083600160a060020a0316021790555060608201518160030160006101000a815481600160a060020a030219169083600160a060020a0316021790555060808201518160040160006101000a815481600160a060020a030219169083600160a060020a0316021790555060a08201518160040160146101000a81548167ffffffffffffffff021916908367ffffffffffffffff16021790555060c082015181600401601c6101000a81548163ffffffff021916908363ffffffff16021790555060e08201518160050160006101000a81548163ffffffff021916908363ffffffff1602179055506101008201518160050160046101000a81548161ffff021916908361ffff1602179055506101208201518160050160066101000a81548160ff021916908360ff1602179055506101408201518160050160076101000a81548160ff021916908360ff1602179055506101608201518160050160086101000a81548160ff021916908360ff1602179055506101808201518160050160096101000a81548160ff021916908360000b60ff1602179055506101a082015181600501600a6101000a81548160ff021916908360ff1602179055506101c082015181600501600b6101000a81548160ff021916908360ff1602179055506101e082015181600501600c6101000a81548160ff021916908360ff1602179055509050506120de838361228d565b60408051600160a060020a03338116825267ffffffffffffffff421660208301528183018c90528a16606082015263ffffffff808a166080830152881660a082015260ff871660c082015261ffff861660e082015290517f3b02639f990ff28e23551ce9a1407174b2bef0652a6dbdc12d227e85c5810a2c918190036101000190a1611d0d565b60006000fd5b5b505050505050505050565b600083815260208190526040808220600581015491519092600160a060020a0386169264e8d4a5100063ffffffff9091160280156108fc02929091818181858888f19350505050506121c984836122c9565b5b50505050565b60008181526020819052604081206003810154600482015460058301549293600160a060020a0392831693929091169160029063ffffffff1664e8d4a51000025b6040519190049150600160a060020a0383169082156108fc029083906000818181858888f15050506005860154604051600160a060020a038716935064e8d4a5100063ffffffff9092169190910284900380156108fc029250906000818181858888f19350505050506122858560ff6122c9565b5b5050505050565b60008111156106f157604051600160a060020a0383169082156108fc029083906000818181858888f1935050505015156106f157fe5b5b5b5050565b600082815260208190526040902060058101805468ff00000000000000001916604060020a60ff8516021790555b505050560061ae744460330c100f3fed9aab830d7b96b79502dfbf7588e010e0b03c7b5df3a165627a7a723058201e09826acda6399334e30a6cc6ad753f05a1dc1859eb43b7afa05a6b756ae9720029"}],"uncles":[]}' for method 'getBlockByNumber' Error: [ethjs-format] hex string '0x00' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 4 bytes
    at cb (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:43819:31)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:43910:12
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:64308:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10069:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:9949:25)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:9939:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10085:16
    at resultObj.id (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:64288:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10160:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:9954:17)
```

I have no idea what that means.

The same setup (ethereumjs-testrpc on metamask) used to work. Metamask works fine on the mainnet though.

Metamask version 3.9.5 , not sure what was the version when it was working

**Comment by flyswatter** [comment]
I think this is a new change to TestRPC. EthJS-Query just added a patch that I believe will now tolerate this, we may need to roll-up our ethjs-query version to fix this:

https://github.com/ethjs/ethjs-format/pull/2

**Comment by wighawag** [comment]
cool, 
is there an archive of some sort to use an older version of metamask? This way when these kind of issue arise, we can use older working version.

**Comment by flyswatter** [comment]
We have all our historical releases online [here](https://github.com/MetaMask/metamask-extension/releases), but I suspect this break came from TestRPC, not MetaMask. Let us know either way!

**Comment by kumavis** [comment]
> hex string '0x00' must be an alphanumeric 42 utf8 byte hex (chars: a-fA-F) string, is 4 bytes

```json
{
  "number": "0x01",
  "hash": "0xebe6c2414b3f0e5296198a4927b718ae94640a4e3f67a7e41825c0b5cb6ce5d1",
  "parentHash": "0x54d71c4729af8f6ca632a6b215b4b7773928849dd7f46e650abb2c7e9ad0fd7e",
  "nonce": "0x0",
  "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  "stateRoot": "0xab18f66801075b2e24aa9032285a658a10d8c066211fd1527129e5900286ff87",
  "receiptRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  "miner": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x0",
  "totalDifficulty": "0x0",
  "extraData": "0x0",
  "size": "0x03e8",
  "gasLimit": "0x47e7c4",
  "gasUsed": "0x250985",
  "timestamp": "0x598b12e1",
  "transactions": [
    {
      "hash": "0x4d5017c4071b7c60200e86cd0b5b38e1dfd889ea3f9241a52193df99cf8dfc4d",
      "nonce": "0x0",
      "blockHash": "0xebe6c2414b3f0e5296198a4927b718ae94640a4e3f67a7e41825c0b5cb6ce5d1",
      "blockNumber": "0x01",
      "transactionIndex": "0x0",
      "from": "0x3b26935917de7f5fac60f6d15ff02b1cf468dfb0",
      "to": "0x0",
      "value": "0x0",
      "gas": "0x3d0900",
      "gasPrice": "0x059682f000",
      "input": "..."
    }
  ],
  "uncles": []
}
```

as i understand it, this is a change on our side by adopting ethjs-query in more places
ethjs-query is very strict and does not like some result being returned by testrpc

not sure where the actual issue is, as the params dont seem to include the value '0x00' anywhere

**Comment by SilentCicero** [comment]
@flyswatter I would need to publish a new ethjs-query for this. Give me 30.

**Comment by wighawag** [comment]
Thanks that was quick!
