### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'maxPriorityFeePerGas')

### ISSUE THREAD

**Issue by DemonRx** [MetaMask/metamask-extension#19091]
### Describe the bug

![Screenshot from 2023-05-10 19-44-15](https://github.com/MetaMask/metamask-extension/assets/18432686/7b3d0370-80c3-4031-99ed-1ef376655119)

### Steps to reproduce

1. Visit a sites such as uniswap or camelot.exchange or swapfish.fi swap pages
2. connect the wallet
3. select a coin to swap (that requires spending approval)
4. click approve which opens metamask to set the spending cap
5. click approve in metamask
6. the error then appears instead of going to the confirmation/gas fee dialogue

### Error messages or log output

```shell
Error messages is displayed in the attached screenshot to this bug report
```

### Version

10.30.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Additional context

I downgraded metamask to version 10.29 and the error no longer occurs.

**Comment by anaamolnar** [comment]
Hello @DemonRx. Thank you for reporting! Does this occur only on Ethereum Mainnet, or is consistent across other chains as well? Could you please send us a screenshot of your browser console logs when this error occurs? To do that, please follow these steps:
- Open the Metamask pop-up and the error will show
- Click right on the pop-up and then press 'Inspect'
- Go to the Console tab
- Look for red error messages and please send a screenshot of what you see in the logs

Thank you!

**Comment by snorkypie** [comment]
I have this exact problem. Works fine in 10.29.0 but broken in 10.30.1. I've attached screenshot from the console.

<img width="709" alt="Screenshot 2023-05-11 at 12 38 06" src="https://github.com/MetaMask/metamask-extension/assets/244598/47cc7eef-a141-452d-a152-88d7a456a30a">

**Comment by anaamolnar** [comment]
@snorkypie Thank you! Do you remember what you were doing before this happened? Does this occur on Ethereum mainnet for you, or on a different custom chain?

**Comment by DemonRx** [comment]
In regards to metamask on mobile I believe it's the same issue occuring there except you only see "internal json RPC error". The problem only occurs when approving token spending caps.

However it occurs intermittently.

![Screenshot_20230507_091924_MetaMask](https://github.com/MetaMask/metamask-extension/assets/18432686/eebdf6f0-bec9-47d2-8a5f-b67bce85f411)

**Comment by vANJKEEE** [comment]
Hello! I have exactly the same problem. I didn't check other networks, but on after updating the extension from version 10.29 to 10.30 = this problem immediately appeared.
When I try to set the approve limit, I get an error.

Chrome/Win10

![Screenshot_22](https://github.com/MetaMask/metamask-extension/assets/130900317/3722d271-bbe2-4053-ba85-ffd1d511eebb)

**Comment by sg4you** [comment]
Same for me on 10.30.1, Chrome/Windows10, Eth mainnet, yesterday a layer2 with same error. Seems to be when trying to abrove token/nft allowances.

**Comment by WangXueminGit** [comment]
Same for me on 10.30.1, arbitrum, when approve token allowances.
Is this one fixed?

**Comment by WangXueminGit** [comment]
> 

any work through?

**Comment by thuesdays** [comment]
> Same for me on 10.30.1, arbitrum, when approve token allowances. Is this one fixed?

Same issue with Arbitrum on token approval from https://stargate.finance/
version 10.30.1
Message: Cannot read properties of undefined (reading 'maxPriorityFeePerGas')

Code: TypeError

Stack:
TypeError: Cannot read properties of undefined (reading 'maxPriorityFeePerGas')
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:33041)
  at ha (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60036)
  at Cu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:104794)
  at Tl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90710)
  at gl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90635)
  at fl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:87983)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46441
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:417870)
  at $o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46150)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46386)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46321)
  at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:114836)
  at Pn (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:29796)

**Comment by alpari163** [comment]
I have same problem
I get this error on many wallets, only ARB chain and only when I try approve usdc spend, first it was on bebop xyz , 
i thought it was a bebop issue, but now I get this error when try approve spending on defillama (arb chain too)

**Comment by Alistrago** [comment]
**The same problem on Arbitrum chain.** 

MetaMask encountered an error
Try again by closing and reopening the popup, or contact support [here](https://metamask.zendesk.com/hc/en-us).
Error details
Message: Cannot read properties of undefined (reading 'maxPriorityFeePerGas')

Code: TypeError

Stack:
TypeError: Cannot read properties of undefined (reading 'maxPriorityFeePerGas')
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:33041)
  at ha (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60036)
  at Cu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:104794)
  at Tl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90710)
  at gl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90635)
  at fl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:87983)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46441
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:417870)
  at $o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46150)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46386)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46321)
  at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:114836)
  at Pn (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:29796)

**Comment by Alistrago** [comment]
I have just opened tread in Twitter. You can write there, tag Metamsk and Metamask support  https://twitter.com/alistrago_crypt/status/1657429244220260354?s=46&t=tC9o1HiSoOdR40NuapxmLA

**Comment by iamdimka1** [comment]
Hi guys, I also have this problem. Can you help me?

**Comment by Alistrago** [comment]
Download 10.29 version MM

**Comment by Starmand6** [comment]
I am currently getting this error on version 11.0.0. Same circumstances as others: happened when approving DAI and USDC token allowances on Arbitrum.
