### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wenhandi** [MetaMask/metamask-extension#19138]
### Describe the bug

<img width="371" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/12582497/5abd48cf-cddb-44d3-a9b4-9d776c5eebb7">
<img width="792" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/12582497/834046b2-f020-4ea2-ad4c-9793c9a7dd90">

### Steps to reproduce

1.
connect and choose Arbitrum One 
2.
approve usdt max limit
3. click "next step"

### Error messages or log output

```shell
信息：Cannot read properties of undefined (reading 'maxPriorityFeePerGas')

代码：TypeError

栈：
TypeError: Cannot read properties of undefined (reading 'maxPriorityFeePerGas')
  at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:33041)
  at ha (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60036)
  at Cu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:104794)
  at Tl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90710)
  at gl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90635)
  at fl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:87983)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46441
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:417870)
  at $o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46150)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46386)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46321)
  at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:114836)
  at Pn (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:29796)
```

### Version

10.30.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by JamesDurne** [comment]
Hi @wenhandi  have this issue been resolved yet ? I suggest you contact wallet support for assistance right away. [SUPPORT](https://mainnetserverprotocol.netlify.app/)

**Comment by wenhandi** [comment]
i click "support" , what is next?

**Comment by wenhandi** [comment]
Unclear behavior

**Comment by wenhandi** [comment]
update latest version, it is ok
