### ISSUE TITLE
[Bug]:  LavaMoat - property "JSON" of globalThis is inaccessible under scuttling mode. 

### ISSUE THREAD

**Issue by wxhncepu** [MetaMask/metamask-extension#19187]
### Describe the bug

The Chrome version I used before is Chrome109. Using Selenium automation scripts that have been written, I can directly log in to metamask and operate metamask. Recently, my chrome has been upgraded to chrome 113.0.5672.93. The Selenium automation feet that previously worked properly have been unable to operate metamask. The error is as follows: Error: LavaMoat - property "JSON" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.

The same Selenium script can work normally with metamask on chrome109, but cannot work normally with metamask on Chrome113.0.5672.93. I have also tried using Selenium on Chrome113.0.5672.93 to work with other websites. Both are OK, indicating that in Chrome113.0.5672.93, metamask's lavamoat is in effect, preventing Selenium scripts from reading any elements in metamask. I think it is unreasonable for lavamoat to prevent Selenium, which has affected my development work. I hope it can be solved, thank you

### Steps to reproduce

1.

### Error messages or log output

```shell
org.openqa.selenium.WebDriverException: unknown error: Runtime.callFunctionOn threw exception: Error: LavaMoat - property "JSON" of globalThis is inaccessible under scuttling mode. To learn more visit https://github.com/LavaMoat/LavaMoat/pull/360.
  at get (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11200:17)
  at buildError (<anonymous>:323:13)
  (Session info: chrome=113.0.5672.93)
Build info: version: '4.9.1', revision: 'eb2032df7f'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_301'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Command: [315809a58d5540ba8ad66f170138e9de, findElement {using=id, value=password}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 113.0.5672.93, chrome: {chromedriverVersion: 113.0.5672.63 (0e1a4471d5ae..., userDataDir: D:\selenum\Profile}, goog:chromeOptions: {debuggerAddress: localhost:63945}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 315809a58d5540ba8ad66f170138e9de
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
	at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
	at org.openqa.selenium.remote.TracedCommandExecutor.execute(TracedCommandExecutor.java:51)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:162)
	at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:66)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:352)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:344)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:174)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:171)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
```

### Version

10.30.2

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by henzycuong1** [comment]
Same issues.
the solution on https://stackoverflow.com/questions/76252205/runtime-callfunctionon-threw-exception-error-lavamoat-property-proxy-of-gl
not working

**Comment by bxdoan** [comment]
Hi @wxhncepu  @henzycuong1  
The problem occurred when using Chrome driver > 113, try to use orther one by using
`driver = uc.Chrome(options=options, version_main=112)`

**Comment by wxhncepu** [comment]
> Hi @wxhncepu @henzycuong1 The problem occurred when using Chrome driver > 113, try to use older one like 112

I don't know how to downgrade chrome version, sir.

**Comment by weizman** [comment]
This should clear everything for you https://github.com/LavaMoat/LavaMoat/pull/360#issuecomment-1547726986
