### ISSUE TITLE
[Bug]: Cannot destructure property 'balance' of '(0 , r.useSelector)(...)' as it is undefined.

### ISSUE THREAD

**Issue by rebwar** [MetaMask/metamask-extension#19247]
### Describe the bug

when I open the MM I got the error and can't access the MM
I do all things like disable MM and enable it again, I disable all of the extensions but MM but still got the error
here is the screenshot of the error 
[
<img width="638" alt="Screenshot 2023-05-21 at 5 13 18 PM" src="https://github.com/MetaMask/metamask-extension/assets/1691770/acd84fb5-442e-4600-82a9-cc0c019d746a">
<img width="355" alt="Screenshot 2023-05-21 at 5 12 48 PM" src="https://github.com/MetaMask/metamask-extension/assets/1691770/e41c962b-b867-4ca0-ac04-401be7751de4">
](url)

### Steps to reproduce

1.

### Error messages or log output

```shell
TypeError: Cannot destructure property 'balance' of '(0 , r.useSelector)(...)' as it is undefined.
  at n.useGasFeeErrors (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:2460)
  at n.useGasFeeInputs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:6033)
  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:208644)
  at ps (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:297700)
  at No (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:342458)
  at _l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:328374)
  at vl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:328299)
  at dl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:325647)
  at sl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:322415)
  at Kl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:350019)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:351218
  at pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:325995)
  at ef (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:351203)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:26:353120)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:57188
```

### Version

10.30.4

### Build type

None

### Browser

Microsoft Edge

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hello, @rebwar! Thanks for reporting! Could you please let me know what you remember doing before this error occurred? Thank you!

**Comment by rebwar** [comment]
it's happened just after I updated MM to 10.30.4 and before that, it's ok, as you see in the screenshot I think it's because of the Front UI.

**Comment by rebwar** [comment]
> Hello, @rebwar! Thanks for reporting! Could you please let me know what you remember doing before this error occurred? Thank you!


it's happened just after I updated MM to 10.30.4 and before that, it's ok, as you see in the screenshot I think it's because of the Front UI.

**Comment by spiritanand** [comment]
I would like to get started on fixing this. Can a maintainer please assign this issue to me.

**Comment by imtianx** [comment]
I have the same problem on `10.31.1`, how can I restore my wallet ?

**Comment by birminghamallen** [comment]
I fixed this error by right clicking MM in Brave browser, > manage extension > flip switch to OFF > flip switch to ON > error should be gone.

**Comment by albertolive** [comment]
It seems that this will be fixed by this PR https://github.com/MetaMask/metamask-extension/pull/20612 @DDDDDanica
