### ISSUE TITLE
[Bug]: Map maximum size exceeded

### ISSUE THREAD

**Issue by adapt7** [MetaMask/metamask-extension#19978]
### Describe the bug

Login to MetaMask, Expand view - wallet loads. After few seconds of inactivity getting this error:

```Message: Map maximum size exceeded

Code: RangeError

Stack:
RangeError: Map maximum size exceeded
  at Map.set (<anonymous>)
  at $n.set (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:26:134642)
  at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:26:160737)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:118104
  at va (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:60111)
  at Xa (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:67450)
  at Mu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:107220)
  at Al (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90901)
  at Rl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:90826)
  at El (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88166)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46516
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:416037)
  at Jo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46225)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46461)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46396)
  at _l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88460)
  at Object.notify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:225135)
  at t.notifyNestedSubs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:224702)
  at t.handleChangeWrapper (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:224770)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:404573)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:402646
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:405550)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-11.js:1:77108
  at Object.dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:402637)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-8.js:1:56792
  at o.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-11.js:1:119569)
  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:239415)
  at o.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:239819)
  at u.handleResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-11.js:1:120063)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:7:36325
  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:7:36395)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:250949)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:250764)
  at v.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:251578)
  at t.exports._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:147725)
  at v (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:264189)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:267373
  at b.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:267400)
  at e.exports.p (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:256149)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:7:36325
  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:7:36395)
  at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:250949)
  at y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:250764)
  at v.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:1:251578)
  at e.exports._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:55447)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:55294```

Started to happen after latest MetaMask update.

### Steps to reproduce

1. Login to MetaMask
2. Expand view - wallet loads
3. After few seconds of inactivity getting this error: Map maximum size exceeded

Repeats all the time.

### Error messages or log output

_No response_

### Version

10.33.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Hardware wallet

_No response_

### Additional context

All worked perfectly before the latest MetaMask update.

**Comment by anaamolnar** [comment]
Hey, @adapt7. Thanks for reporting! Could you please manually update to 10.34.0 and let me know if this error still occurs?  Was this a one-time occurrence, or could you reproduce it consistently? Thank you!

**Comment by danjm** [comment]
My guess is that this was resolved with https://github.com/MetaMask/metamask-extension/pull/19993

If it is not still reproducible, then I think we can conclude that fixed it
