### ISSUE TITLE
[Bug]: Unable to connect to websites using MetaMask

### ISSUE THREAD

**Issue by Natashkinsasha** [MetaMask/metamask-extension#20010]
### Describe the bug

Issue Description:
I have been using MetaMask successfully, but recently I encountered an issue where I am unable to connect to any website using MetaMask. I have tried multiple websites, but the problem persists. 

Please let me know if there are any additional details or steps to reproduce the issue.

### Steps to reproduce

1.Open MetaMask extension.
2.Visit any website that requires MetaMask integration.
3.Observe the error messages mentioned above.

Expected Behavior:
I should be able to connect to websites using MetaMask without any errors.

### Error messages or log output

```shell
"Uncaught (in promise) Error: No window with id: 837975491.
at et.r (inpage.js:2:2567951)
at r.throw (<anonymous>)
at i (inpage.js:2:2568069)"

After reloading the page, the error message changes to:
"Uncaught (in promise) Error: Request of type 'PUBLIC_switchEthereumChain' already pending for origin https://etherscan.io/. Please wait.
at et.r (inpage.js:2:2567951)
at r.throw (<anonymous>)
at i (inpage.js:2:2568069)"
```

### Version

10.33.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by v-goyal** [comment]
can you provide a few more details? 
 - Chrome version
 -  MacOS version
 - Any specific websites where you are seeing the issue? 
 - Also, does it work on other browsers like FireFox?

**Comment by danjm** [comment]
@Natashkinsasha Are you using other wallets as well? The problems you describe are very similar to reports we've seen from other users with multiple wallets installed. If so, you can try resolving by going to chrome://extensions and disabling other wallet extensions
