### ISSUE TITLE
[Bug]: Submitting an incorrect password throws an unhandled rejection in the show private key flow

### ISSUE THREAD

**Issue by PeterYinusa** [MetaMask/metamask-extension#20902]
### Describe the bug

https://github.com/MetaMask/metamask-extension/assets/53189696/679a3fb6-af5a-43d3-a7af-d6f279b43cac

### Steps to reproduce

1. log in to the extension
2. click the account menu icon
3. click the ellipsis icon to the right of the first account in the account list
4. select the Account Details menu item
5. click the Show Private Key button
6. enter an incorrect password, click Confirm
7. wait a few seconds

### Error messages or log output

Error
```shell
sentry-install.js:1 Error in verifying password.
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
(anonymous) @ ui-12.js:1
handleResponse @ ui-12.js:1
(anonymous) @ common-3.js:7
s.emit @ common-3.js:7
w @ common-5.js:3
_ @ common-5.js:3
y.push @ common-5.js:3
_write @ common-4.js:26
y @ common-5.js:3
(anonymous) @ common-5.js:3
g.write @ common-5.js:3
m @ common-5.js:3
(anonymous) @ common-3.js:7
s.emit @ common-3.js:7
w @ common-5.js:3
_ @ common-5.js:3
y.push @ common-5.js:3
_onMessage @ common-3.js:16
(anonymous) @ common-3.js:16
```

Unhandled exception
```shell
sentry-install.js:1 SES_UNHANDLED_REJECTION: (Error#6)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:7114
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
```

```shell
sentry-install.js:1 Error#6: Incorrect password
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:7075
logSubErrors @ runtime-lavamoat.js:7018
error @ runtime-lavamoat.js:7116
handleRejection @ runtime-lavamoat.js:7415
finalizeDroppedPromise @ runtime-lavamoat.js:7243
sentry-install.js:1   at c (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/common-0.js:1:129596)
  at async Object.o [as decrypt] (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/common-0.js:1:129365)
  at async T.verifyPassword (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/background-0.js:13:101987)
  at async Ke.verifyPassword (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/background-4.js:1:209385)
  at async s.<anonymous> (chrome-extension://cmbgfohndfdmokhhionelhibkgpkmllf/background-4.js:1:56518)
```

### Version

11.1.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by gantunesr** [comment]
@PeterYinusa is this a regression? I see that this error log has been in the codebase for at least 3 years.

https://github.com/MetaMask/metamask-extension/blob/ce14c9d87a019045550411ed5631c1ee3c71270e/ui/store/actions.ts#L2581-L2582

**Comment by PeterYinusa** [comment]
Yes, it's not a new issue. I labelled it with `regression-production` to indicate this, as opposed to `regression-rc`. The unhandled exception is specifically the `Incorrect password` error
