### ISSUE TITLE
[Bug]: Error prompt when cancelling a transaction 

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#21261]
### Describe the bug

Error is prompted in the console when attempting to cancel a transaction.

### Expected behavior

No errors are shown.

### Screenshots

https://github.com/MetaMask/metamask-extension/assets/120041701/d371c902-b0bb-4e52-b152-549f1a487375

### Steps to reproduce

1. Open MetaMask and enter your password
2. Switch to a test network: e.g. Goerli
3. Proceed to the send flow
4. Send 0.1 ETH to an address: e.g. 0x3D0b9b4056D86f8d9889B2C8e26FFCedC62D3036
5. Edit the gas settings in Market --> Advanced: Max base fee to 0.0000001 and Priority Fee to 0.0000001
6. Confirm the transaction
7. Cancel transaction

### Error messages or log output

```shell
Error in event handler: TypeError: Cannot destructure property 'id' of 'e[(e.length - 1)]' as it is undefined.
  at chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/ui-12.js:1:8747
  at s.handleResponse (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/ui-12.js:1:81072)
  at a.emit (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-3.js:18:111667)
  at v (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:1:293993)
  at w (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:1:293808)
  at y.push (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:1:294622)
  at t.exports._write (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:1:122084)
  at y (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:1:307233)
  at chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:1:310417
  at g.write (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:1:310444)
  at i.h (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:3:107261)
  at a.emit (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-3.js:18:111667)
  at S (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:3:102066)
  at x (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:3:101896)
  at T.push (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-5.js:3:102683)
  at i._onMessage (chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-3.js:18:115216)
  at chrome-extension://dofbkecmjglnaakpmejcnfefopfjickf/common-3.js:18:115012
```

### Version

11.3.0

### Build type

None

### Browser

Chrome, Firefox

### Operating system

MacOS

**Comment by danjm** [comment]
fixed by https://github.com/MetaMask/metamask-extension/pull/21269
