### ISSUE TITLE
Improve error message when Infura returns a 50x error.

### ISSUE THREAD

**Issue by somish** [MetaMask/metamask-extension#2131]
Hi,
We have been deploying our contracts on Rinkeby Testnet using solidity browser along with metamask for quite some time now. Since a week, we have been facing an issue as follows:

"callback contain no result Error: SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at asyncify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:71632:34)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10206:27
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10439:12
    at nextTask (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:70593:14)
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:70600:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10537:16"

The same contract is compiling on Ropsten but not on Rinkeby. Earlier the same contract used to compile on Rinkeby as well. Could you please help us identify the problem.

Thanks

**Comment by flyswatter** [comment]
Hi, sorry for the confusing error message. We usually see this error when we get a timeout error from our backend (Infura). It's possible Rinkeby's traffic spiked suddenly. I've contacted Infura, who will probably increase the Rinkeby bandwidth they host.

If you hit this error in the future, you can always point your MetaMask at a local Rinkeby node, and also I'll leave this issue open for making this error more readable. (Renaming title for that).

**Comment by bdresser** [comment]
Closing due to inactivity - if this is still relevant, feel free to open a new issue.
