### ISSUE TITLE
Failed transaction, insufficient funds, went through the next day when wallet happened to have sufficient funds

### ISSUE THREAD

**Issue by nharlow89** [MetaMask/metamask-extension#2137]
**Expected Behavior**
Failed transaction due to insufficient funds is never resubmitted or "pending".

**Actual Behavior**
Somehow, once sufficient funds arrived in wallet a day later, the transaction actually went through!

**Browser Used**
Chrome Version 60.0.3112.113

**Operating System**
Mac OS 10.12.4

I arrived at this issue by clicking "send" on a transaction twice, the first click gave no UI feedback. The first transaction went through fine, the second transaction (a duplicate of the first) failed to go through as there were insufficient funds.
 
![image](https://user-images.githubusercontent.com/6100067/30678562-f5622e8c-9e47-11e7-9b61-ff80e767a537.png)
TX: [0x80c779c6e99d97499588ca61cfb6efc940a276db3361ba8615de8e6245897cb4](https://etherscan.io/tx/0x80c779c6e99d97499588ca61cfb6efc940a276db3361ba8615de8e6245897cb4)

As you can see, the transaction failed (according to Metamask extension) on Sept 19, but went through Sept 20. I am not sure if this is a Metamask issue, or if this transaction remained "pending" on the ethereum network and was picked up later when the wallet happened to have sufficient funds. Relevant history item in state log:
```
{
    "id": 5394431615336104,
    "time": 1505833612621,
    "status": "failed",
    "metamaskNetworkId": "1",
    "txParams": {
        "from": "0x5b0840305b81aad13506bc9a6a0df14cc234dc9f",
        "to": "0x918c12eaf56dac02c0500840ded69b064994cdba",
        "value": "0x3782dace9d900000",
        "gasPrice": "0xdf8475800",
        "gas": "0x7b0d",
        "nonce": "0x09",
        "chainId": 1
    },
    "gasLimitSpecified": false,
    "estimatedGas": "5209",
    "nonceDetails": {
        "params": {
            "highestLocalNonce": 0,
            "highestSuggested": 8,
            "nextNetworkNonce": 8
        },
        "local": {
            "name": "local",
            "nonce": 9,
            "details": {
                "startPoint": 8,
                "highest": 9
            }
        },
        "network": {
            "name": "network",
            "nonce": 8,
            "details": {
                "baseCount": 8
            }
        }
    },
    "rawTx": "0xf86c09850df8475800827b0d94918c12eaf56dac02c0500840ded69b064994cdba883782dace9d9000008026a0d233daccd00aa99f91aea607c7d6f6d6b0a8ef1aaa3fcdb910ae5c8328e4c3d2a06e08839856440d006b939370e0ef7d45869c9b01eac0694a9ef2ea22eac184b6",
    "hash": "0x80c779c6e99d97499588ca61cfb6efc940a276db3361ba8615de8e6245897cb4",
    "retryCount": 1,
    "err": {
        "message": "Error: [ethjs-rpc] rpc error with payload {\"id\":3305388020025,\"jsonrpc\":\"2.0\",\"params\":[\"0xf86c09850df8475800827b0d94918c12eaf56dac02c0500840ded69b064994cdba883782dace9d9000008026a0d233daccd00aa99f91aea607c7d6f6d6b0a8ef1aaa3fcdb910ae5c8328e4c3d2a06e08839856440d006b939370e0ef7d45869c9b01eac0694a9ef2ea22eac184b6\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value",
        "stack": "Error: [ethjs-rpc] rpc error with payload {\"id\":3305388020025,\"jsonrpc\":\"2.0\",\"params\":[\"0xf86c09850df8475800827b0d94918c12eaf56dac02c0500840ded69b064994cdba883782dace9d9000008026a0d233daccd00aa99f91aea607c7d6f6d6b0a8ef1aaa3fcdb910ae5c8328e4c3d2a06e08839856440d006b939370e0ef7d45869c9b01eac0694a9ef2ea22eac184b6\"],\"method\":\"eth_sendRawTransaction\"} Error: insufficient funds for gas * price + value\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:48797:26\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:69942:9\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10521:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10401:25)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10391:17)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10537:16\n    at resultObj.id (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:69924:9)\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10612:16\n    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10406:17)\n    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:10391:17)"
    }
},
```

**Comment by flyswatter** [comment]
Sorry this bit you, some very specific user behavior could make this happen. There are kindof two issues here, both of which we're aware of and have pending improvements for:

- Currently MetaMask will allow you to send multiple transactions that would spend the same funds, if you send the subsequent before the previous transactions are mined. #1746 This would mean you signed two transactions in a row for the same funds (sometimes people do this thinking it will speed up the first one. It won't.)
- A transaction can be broadcast once before being marked as failed if it is later an invalid transaction. #2115

Together, it means you could send a transaction, get impatient, send another one, the first one could get mined, then marking the second one as failed, when actually it's still a valid signed transaction.

We have patches coming soon to alleviate both of those issues:

- Subtract the values of pending transactions from the account balance when disallowing a new transaction for low balance. #2094 
- Do not mark a transaction as failed if it has been broadcast successfully once, unless there is an on-chain error. #2121

Since these are accounted for, I'll just close this issue and say sorry you went through this.

**Comment by nharlow89** [comment]
Thank you @flyswatter for detailed explanation and the relevant issues. Glad to hear this is already being fixed!

**Comment by absan86** [comment]
![2](https://user-images.githubusercontent.com/35181500/34645587-b66af24a-f31f-11e7-8837-5acf1d0d8e89.jpg)
so can i please get instruction on how to fix it?
![1](https://user-images.githubusercontent.com/35181500/34645586-b427ebb4-f31f-11e7-95a5-2e9b5895c097.jpg)

**Comment by absan86** [comment]
please help, what should i do?

**Comment by danfinlay** [comment]
Reopening because we reverted the patch that fixed this.

**Comment by absan86** [comment]
Thank for the update but is there anything I need to do from my end?

**Comment by danfinlay** [comment]
The way to avoid this bug is simple:

Don't send multiple transactions worth more than your account holds, faster than a block can be mined. We can't currently validate that properly and reject the second transaction automatically.

Just be aware of what you have, and if you get impatient, use the "re-submit with higher gas price" button, don't send another transaction.

**Comment by absan86** [comment]
I used the red link underneath that said resend with higher gas and that what got me where I’m, but my question is would the other user get the 3 eth or is it lost?

**Comment by danfinlay** [comment]
Not clear what’s happening for you. Please submit a detailed explanation to support@metamask.io

**Comment by bdresser** [comment]
Closing due to inactivity - if this is still relevant, feel free to open a new issue.
