### ISSUE TITLE
 Error: [number-to-bn] while converting number "0xnull" to BN.js instance

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#2141]
```
Error in event handler for (unknown): Error: [number-to-bn] while converting number "0xnull" to BN.js instance, error: invalid number value. Value must be an integer, hex string, BN or BigNumber instance. Note, decimals are not supported.
    at numberToBN (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:48453:9)
    at TransactionListItem.render (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:90913:32)
    at chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:57450:21
    at measureLifeCyclePerf (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:56730:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:57449:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:57476:32)
    at ReactCompositeComponentWrapper.performInitialMount (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:57016:30)
    at ReactCompositeComponentWrapper.mountComponent (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:56912:21)
    at Object.mountComponent (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:63284:35)
    at ReactDOMComponent.mountChildren (chrome-extension://ieiacihbmmkaocpbnlcohcjncikcfeej/scripts/popup.js:62661:44)
```

**Comment by kumavis** [comment]
This prevented the UI from loading

**Comment by Zanibas** [comment]
Needs a migration
