### ISSUE TITLE
Fix flaky test "makes a call to 4byte when the setting is on"

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#21491]
Frequency: **Medium** (3 times in the develop branch over the last 4 days)

Test file: `test/e2e/tests/4byte-directory.spec.js`
Test name: `makes a call to 4byte when the setting is on`
Test error message:
```
    message: 'A new host not contained in the privacy-snapshot received a network\n' +
      '           request during test execution. Please update the privacy-snapshot\n' +
      '           file by passing the --update-privacy-snapshot option to the test\n' +
      '           command or add the new hosts to the snapshot manually.\n' +
      '\n' +
      '           New hosts found: configuration.dev.metamask-institutional.io.\n' +
      'Error: A new host not contained in the privacy-snapshot received a network\n' +
      '           request during test execution. Please update the privacy-snapshot\n' +
      '           file by passing the --update-privacy-snapshot option to the test\n' +
      '           command or add the new hosts to the snapshot manually.\n' +
      '\n' +
      '           New hosts found: configuration.dev.metamask-institutional.io.\n' +
      '    at withFixtures (test/e2e/helpers.js:152:23)\n' +
      '    at process.openDapp (node:internal/process/task_queues:95:5)\n' +
      '    at Context.<anonymous> (test/e2e/tests/4byte-directory.spec.js:5:3)',
```

Failed build: [link](https://circleci.com/gh/MetaMask/metamask-extension/1875701).

**Comment by chloeYue** [comment]
close this ticket as the test is not flaky anymore
