### ISSUE TITLE
Fix flaky test "will detect if eth_sign is disabled"

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#21492]
Frequency: **Medium** (3 times in the develop branch over the last 4 days)

Test file: `test/e2e/tests/eth-sign.spec.js`
Test name: `will detect if eth_sign is disabled`
Test error message:
```
    message: 'A new host not contained in the privacy-snapshot received a network\n' +
      '           request during test execution. Please update the privacy-snapshot\n' +
      '           file by passing the --update-privacy-snapshot option to the test\n' +
      '           command or add the new hosts to the snapshot manually.\n' +
      '\n' +
      '           New hosts found: configuration.dev.metamask-institutional.io.\n' +
      'Error: A new host not contained in the privacy-snapshot received a network\n' +
      '           request during test execution. Please update the privacy-snapshot\n' +
      '           file by passing the --update-privacy-snapshot option to the test\n' +
      '           command or add the new hosts to the snapshot manually.\n' +
      '\n' +
      '           New hosts found: configuration.dev.metamask-institutional.io.\n' +
      '    at withFixtures (test/e2e/helpers.js:152:23)\n' +
      '    at process.withFixtures (node:internal/process/task_queues:95:5)\n' +
      '    at Context.<anonymous> (test/e2e/tests/eth-sign.spec.js:3:3)',
```

Failed build: [link](https://circleci.com/gh/MetaMask/metamask-extension/1875701).

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
