### ISSUE TITLE
Fix flaky test "executes a eth_accounts json rpc call"

### ISSUE THREAD

**Issue by pedronfigueiredo** [MetaMask/metamask-extension#21490]
Frequency: **Medium** (3 times in the develop branch over the last 4 days)

Test file: `test/e2e/json-rpc/eth_accounts.spec.js`
Test name: `executes a eth_accounts json rpc call`
Test error message:
```
    message: 'A new host not contained in the privacy-snapshot received a network\n' +
      '           request during test execution. Please update the privacy-snapshot\n' +
      '           file by passing the --update-privacy-snapshot option to the test\n' +
      '           command or add the new hosts to the snapshot manually.\n' +
      '\n' +
      '           New hosts found: configuration.dev.metamask-institutional.io.\n' +
      'Error: A new host not contained in the privacy-snapshot received a network\n' +
      '           request during test execution. Please update the privacy-snapshot\n' +
      '           file by passing the --update-privacy-snapshot option to the test\n' +
      '           command or add the new hosts to the snapshot manually.\n' +
      '\n' +
      '           New hosts found: configuration.dev.metamask-institutional.io.\n' +
      '    at withFixtures (test/e2e/helpers.js:152:23)\n' +
      '    at process.withFixtures (node:internal/process/task_queues:95:5)\n' +
      '    at Context.<anonymous> (test/e2e/json-rpc/eth_accounts.spec.js:2:9)',
```

Failed build: [link](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/60306/workflows/64832255-8f79-4ff0-8399-e0ec5e7570b6/jobs/1875700).

**Comment by chloeYue** [comment]
Close this ticket as the test is not flaky anymore
