### ISSUE TITLE
[Bug]: Can't fetch data

### ISSUE THREAD

**Issue by orangeqq** [MetaMask/metamask-extension#21515]
### Describe the bug

From 6hours ago.
Can't get the latest token balance.
Always showing [Loading tokens...]
Not showing transactions confirmation window.

### Steps to reproduce

1. Click the Metamask icon on the top right sight of Chrome

### Error messages or log output

```shell
(Error#31)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
error @ runtime-lavamoat.js:6830
error @ runtime-lavamoat.js:11748
_synchronize @ background-2.js:17
 Error#31: PollingBlockTracker - encountered an error while attempting to update latest block:
TypeError: Failed to fetch
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:336722
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11748:22
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11748:22
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11748:22
  at h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:5832)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:7019
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37941
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36950
  at new Promise (<anonymous>)
  at a._runMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36607)
  at a._runAllMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36513)
  at a._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36302)
  at a._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36146)
  at a.handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:35093)
  at c.sendAsync (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:91703)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:86657
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:91640
  at new Promise (<anonymous>)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:91287
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:91967
  at h._fetchLatestBlock (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:86673)
  at h._updateLatestBlock (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:86408)
  at h._synchronize (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:85927)
e.<computed> @ sentry-install.js:1
(anonymous) @ sentry-install.js:1
logError @ runtime-lavamoat.js:6791
logSubErrors @ runtime-lavamoat.js:6734
error @ runtime-lavamoat.js:6832
error @ runtime-lavamoat.js:11748
_synchronize @ background-2.js:17
 TypeError: Failed to fetch
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:336722
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11748:22
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11748:22
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11748:22
  at h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:5832)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:7019
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37941
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36950
  at new Promise (<anonymous>)
  at a._runMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36607)
  at a._runAllMiddleware (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36513)
  at a._processRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36302)
  at a._handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:36146)
  at a.handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:35093)
  at c.sendAsync (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:91703)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:86657
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:91640
  at new Promise (<anonymous>)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:91287
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/sentry-install.js:1:693)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:91967
  at h._fetchLatestBlock (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:86673)
  at h._updateLatestBlock (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:86408)
  at h._synchronize (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:85927)
  at h._synchronize (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:17:86071)
```

### Version

MetaMask Version 11.2.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by ZbrancaI** [comment]
Hey @orangeqq! Thank you for reporting the issue! 

Does this issue occur only on a particular Network? 

Also, I recommend updating the extension to the latest version (11.3.0).
(back up your SRP & any associated PK before proceeding with this action)

**Comment by orangeqq** [comment]
@ZbrancaI Thank you for your replay, sir.
This issue occur on any network.
I updated the Metamask extension 11.2.0 to 11.3.0, and the situation changed.
It stops at the fox logo with a loading mark rotating under it.
The error logs are still the same.

**Comment by ZbrancaI** [comment]
Hey @orangeqq! 

I see! Could you please provide a screen recording of when you're entering the app and the issue occurs?

Please let me know if you have access to your SRP/PK. And make sure to have your browser up to date!

**Comment by orangeqq** [comment]
@ZbrancaI 
After I removed the extension and reinstalled it, everything goes well now.
Thanks.

**Comment by ZbrancaI** [comment]
Hello @orangeqq!

Great to hear that the issue was solved! Then I will close this issue. 

Thank you!
