### ISSUE TITLE
[Bug]: "TypeError: this.codeReader.stop is not a function" - When clicking on Grey area under "Webcam not found" popup

### ISSUE THREAD

**Issue by emanuelb** [MetaMask/metamask-extension#21900]
### Describe the bug

Metamask crash instead of "back/cancel" operation

### Expected behavior

No crash, the effect is the same as cancel

### Screenshots/Recordings

![MetaMaskBugQRScan1](https://github.com/MetaMask/metamask-extension/assets/1792055/3a725e94-8ce6-48e5-bff5-4a44d643ef8a)
![MetaMaskBugQRScan2](https://github.com/MetaMask/metamask-extension/assets/1792055/74ddde46-0f85-423c-a1df-96afdccec97f)

### Steps to reproduce

1. Click MetaMask
2. Click Send
3. Click QR Icon
4. it shows "Webcam not found" (it was tested on Chromium on Linux in virtual machine)
5. Click on Grey area below the popup (under "Cancel" and "Try again" buttons) to have the same effect as "Cancel"

### Error messages or log output

```shell
> MetaMask encountered an error
Try again by closing and reopening the popup, or contact support here.
Error details
Message: this.codeReader.stop is not a function
Code: TypeError
Stack:
TypeError: this.codeReader.stop is not a function
  at _.teardownCodeReader (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:200617)
  at _.componentWillUnmount (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:200517)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:79022
  at Tu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:79063)
  at Ou (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:80824)
  at Ds (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:100114)
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:491157)
  at Qo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46225)
  at Ns (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:97994)
  at xs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:88366)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46516
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:491157)
  at Qo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46225)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46461)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:46396)
  at gs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:84932)
  at Object.enqueueSetState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:51177)
  at w.setState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:470338)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:169797
  at HTMLDivElement.n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-5.js:1:169512)
```

### Version

11.4.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by anaamolnar** [comment]
Hello, @emanuelb. Thanks for reporting! Do you still experience this issue on 11.5.1?

**Comment by emanuelb** [comment]
> Hello, @emanuelb. Thanks for reporting! Do you still experience this issue on 11.5.1?

Yes, Ive updated to 11.5.1, issue still apply, looks like the fix should add more error handling in: https://github.com/MetaMask/metamask-extension/blob/a341f2da064eb9744e9061b61ebdbbd28452f0e9/ui/components/app/modals/qr-scanner/qr-scanner.component.js#L107-L119

**Comment by Akaryatrh** [comment]
@emanuelb As of today, I can not replicate. Please see below recording:
https://github.com/user-attachments/assets/c9f114aa-47a2-4892-9827-6af48c33539d

- Ubuntu 24.04 (virtualized with UTM 4.5.3)
- Chromium 126.0.6478.126 (Official Build) snap (64-bit) 
- MM extension 11.16.14
