### ISSUE TITLE
[Bug]: The scan button next to the receiving address, when tapped to scan the QR code, triggers an error.

### ISSUE THREAD

**Issue by Esme-Keystone** [MetaMask/metamask-extension#22160]
### Describe the bug

Hope you have a great weekend, MetaMask team!
We have encountered a general issue while using the MetaMask extension. The scan button next to the receiving address, when tapped to scan the QR code, triggers an error.
Here is some information that might be helpful -
TypeError: this.codeReader.stop is not a function
  at _.teardownCodeReader (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:272453)
  at _.componentWillUnmount (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:272353)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:176110
  at Ss (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:176151)
  at Os (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:177912)
  at Bl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:197202)
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:197381)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:143313)
  at Nl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:195082)
  at Tl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:185454)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:143604
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:197381)
  at Zo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:143313)
  at ti (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:143549)
  at ei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:143484)
  at bl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:182020)
  at Object.enqueueSetState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:148265)
  at v.setState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:176562)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:241634
  at HTMLDivElement.n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-3.js:1:241349)

### Expected behavior

Able to detect the QR code and read it

### Screenshots/Recordings

https://github.com/MetaMask/metamask-extension/assets/7900773/6121fa5f-4c4e-4bbe-9f7c-b75299fa2044

_No response_

### Steps to reproduce

1. Open the MetaMask extension
2. Tap [Send] > scan button to fill the receiving address
3. Use ETH address on Keystone to let MetaMask scan it

### Version

11.5.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

Keystone

**Comment by AlexJupiter** [comment]
While we're fixing this it would also be ideal to update the copy as per @coreyjanssen's suggestion:

> *Something went wrong*
> We couldn't access your camera. Please give it another try.
