### ISSUE TITLE
[Bug]: Console warnings when sending async with SSK 1.1.1 snap account

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/metamask-extension#22864]
### Describe the bug

When I confirm a tx in extension with a snap account that is using the async flow, a console error is presented.  The tx is able to be signed and broadcast successfully even with this error.

Observed in chrome 117.0.5938.92
Initially in 11.10RC, then confirmed in 11.9 and 11.7.5
[SSK](https://metamask.github.io/snap-simple-keyring/1.1.1/) v1.1.1 with `Use Synchronous Approval` toggle turned off

### Expected behavior

Account snap redirect should not generate an error

### Screenshots/Recordings

https://recordit.co/nHqxwBvS9u
![Screenshot 2024-02-07 at 6 27 47 PM](https://github.com/MetaMask/metamask-extension/assets/32695229/222590d2-3e9d-450c-a7bc-de4eed4362ae)

### Steps to reproduce

1. Set up a wallet
2. Connect and install SSK 1.1.1
3. Create account and fund, or import an account into SSK that already has testnet balance
4. Disable Synchronous Approval in SSK by turning the toggle off
5. Initiate a send tx from extension
6. after tapping `Next` and `Confirm` error will appear

### Error messages or log output

```shell
Invalid URL passed into snap-keyring: Error: Action missing from allow list: PhishingController:testOrigin
  at RestrictedControllerMessenger.call (RestrictedControllerMessenger.js:117:1)
  at snap-keyring.ts:101:42
  at isBlockedUrl (isBlockedUrl.ts:28:12)
  at async Object.redirectUser (snap-keyring.ts:93:29)
  at async SnapKeyring._SnapKeyring_submitRequest (SnapKeyring.js:497:1)
  at async SnapKeyring.signTransaction (SnapKeyring.js:150:1)
  at async KeyringController.signTransaction (KeyringController.js:348:1)
isBlockedUrl @ isBlockedUrl.ts:30
await in isBlockedUrl (async)
redirectUser @ snap-keyring.ts:93
_SnapKeyring_submitRequest @ SnapKeyring.js:497
await in _SnapKeyring_submitRequest (async)
signTransaction @ SnapKeyring.js:150
signTransaction @ KeyringController.js:348
await in signTransaction (async)
signTransaction @ KeyringController.js:582
sign @ metamask-controller.js:1429
(anonymous) @ TransactionController.js:1551
(anonymous) @ TransactionController.js:8
__awaiter @ TransactionController.js:4
signTransaction @ TransactionController.js:1547
(anonymous) @ TransactionController.js:1193
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
(anonymous) @ TransactionController.js:8
__awaiter @ TransactionController.js:4
approveTransaction @ TransactionController.js:1159
(anonymous) @ TransactionController.js:1112
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
(anonymous) @ TransactionController.js:8
__awaiter @ TransactionController.js:4
processApproval @ TransactionController.js:1079
(anonymous) @ TransactionController.js:319
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
fulfilled @ TransactionController.js:5
Promise.then (async)
step @ TransactionController.js:7
(anonymous) @ TransactionController.js:8
__awaiter @ TransactionController.js:4
addTransaction @ TransactionController.js:264
addTransaction @ metamask-controller.js:3914
(anonymous) @ createMetaRPCHandler.js:23
emit @ events.js:153
addChunk @ _stream_readable.js:291
readableAddChunk @ _stream_readable.js:278
Readable.push @ _stream_readable.js:245
_write @ index.js:68
doWrite @ _stream_writable.js:428
writeOrBuffer @ _stream_writable.js:417
Writable.write @ _stream_writable.js:334
ondata @ readable.js:662
emit @ events.js:153
addChunk @ readable.js:278
readableAddChunk @ readable.js:255
Readable.push @ readable.js:201
_onMessage @ index.js:30
(anonymous) @ index.js:12
stream-utils.js:22 Error: premature close
  at onclosenexttick (index.js:53:1)
  at Item.run (browser.js:153:1)
  at drainQueue (browser.js:123:1)
(anonymous) @ stream-utils.js:22
(anonymous) @ index.js:75
f @ once.js:25
(anonymous) @ index.js:31
f @ once.js:25
onclosenexttick @ index.js:54
Item.run @ browser.js:153
drainQueue @ browser.js:123
setTimeout (async)
runTimeout @ browser.js:41
process.nextTick @ browser.js:143
onDestroy @ destroy.js:88
Readable._destroy @ readable.js:190
_destroy @ destroy.js:92
destroy @ destroy.js:62
_onDisconnect @ index.js:38
(anonymous) @ index.js:13
createLoggerMiddleware.js:24 RPC (https://metamask.github.io): {method: 'metamask_getProviderState', jsonrpc: '2.0', id: 281436282, origin: 'https://metamask.github.io', networkClientId: 'sepolia', …} -> {id: 281436282, jsonrpc: '2.0', result: {…}}
createLoggerMiddleware.js:24 RPC (https://metamask.github.io): {jsonrpc: '2.0', id: 281436283, method: 'metamask_sendDomainMetadata', params: {…}, origin: 'https://metamask.github.io', …} -> {id: 281436283, jsonrpc: '2.0', result: true}
createLoggerMiddleware.js:24 RPC (https://metamask.github.io): {method: 'wallet_getSnaps', jsonrpc: '2.0', id: 281436284, origin: 'https://metamask.github.io', networkClientId: 'sepolia', …} -> {id: 281436284, jsonrpc: '2.0', result: {…}}
createLoggerMiddleware.js:24 RPC (https://metamask.github.io): {method: 'wallet_invokeKeyring', params: {…}, jsonrpc: '2.0', id: 281436285, origin: 'https://metamask.github.io', …} -> {id: 281436285, jsonrpc: '2.0', result: Array(1)}
createLoggerMiddleware.js:24 RPC (https://metamask.github.io): {method: 'wallet_invokeKeyring', params: {…}, jsonrpc: '2.0', id: 281436286, origin: 'https://metamask.github.io', …} -> {id: 281436286, jsonrpc: '2.0', result: Array(1)}
createLoggerMiddleware.js:24 RPC (https://metamask.github.io): {method: 'wallet_snap', params: {…}, jsonrpc: '2.0', id: 281436287, origin: 'https://metamask.github.io', …} -> {id: 281436287, jsonrpc: '2.0', result: false}
createLoggerMiddleware.js:24 RPC (https://metamask.github.io): {method: 'wallet_invokeKeyring', params: {…}, jsonrpc: '2.0', id: 281436288, origin: 'https://metamask.github.io', …} -> {id: 281436288, jsonrpc: '2.0', result: Array(1)}
createLoggerMiddleware.js:24 RPC (npm:@metamask/snap-simple-keyring-snap): {method: 'snap_manageState', params: {…}, jsonrpc: '2.0', id: 2709052614, origin: 'npm:@metamask/snap-simple-keyring-snap', …} -> {id: 2709052614, jsonrpc: '2.0', result: null}
createLoggerMiddleware.js:24 RPC (npm:@metamask/snap-simple-keyring-snap): {method: 'snap_manageAccounts', params: {…}, jsonrpc: '2.0', id: 2709052615, origin: 'npm:@metamask/snap-simple-keyring-snap', …} -> {id: 2709052615, jsonrpc: '2.0', result: null}
```

### Version

11.7.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by plasmacorral** [comment]
Closing as a duplicate of https://github.com/MetaMask/accounts-planning/issues/159
