### ISSUE TITLE
[Bug]: Can't access networks settings `MetaMask encountered an error`

### ISSUE THREAD

**Issue by pcaversaccio** [MetaMask/metamask-extension#23084]
### Describe the bug

Since I updated to the latest MetaMask extension version `11.10.0`, whenever I click on the networks tab in the settings it throws with:

```console
MetaMask encountered an error` Message: Cannot read properties of undefined (reading 'toLowerCase')
Code: TypeError
```

### Expected behavior

It should not throw.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/25297591/d49feb99-7932-47e9-ae02-74f18fe1ffd0)

### Steps to reproduce

1. Go to Settings
2. Click on Networks

### Error messages or log output

```shell
Error details
Message: Cannot read properties of undefined (reading 'toLowerCase')

Code: TypeError

Stack:
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:13:10724
  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:13:11125)
  at r.blo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-0.js:13:11194)
  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:2822)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:246078)
  at Pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:291005)
  at Iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276868)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276793)
  at Eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274133)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232483
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:221729)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
  at eo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232428)
  at Zi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232363)
  at se (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:301255)
  at Dn (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:216157)
  at Pn (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:217114)
  at An (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:216402)
```
```


### Version

11.10.0

### Build type

None

### Browser

Microsoft Edge

### Operating system

Windows, Linux

### Hardware wallet

_No response_

### Additional context

I have around 80+ EVM chains configured, i.e. a lot of configurations. I restarted the browser, I tried using it in private mode. Always the same bug.

### Severity

_No response_

**Comment by danjm** [comment]
@pcaversaccio Thanks for the report, we are working on fixing this

**Comment by danjm** [comment]
@pcaversaccio what version of MetaMask were you using before you updated to v11.10.0?

**Comment by pcaversaccio** [comment]
> @pcaversaccio what version of MetaMask were you using before you updated to v11.10.0?

I'm not really sure anymore, but I updated  to `11.9.0` one week ago. But I don't know if there was an automatic updates to the `11.9.x` versions in the meantime.

**Comment by pcaversaccio** [comment]
> @pcaversaccio, I'm fixing the bug in the PR linked above. I believe 4 chains are affected. If possible, could you verify that one of these chains was in your list?
> 
> * 648 (0x288) - Endurance Smart Chain
> * 1234 (0x4d2) - Step Network
> * 106 (0x6a) - Velas EVM
> * 1261120 (0x133e40) - zKatana

Endurance 

![image](https://github.com/MetaMask/metamask-extension/assets/25297591/698e861f-1b3c-49a9-b3f7-4792698d5446)
