### ISSUE TITLE
[Bug]: Failed to make changes to the network. MetaMask 11.10.0 for Chrome

### ISSUE THREAD

**Issue by asawin247** [MetaMask/metamask-extension#23146]
### Describe the bug

Failed to make changes to the network. MetaMask 11.10.0 for Chrome

### Expected behavior

MetaMask encountered an error page.

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/101303317/268a2c5f-ef13-4dc8-a51d-dffedd5f66c7)

### Steps to reproduce

1.Metamask 2.Setting 3.Network

### Error messages or log output

```shell
Error details
Message: Cannot read properties of undefined (reading 'slice')

Code: TypeError

Stack:
TypeError: Cannot read properties of undefined (reading 'slice')
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:304145
  at o.generateNewIdenticon (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:304179)
  at o.generateIdenticonSvg (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:304025)
  at o.iconForAddress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:303889)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:12616
  at wl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:264532)
  at zu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:289097)
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:221729)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
  at Fu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:288853)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:288764
  at D (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:221111)
  at x.port1.onmessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:219855)
```

### Version

11.10

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by Lidwenar** [comment]
Got same error, happens when trying to see "networks" in the configuration page. 

I can reproduce the error in chrome and in brave after adding astar zkatana testnet, in astar bridge page: https://portal.astar.network/zkatana-testnet/bridge/ethereum



![Captura de pantalla 2024-02-29 162711](https://github.com/MetaMask/metamask-extension/assets/160979668/417ae36d-b49c-49e2-a432-cd482411abfa)



full error message:


```
Detalles del error
Mensaje: Cannot read properties of undefined (reading 'slice')

Código: TypeError

Pila:
TypeError: Cannot read properties of undefined (reading 'slice')
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:304145
  at o.generateNewIdenticon (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:304179)
  at o.generateIdenticonSvg (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:304025)
  at o.iconForAddress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:303889)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:12616
  at wl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:264532)
  at zu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:289097)
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:221729)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
  at Fu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:288853)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:288764
  at D (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:221111)
  at x.port1.onmessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:21
```

**Comment by asawin247** [comment]
Update! MetaMask11.10.1 (Windows/Chrome) 
Bug fixed. Problem Solved.
