### ISSUE TITLE
Can't open metamask, always loading

### ISSUE THREAD

**Issue by checkboot** [MetaMask/metamask-extension#23338]
### What is this about?

 TypeError: globalThis.stateHooks.getPersistedState is not a function
  at i.o [as getMetaMetricsEnabled] (sentry-install.js:1:3225)
  at sentry-install.js:1:2377
  at sentry-install.js:1:128197
  at new i (sentry-install.js:1:359592)
  at i._notifyEventProcessors (sentry-install.js:1:128105)
  at sentry-install.js:1:128433
  at new i (sentry-install.js:1:359592)
  at i._notifyEventProcessors (sentry-install.js:1:128105)
  at sentry-install.js:1:128433
  at new i (sentry-install.js:1:359592)
  at i._notifyEventProcessors (sentry-install.js:1:128105)
  at sentry-install.js:1:128433
  at new i (sentry-install.js:1:359592)
  at i._notifyEventProcessors (sentry-install.js:1:128105)
  at sentry-install.js:1:128433
  at new i (sentry-install.js:1:359592)
  at i._notifyEventProcessors (sentry-install.js:1:128105)
  at i.applyToEvent (sentry-install.js:1:127896)
  at n.prepareEvent (sentry-install.js:1:157382)
  at u._prepareEvent (sentry-install.js:1:103711)
  at u._prepareEvent (sentry-install.js:1:56565)
  at u._processEvent (sentry-install.js:1:104506)
  at u._captureEvent (sentry-install.js:1:103769)
  at u.captureEvent (sentry-install.js:1:100867)
  at sentry-install.js:1:110938
  at u._withClient (sentry-install.js:1:113237)
  at u.captureEvent (sentry-install.js:1:110915)
  at d (sentry-install.js:1:71878)
  at sentry-install.js:1:70907
  at h (sentry-install.js:1:338067)
  at l.onerror (sentry-install.js:1:337511)
e.<computed> @ sentry-install.js:1
 (TypeError#1)
e.<computed> @ sentry-install.js:1
 TypeError#1: Accessor not expected at intrinsics.%IteratorPrototype%.constructor
e.<computed> @ sentry-install.js:1
   at isAllowedProperty (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:4159:13)
  at visitProperties (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:4206:26)
  at isAllowedPropertyValue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:4093:7)
  at isAllowedProperty (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:4156:14)
  at visitProperties (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:4206:26)
  at whitelistIntrinsics (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:4249:3)
  at repairIntrinsics (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:9937:3)
  at globalThis.lockdown (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:10026:28)
  at createKernel (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:11333:5)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:12428:18
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/runtime-lavamoat.js:12534:3

e.<computed> @ sentry-install.js:1
 Protecting intrinsics failed: (ReferenceError#2)
e.<computed> @ sentry-install.js:1
 ReferenceError#2: harden is not defined
e.<computed> @ sentry-install.js:1
   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-more.js:69:13
  at Set.forEach (<anonymous>)
  at protectIntrinsics (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-more.js:44:22)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/lockdown-more.js:97:5

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

mac, chrome

After restarting mac and chrome, clicking metamask is always loading and showing blank

**Comment by danjm** [comment]
@checkboot You likely need to update metamask. That error should have been fixed in v11.7.5
