### ISSUE TITLE
[Bug]: still problems after update to 11.11.3 on chrome  mmerrors  image  image

### ISSUE THREAD

**Issue by cryptodigi** [MetaMask/metamask-extension#23409]
### Describe the bug

cannot get password prompt, metamask loading forever

### Expected behavior

metamask should popup and "ask" for password but keeps loading forever

### Screenshots/Recordings

[](https://private-user-images.githubusercontent.com/46853966/310903878-21867915-dd17-4bf5-9e85-ebadbd1e7a24.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODEyMTUsIm5iZiI6MTcxMDA4MDkxNSwicGF0aCI6Ii80Njg1Mzk2Ni8zMTA5MDM4NzgtMjE4Njc5MTUtZGQxNy00YmY1LTllODUtZWJhZGJkMWU3YTI0LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE0MjgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NDM3NDRiZmRhMzZkNTRjMDM3NzlmYWY4ZGIwNGEyNzE1NTk0OGMzZmY3YjNhNzQwNzQxYmUyOWI1MTlkOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ptno9iICfRdxkUv87jJAdm7RPpp35S9H84bv3YFRpKE
)

### Steps to reproduce

open chrome
click on metamask extension 
watch loading forever

### Error messages or log output

```shell
https://github.com/MetaMask/metamask-extension/issues/23323#issuecomment-1983562514
```

### Version

11.11.4

### Build type

None

### Browser

Chrome

### Operating system

Windows

### Additional context

extension works on another chrome user, it always worked on both without any issue

**Comment by cryptodigi** [comment]
![mmerrors](https://github.com/MetaMask/metamask-extension/assets/46853966/a14c8969-f07a-4df6-a37e-698437449701)

**Comment by cryptodigi** [comment]
TypeError#2: F(...).call(...).filter is not a function
at n.PendingTransactionTracker.U (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:180055) at n.PendingTransactionTracker.R (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:179091) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:174221 at n.PendingTransactionTracker.onStateChange (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:130787) at new n.PendingTransactionTracker (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:174189) at new B (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:130463) at new pt (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:60829) at de (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:150293) at ie (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:148048)

**Comment by cryptodigi** [comment]
Contesto
background.html
Analisi dello stack
sentry-install.js:1 (e.<computed>)
sentry-install.js:1 (funzione anonima)
runtime-lavamoat.js:6929 (error)
runtime-lavamoat.js:7285 (handleRejection)
runtime-lavamoat.js:7058 (finalizeDroppedPromise)
1
2
3
4
5
6
7
8
SES_UNHANDLED_REJECTION: (TypeError#2)
Contesto
background.html
Analisi dello stack
sentry-install.js:1 (e.<computed>)
sentry-install.js:1 (funzione anonima)
runtime-lavamoat.js:6929 (error)
runtime-lavamoat.js:7285 (handleRejection)
runtime-lavamoat.js:7058 (finalizeDroppedPromise)/*!
    localForage -- Offline Storage, Improved
    Version 1.10.0
    https://localforage.github.io/localForage
    (c) 2013-2017 Mozilla, Apache License 2.0
*/
!function(e){if("object"==typeof n&&void 0!==t)t.exports=e();else if("function"==typeof define&&de

**Comment by cryptodigi** [comment]
can anybody take care of this??? extension is working on a chrome user but on another one is not, it used to work on both... loading forever...

**Comment by cryptodigi** [comment]
Error#1: MetaMask Migration Error #88: Invalid character
at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:627450) at l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:628272) at i._parseBase (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:630658) at i._init (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:628932) at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:627744) at l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:195264) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:193330 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:24:125031 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:24:100816 at wr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:24:90408) at Hn.mapKeys (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:24:125004) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:193319 at r.migrate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:194988) at o.migrateData (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-3.js:3:278963) at le (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:149353) at async ie (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:147729)

**Comment by cryptodigi** [comment]
SES_UNHANDLED_REJECTION: (TypeError#2)
e.<computed> @ sentry-install.js:1
sentry-install.js:1 TypeError#2: F(...).call(...).filter is not a function
e.<computed> @ sentry-install.js:1
sentry-install.js:1   at n.PendingTransactionTracker.U (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:180055)
  at n.PendingTransactionTracker.R (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:179091)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:174221
  at n.PendingTransactionTracker.onStateChange (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:130787)
  at new n.PendingTransactionTracker (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:174189)
  at new B (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-1.js:13:130463)
  at new pt (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:60829)
  at de (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:150293)
  at ie (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:148048)

e.<computed> @ sentry-install.js:1

**Comment by gauthierpetetin** [comment]
Closing as duplicate from: https://github.com/MetaMask/metamask-extension/issues/23323
