### ISSUE TITLE
[Bug]: Bricked extension after deleting currently showing account

### ISSUE THREAD

**Issue by danielnordh** [MetaMask/metamask-extension#23643]
### Describe the bug

After deleting an account that had recently been imported from a private key, the extension is now completely bricked.
Restarting extension, chrome, computer does not return to a usable state.

Sev1

### Expected behavior

Deleting an account, even if it is the currently showing one, should NOT brick the extension.
Expected behaviour would be for it to show another account, or ask the user to select another account.

### Screenshots/Recordings

<img width="354" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/3393669/6abc3f0a-68e6-4689-a12b-0f74b1ed8821">

### Steps to reproduce

1. Add an account by importing a private key
2. Initiate a transaction on that account
3. Delete the newly imported account (in my case I believe the transaction had been confirmed)
4. Extension shows error, completely bricking it

### Error messages or log output

```shell
Message: Cannot destructure property 'balance' of 'Z[V]' as it is undefined.

Code: TypeError

Stack:
TypeError: Cannot destructure property 'balance' of 'Z[V]' as it is undefined.
  at n.default.txData [as mapToProps] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:236382)
  at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:29788)
  at r.mapToProps (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:29924)
  at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:29788)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:28327
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:21025
  at Object.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:250245)
  at r.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:1:325852)
  at z (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:20969)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:246078)
  at Za (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:254286)
  at Ja (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:254105)
  at Ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:253824)
  at Pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:294417)
  at Iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276868)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276793)
  at Eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274133)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232483
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:220513)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
  at eo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232428)
  at Zi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232363)
  at Su (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274510)
  at fs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:299750)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:301673)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:169577
```

### Version

11.12.4

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by anaamolnar** [comment]
Hi @danielnordh. Thanks for reporting this! Can you consistently reproduce this issue, or was this just a one-time occurrence? If you can reproduce this again, please share the console log errors you see when this pop-up error appears. Is this behavior consistent even after updating to 11.13.0? You will be able to update manually from your browser. Go to extensions-> Metamask->Details->Enable developer mode from the top right, then there should be a button for Updating in the top left. Thank you!

**Comment by plasmacorral** [comment]
@danielnordh Im sorry that you encountered this but I want to thank you for taking the time to share this experience.  Removing an account should never brick the wallet.  

I'm not seeing the issue when I follow these reproduction steps.  Is there anything more you can share about what you were doing before you observed this issue? Were you just doing a send tx at the time, or was this a contract interaction?  What network were you on when this was observed?

I am testing in Mac Sonoma 14.3.1 with Chrome 117.0.5938.92 using extension 11.12.4.  I have tried removing the account I imported by private key immediately after sending a tx, as well as letting the tx be confirmed and then removing.  In both cases the active account is changed to one that was not removed and the extension is not erroring for me.

**Comment by anaamolnar** [comment]
Hey @danielnordh If this continues to occur, could you please reach out to Metamask support by clicking 'Start a conversation' on our site: https://support.metamask.io/hc/en-us 
Please make sure to mention this Github issue, as we'd like to ask for some more information regarding this. Thank you!

**Comment by AlexJupiter** [comment]
Downgrading this to Sev2 until we can reproduce on the MetaMask side.

**Comment by danielnordh** [comment]
Still bricked with 11.13.1

I contacted support and am awaiting further questions.

**Comment by danielnordh** [comment]
Update:

On a subsequent open of the extension (that requires inputting the password) I tried switching the network from Ethereum to Polygon before signing in. This WORKED. Extension is now working again, I was also able to switch back to Ethereum again after being signed in.

This is good, as there seems to be no material damage. 
If I had to fix this myself, I'd go look for places where there is an assumption of stable account states (I.e not updating if accounts are deleted) and implement some graceful fallbacks / ignoring undefined accounts etc.

Anyway, this gets me what I wanted, a functioning extension and access to my accounts again.

**Comment by Gudahtt** [comment]
Reopening so that someone can analyze the stack trace provided to find the reason for the crash.

**Comment by Montoya** [comment]
Spend one day analyzing the stack trace, determine if this is still an issue, and determine if we can better handle these types of errors in the future (so that the Extension is not bricked).

**Comment by gantunesr** [comment]
Thanks @ccharly for the investigation, will close the issue since this can't be reproduced in recent versions.
