### ISSUE TITLE
[Bug]:  Windows Build Failure

### ISSUE THREAD

**Issue by pauldmurphy** [MetaMask/metamask-extension#23805]
### Describe the bug

yarn fails to build on windows with the following error:

MetaMask build: Encountered an error while running task "dist".
Error: MetaMask build: runInChildProcess for task "scripts:core:dist:standardEntryPoints" encountered an error "1".
  at ChildProcess.eval (D:\source\metamask-extension\development\build\task.js:97:13)
  at Object.onceWrapper (node:events:633:26)
  at ChildProcess.emit (node:events:518:28)
  at cp.emit (D:\source\metamask-extension\node_modules\cross-spawn\lib\enoent.js:35:29)
  at ChildProcess._handle.onexit (node:internal/child_process:294:12)

### Expected behavior

a successful build.

### Steps to reproduce

1: clone git repo
2: Setup build env
3: invoke yarn dist --build-type Flask
4: kaBOOM

### Error messages or log output

```shell
MetaMask build: Encountered an error while running task "dist".
Error: MetaMask build: runInChildProcess for task "scripts:core:dist:standardEntryPoints" encountered an error "1".
  at ChildProcess.eval (D:\source\metamask-extension\development\build\task.js:97:13)
  at Object.onceWrapper (node:events:633:26)
  at ChildProcess.emit (node:events:518:28)
  at cp.emit (D:\source\metamask-extension\node_modules\cross-spawn\lib\enoent.js:35:29)
  at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

### Version

11.13.0

### Build type

Flask

### Browser

Chrome, Firefox, Microsoft Edge, Brave

### Operating system

Windows

### Severity

severe build blocking issue.

**Comment by pauldmurphy** [comment]
attempting to build using yarn start produces the following

 *  Executing task: yarn run start 

Building lavamoat runtime file (scuttling is off)
Running task "dev"...
Starting 'dev'...
Starting 'clean'...
Finished 'clean'
Starting 'styles:dev'...
Finished 'styles:dev'
Starting 'scripts:core:dev:standardEntryPoints'...
Starting 'scripts:core:dev:contentscript'...
Starting 'scripts:core:dev:disable-console'...
Starting 'scripts:core:dev:sentry'...
Starting 'static:dev'...
Starting 'manifest:dev'...
Starting 'reload'...
Finished 'reload'
Finished 'manifest:dev'
Finished 'static:dev'
scripts:core:dev:disable-console: Bundle start: "disable-console"
scripts:core:dev:standardEntryPoints: Bundle start: "primary"
scripts:core:dev:contentscript: Bundle start: "inpage"
scripts:core:dev:sentry: Bundle start: "sentry-install"
scripts:core:dev:disable-console: Bundle end: "disable-console"
scripts:core:dev:contentscript: Bundle end: "inpage"
scripts:core:dev:contentscript: Bundle start: "contentscript"
scripts:core:dev:sentry: Bundle end: "sentry-install"
scripts:core:dev:contentscript: Bundle end: "contentscript"
scripts:core:dev:standardEntryPoints: TypeError: Tried to access an environmental variable "_nodeLRUCacheForceNoSymbol" that wasn't declared in builds.yml
        Why am I seeing this: We've made use of new variables be explicit to keep track of all of them in one place
        How do I fix this: Adding your variable in builds.yml under "env" property and committing to git will fix this
    at Variables.getMaybe (D:\source\metamask-extension\development\lib\variables.js:52:7)
    at Variables.get (D:\source\metamask-extension\development\lib\variables.js:28:24)
    at Object.get (D:\source\metamask-extension\development\build\scripts.js:1187:26)
    at getReplacementString (D:\source\metamask-extension\node_modules\loose-envify\replace.js:56:19)
    at replace (D:\source\metamask-extension\node_modules\loose-envify\replace.js:28:25)
    at LooseEnvify._flush (D:\source\metamask-extension\node_modules\loose-envify\loose-envify.js:33:18)
    at LooseEnvify.final [as _final] (node:internal/streams/transform:128:10)
    at prefinish (node:internal/streams/writable:906:14)
    at finishMaybe (node:internal/streams/writable:920:5)
    at Writable.end (node:internal/streams/writable:835:5)
    at DuplexWrapper.<anonymous> (D:\source\metamask-extension\node_modules\duplexer2\index.js:29:14)
    at Object.onceWrapper (node:events:632:28)
    at DuplexWrapper.emit (node:events:530:35)
    at finishMaybe (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at Writable.end (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at DestroyableTransform.onend (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:632:28)
    at DestroyableTransform.emit (node:events:530:35)
    at endReadableNT (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  filename: 'D:\\source\\metamask-extension\\node_modules\\react-devtools-core\\dist\\backend.js',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      finish: undefined,
      error: [Function (anonymous)],
      unpipe: undefined,
      drain: undefined,
      close: undefined,
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [Deps], [Transform] ],
    length: 2,
    label: 'deps',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  }
}
scripts:core:dev:standardEntryPoints: scripts:core:dev:standardEntryPoints: [SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'] {
  line: 366,
  column: 1,
  annotated: '\n' +
    'D:\\source\\metamask-extension\\node_modules\\ts-mixer\\dist\\esm\\index.js:366\n' +
    'export { Mixin, decorate, hasMixin, mix, settings };\n' +
    '^\n' +
    "ParseError: 'import' and 'export' may appear only with 'sourceType: module'",
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 0 },
      length: 0,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: true,
      ended: false,
      endEmitted: false,
      reading: true,
      sync: false,
      needReadable: true,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      finish: [Function],
      error: [Function (anonymous)],
      unpipe: undefined,
      drain: undefined,
      close: undefined,
      data: [Function: ondata],
      _mutate: [Function]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 1,
      writing: true,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: [Function: nop],
      writelen: 1,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 1,
      prefinished: false,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: true,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [DestroyableTransform] ],
    length: 1,
    label: 'syntax',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  }
}
scripts:core:dev:standardEntryPoints: scripts:core:dev:standardEntryPoints: TypeError: Tried to access an environmental variable "SUITE_TYPE" that wasn't declared in builds.yml
        Why am I seeing this: We've made use of new variables be explicit to keep track of all of them in one place
        How do I fix this: Adding your variable in builds.yml under "env" property and committing to git will fix this
    at Variables.getMaybe (D:\source\metamask-extension\development\lib\variables.js:52:7)
    at Variables.get (D:\source\metamask-extension\development\lib\variables.js:28:24)
    at Object.get (D:\source\metamask-extension\development\build\scripts.js:1187:26)
    at getReplacementString (D:\source\metamask-extension\node_modules\loose-envify\replace.js:56:19)
    at replace (D:\source\metamask-extension\node_modules\loose-envify\replace.js:28:25)
    at LooseEnvify._flush (D:\source\metamask-extension\node_modules\loose-envify\loose-envify.js:33:18)
    at LooseEnvify.final [as _final] (node:internal/streams/transform:128:10)
    at prefinish (node:internal/streams/writable:906:14)
    at finishMaybe (node:internal/streams/writable:920:5)
    at Writable.end (node:internal/streams/writable:835:5)
    at DuplexWrapper.<anonymous> (D:\source\metamask-extension\node_modules\duplexer2\index.js:29:14)
    at Object.onceWrapper (node:events:632:28)
    at DuplexWrapper.emit (node:events:530:35)
    at finishMaybe (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_writable.js:630:14)
    at endWritable (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_writable.js:638:3)
    at Writable.end (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_writable.js:594:22)
    at DestroyableTransform.onend (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (node:events:632:28)
    at DestroyableTransform.emit (node:events:530:35)
    at endReadableNT (D:\source\metamask-extension\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  filename: 'D:\\source\\metamask-extension\\node_modules\\@trezor\\env-utils\\lib\\envUtils.js',
  stream: Labeled {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { length: 16 },
      length: 16,
      pipes: [Labeled],
      pipesCount: 1,
      flowing: false,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: true,
      readableListening: false,
      resumeScheduled: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 1,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {
      end: [Array],
      finish: undefined,
      error: [Function (anonymous)],
      unpipe: undefined,
      drain: undefined,
      close: undefined,
      data: [Function: ondata],
      _mutate: undefined
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function (anonymous)],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [CorkedRequest]
    },
    writable: false,
    allowHalfOpen: true,
    _options: { objectMode: true },
    _wrapOptions: { objectMode: true },
    _streams: [ [Deps], [Transform] ],
    length: 2,
    label: 'deps',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  }
}
