### ISSUE TITLE
[Bug]: Simulation Details reports NumberFormat RangeError for some locales

### ISSUE THREAD

**Issue by dbrans** [MetaMask/metamask-extension#24067]
@anaamolnar reported 3 inquiries of the error “RangeError: Incorrect locale information provided” when attempting a transaction.

```
RangeError: Incorrect locale information provided
  at Intl.NumberFormat (<anonymous>)
  at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-6.js:1:286226
  at a.IndividualFiatDisplay (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-7.js:1:392298)
  at ga (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:266221)
  at _l (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:311148)
  at Ru (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:297011)
  at Au (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:296936)
  at Su (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:294276)
  at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:252626
  at n.unstable_runWithPriority (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-2.js:1:335481)
  at $i (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:252335)
  at eo (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:252571)
  at Zi (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:252506)
  at bu (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:291042)
  at Ra (chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-1.js:33:269878)
  at chrome-extension://ljfoeinjpaedjfecbmggjgodbgkmjkjk/ui-6.js:1:279473
```

**Comment by dbrans** [comment]
The following locales are affected: es_419, pt_BR, pt_PT, zh_CN, zh_TW
Basically, exactly those [locales that have an underscore](https://github.com/MetaMask/metamask-extension/blob/9980779fa4b9c7e9d808c844360cc2e7632c81f4/app/_locales/index.json).
