### ISSUE TITLE
[Bug]: RangeError: Incorrect locale information provided

### ISSUE THREAD

**Issue by linxin2020** [MetaMask/metamask-extension#24126]
### Describe the bug

My MetaMask is currently the latest version 11.14.0,
I visited https://stargate.finance/transfer Click on "Transfer"
MetaMask pops up an error page,
![image](https://github.com/MetaMask/metamask-extension/assets/46699328/251b9c99-17c0-409a-ba3d-3e2b382d1529)
The detailed error information is as follows:

> RangeError: Incorrect locale information provided
>   at Intl.NumberFormat (<anonymous>)
>   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:253421
>   at a.IndividualFiatDisplay (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:303738)
>   at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:246078)
>   at Pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:291005)
>   at Iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276868)
>   at ju (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276793)
>   at Eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274133)
>   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232483
>   at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:242911)
>   at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
>   at eo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232428)
>   at Zi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232363)
>   at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:270899)
>   at Ia (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:249735)
>   at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:246668

Next, as long as you click the plugin button, an error page will appear after unlocking; Even if the browser is restarted, the same phenomenon occurs.

### Expected behavior

Normal use

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/46699328/45672fb0-ebb9-4633-a0ae-45eb6acd5975)

### Steps to reproduce

None

### Error messages or log output

```shell
RangeError: Incorrect locale information provided
  at Intl.NumberFormat (<anonymous>)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:253421
  at a.IndividualFiatDisplay (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:303738)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:246078)
  at Pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:291005)
  at Iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276868)
  at ju (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276793)
  at Eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274133)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232483
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:242911)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
  at eo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232428)
  at Zi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232363)
  at bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:270899)
  at Ia (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:249735)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:246668
```

### Version

11.14.0

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by linxin2020** [comment]
I further verified that if the extension language is set to Simplified Chinese(简体中文), the above issue will inevitably occur. Setting it to English is normal.
the extension language settings quick access :
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html#settings
