### ISSUE TITLE
[Bug]: Error Message: getMinimumGasTotalInHexWei expects either gasPrice OR the EIP-1559 gas fields, but neither were provided

### ISSUE THREAD

**Issue by digiwand** [MetaMask/metamask-extension#24263]
### Describe the bug

Multiple users are experiencing an error with getMinimumGasTotalInHexWei when attempting to issue a transaction from a variety of networks. 

![image (1)](https://github.com/MetaMask/metamask-extension/assets/20778143/daa33d3e-3b86-44a8-81ca-566831f28945)

@anaamolnar 
> I see this issue comes steady in the queue everyday since the 11.14.0 release. About 2-4 per day. Reports mention multiple networks,including Ethereum Mainnet, Scroll, Polygon ZKEvm, etc.
A more detailed ticket: https://consensys.zendesk.com/agent/tickets/1157137

### Related Links: 

- Related investigation thread: https://consensys.slack.com/archives/GTQAGKY5V/p1714114810125029
- https://consensys.zendesk.com/agent/search/1?copy&type=ticket&q=%22getMinimumGasTotalInHexWei%22%20order_by%3Acreated_at%20sort%3Ades
- https://consensys.zendesk.com/agent/tickets/1156444

### Current Investigation Findings: 

it appears the issue is related to an incomplete formation of the gasEstimationObject created in core/transaction-controller#transactionFeeSelector

[/ui/selectors/confirm-transaction.js#L293](https://github.com/MetaMask/metamask-extension/blob/8860a107376884b574d009d5cd4ba3ebb000bc19/ui/selectors/confirm-transaction.js#L293) - transactionFeeSelector:
```
const gasEstimationObject = {
    gasLimit: txData.txParams?.gas ?? '0x0',
};

// .. logic that adds more props to gasEstimationObject

getMinimumGasTotalInHexWei(gasEstimationObject);
```

/[shared/modules/gas.utils.js#L76](https://github.com/MetaMask/metamask-extension/blob/8860a107376884b574d009d5cd4ba3ebb000bc19/shared/modules/gas.utils.js#L76) - getMinimumGasTotalInHexWei:
```
export function getMinimumGasTotalInHexWei({
  gasLimit = '0x0',
  gasPrice,
  maxPriorityFeePerGas,
  maxFeePerGas,
  baseFeePerGas,
} = {}) {
  const isEIP1559Estimate = Boolean(
    maxFeePerGas || maxPriorityFeePerGas || baseFeePerGas,
  );
  if (isEIP1559Estimate && gasPrice) {
    throw new Error(
      `getMinimumGasTotalInHexWei expects either gasPrice OR the EIP-1559 gas fields, but both were provided`,
    );
  }

  if (isEIP1559Estimate === false && !gasPrice) {
    throw new Error(
      `getMinimumGasTotalInHexWei expects either gasPrice OR the EIP-1559 gas fields, but neither were provided`,
    );
  }
```

@danjm 
> the below code is resulting in a gasEstimationObject which does not have any of the following properties: maxFeePerGas, maxPriorityFeePerGas, baseFeePerGas, gasPrice
> > that would be possible if networkAndAccountSupportsEIP1559 was false and if gasEstimateType was not any of none,ethGasPrice, or legacy
>
> > Another possibility is that each of the values in this expression are numbers === 0
    ```
      const isEIP1559Estimate = Boolean(
        maxFeePerGas || maxPriorityFeePerGas || baseFeePerGas,
      );
     ```

![image](https://github.com/MetaMask/metamask-extension/assets/20778143/37ae3fea-675c-43fc-b053-86cbe9b57ad2)

### Steps to reproduce

From a report:

1) I go into any application where I need to sign a transaction specifically with payment for gas.
2) The metamask pop-up window appears.
3) For a split second it will show how much I will spend for gas, and if I don’t have time to press it, an error will immediately appear

From another report:
I tried to deposit Metis on Metis network by a use of AAVE Defi app
The URL is as follows: https://app.aave.com/?marketName=proto_metis_v3
The steps are just click on the URL above, connect MetaMask and try to deposit Metis. Click the button Supply.
However, they said they could no longer reproduce it the next day

### Error messages or log output

```shell
Error details
Message: getMinimumGasTotalInHexWei expects either gasPrice OR the EIP-1559 gas fields, but neither were provided
Code: Error
Stack:
Error: getMinimumGasTotalInHexWei expects either gasPrice OR the EIP-1559 gas fields, but neither were provided
at n.getMinimumGasTotalInHexWei (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:15:835395)
at a.transactionFeeSelector (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-10.js:1:300714)
at n.default.txData [as mapToProps] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-8.js:1:27146)
at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:52186)
at r.mapToProps (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:52322)
at r (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:52186)
at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:50725
at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:43423
at Object.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:250245)
at n.useMemo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:8:449673)
at z (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:43367)
at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:246078)
at Za (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:254286)
at Ja (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:254105)
at Ya (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:253824)
at Pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:294417)
at Iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276868)
at ju (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276793)
at Eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274133)
at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232483
at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:242911)
at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
```
```


### Version

11.14.0

### Build type

None

### Browser

Other (please elaborate in the "Additional Context" section)

### Operating system

Other (please elaborate in the "Additional Context" section)

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

**Comment by bschorchit** [comment]
I was able to consistently reproduce this issue for some time by going through the send flow on Scroll network and also on Polygon skEVM on v11.14.

Learnings:
- if the crash happens before the confirmation for the send flow shows up, closing and re-opening solves it. 
- if the crash happens on the confirmation, the confirmation persists even after closing and re-opening the popup so the crash happens again (you can see the confirmation for 1-2 seconds before the crash happens again)
- if the crash happens on the confirmation, disabling and re-enabling the extension showed me the unlock screen. After unlocking it, I saw the crash screen again (didn't see any confirmation appear for few seconds first in this case), but closing and re-opening the popup not only solved the crash screen, but also made me not able to reproduce this issue anymore on any network. 

https://github.com/MetaMask/metamask-extension/assets/34968356/29c051e3-50fa-421c-817b-e389c469c033

**Comment by digiwand** [comment]
Thanks @bschorchit for the helpful insights! Made a bit more progress on this with this info. 

I was able to reproduce the issue by adding the Scroll Sepholia Testnet (see: https://docs.scroll.io/en/user-guide/setup/), then using our test dapp > Send Eth > Send

**Investigation update:**

when the error occurs, in the selectors/confirm-transaction#transactionFeeSelector, the gasEstimateType is  "fee-market" which breaks without adding any props to the gasEstimationObject. When it works in the same flow it has been "eth_gasPrice"

```
    switch (gasEstimateType) {
      case GasEstimateTypes.none:
        gasEstimationObject.gasPrice = txData.txParams?.gasPrice ?? '0x0';
        break;
      case GasEstimateTypes.ethGasPrice:
        gasEstimationObject.gasPrice =
          txData.txParams?.gasPrice ??
          decGWEIToHexWEI(gasFeeEstimates.gasPrice);
        break;
      case GasEstimateTypes.legacy:
        gasEstimationObject.gasPrice =
          txData.txParams?.gasPrice ?? getAveragePriceEstimateInHexWEI(state);
        break;
      case GasEstimateTypes.feeMarket:
        break;
      default:
        break;
    }
```
