### ISSUE TITLE
[Bug]: Error: "Unable to determine contract standard" while trying to deposit LBP on launchblock.com

### ISSUE THREAD

**Issue by floki21uu** [MetaMask/metamask-extension#24303]
### Describe the bug

I use Chrome browser metamask plugin. I have tried to deposit LBP from my Metamask on https://launchblock.com/tiers in the searchbox "enter amount to deposit" and then the error appears in metamask: 
"Error details
Message: Unable to determine contract standard

Code: -32603

Code: Error

Stack:
Error: Unable to determine contract standard
  at p.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:11436)
  at Generator.throw (<anonymous>)
  at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:7582)"
![image](https://github.com/MetaMask/metamask-extension/assets/96269029/57c30cf9-a976-4039-8ec1-94c0c14178d5)

### Expected behavior

tokens should be sent

### Screenshots/Recordings

![image](https://github.com/MetaMask/metamask-extension/assets/96269029/c2bda771-cff4-41fb-96ce-aa3e8c8a886d)

### Steps to reproduce

1. Get some LBP from uniswap (https://app.uniswap.org/explore/tokens/ethereum/0xa23c1194d421f252b4e6d5edcc3205f7650a4ebe)
2. Try to deposit in the website  https://launchblock.com/tiers

### Error messages or log output

```shell
Try again by closing and reopening the popup, or contact support here.
Error details
Message: Unable to determine contract standard

Code: -32603

Code: Error

Stack:
Error: Unable to determine contract standard
  at p.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:11436)
  at Generator.throw (<anonymous>)
  at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:7582)
```

### Version

newest

### Build type

None

### Browser

Chrome

### Operating system

Windows

**Comment by hjetpoluru** [comment]
I am able to connect to the Metamask through the LBP site, could you please recheck and let us know the issue exists.
