### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'iconUrl')

### ISSUE THREAD

**Issue by kathyrnvv** [MetaMask/metamask-extension#24386]
### Describe the bug

When connect the dapp, it happen.

### Steps to reproduce

When connect the dapp, click 'next' button, sometimes it happen.

### Error messages or log output

```shell
MetaMask 遇到了一个错误
通过重新加载页面再试一次，或联系支持团队 此处。
错误详情
信息：Cannot read properties of undefined (reading 'iconUrl')

代码：TypeError

栈：
TypeError: Cannot read properties of undefined (reading 'iconUrl')
  at m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:279576)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:246078)
  at Pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:291005)
  at Iu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276868)
  at ju (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:276793)
  at Eu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274133)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232483
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-2.js:1:242911)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232192)
  at eo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232428)
  at Zi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:232363)
  at Su (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:274510)
  at fs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:299750)
  at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-1.js:33:301673)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-6.js:1:291179
```

### Version

11.x

### Build type

None

### Device

Windows10

### Operating system

Other (please elaborate in the "Additional Context" section)

**Comment by alfeng6** [comment]
can you please let us know which dapp you are using?

**Comment by nocrabs** [comment]
When chrome sets the website not to load images, this error will inevitably occur when accessing the dapp [https://stack.shape.network/](https://stack.shape.network/), connecting to metamask and then signing.

**Comment by nocrabs** [comment]
[https://infinity.theoriq.ai/](https://infinity.theoriq.ai/) dapp too

**Comment by darkwing** [comment]
Could not reproduce.
