### ISSUE TITLE
(Ext) Prevent transaction failures for ledger users when requests to the ledger cdn fail

### ISSUE THREAD

**Issue by danjm** [MetaMask/metamask-extension#25666]
As was the case here https://github.com/MetaMask/metamask-extension/issues/25623 and here https://github.com/MetaMask/metamask-extension/issues/17964, it is possible for server side problems related to the https://cdn.live.ledger.com/plugins/ethereum.json endpoint to cause ledger transactions to fail (before they are published to the blockchain).

If the network request in `loadInfosForContractMethod` (https://github.com/LedgerHQ/ledger-live/blob/173bb3c84cc855f83ab8dc49362bc381afecc31e/libs/ledgerjs/packages/hw-app-eth/src/services/ledger/contracts.ts#L17) call in the `signTransaction` method of the Eth class in the `hw-app-eth` library fails, then transaction signing will fail.

Ledger users should be able to sign transactions even if ledger servers are down entirely.

The network requests made here get information that can be useful for ledger users, and help them make secure decisions. As we resolve this issue, we should be mindful that in the case where ledger servers are down (or there are CORS issues as was the case in the above linked issues), the users are effectively "blind signing" on the device, without helpful cues like token names or symbols. We may want to give a warning in these cases.

**Comment by lambertkevin** [comment]
This problem has been fixed in a later version of `hw-app-eth`, Metamask is still using a 3 year old version of it, but we can't update the lib in your stack because of this issue: https://github.com/MetaMask/eth-ledger-bridge-keyring/issues/217 😞

**Comment by desi** [comment]
Tested in v12.9.1 and RC 12.10.0 and can't reproduce. This is valid to be closed.

**Comment by mikesposito** [comment]
Reopening as the issue can still be observed on main:

```
Error: Network Error\n    at createError (https://metamask.github.io/eth-ledger-bridge-keyring/bundle.js:20588:15)\n    at XMLHttpRequest.handleError (https://metamask.github.io/eth-ledger-bridge-keyring/bundle.js:20039:14)
```

The bundle is being created with `yarn webpack --watch` to use `eth-ledger-bridge-keyring` as keyring

**Comment by dawnseeker8** [comment]
We only can reduce the chance of this issue to provide a backup cdn link for fetch that json file, however, this fix is better to fix in ledger side since the contract code was maintenanced by ledger team. if we provide a patch to. that file, we may need to upgrade patch in future release.

I have asked the ledger team to see any solution from them. lets wait for their reply to resolve this issue.

**Comment by dawnseeker8** [comment]
I have tried to how many times this issues will happen in Mixpanel. 
https://mixpanel.com/project/2212883/view/2760759/app/boards#discover and didnt discover any server logs relative to it.

and sentry log as well
https://metamask.sentry.io/issues/?project=273505&project=2299799&query=is%3Aunresolved%20eth-ledger-bridge-keyring&referrer=issue-list&statsPeriod=90d

and sentry only have two logs in 90 days, but all not relative to cdn errors.
