### ISSUE TITLE
new BigNumber() not a base 16 number

### ISSUE THREAD

**Issue by ranbuch** [MetaMask/metamask-extension#2616]
After installing the chrome extension and importing my existing accounts (1 account with 12 words and the other with Ethereum public and private keys) successfully I've tried to view my EOS tokens here:
https://eos.io/distribution/
and got this message:
```
new BigNumber() not a base 16 number:

BigNumber Error: new BigNumber() not a base 16 number: 
    at I (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:126015)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:131731
    at new e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:123515)
    at i.formatOutputString [as _outputFormatter] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:10074)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:14436
    at i.decode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:14458)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:7368
    at Array.map ()
    at d.decodeParams (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:7341)
    at c.unpackOutput (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:14246:37800)
```
inside a ```div``` element with the class ```error pane```.

I had a lot of errors in the console of the extension's background page:
```chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/_generated_background_page.html```
but after ```location.reload()```, logged back in to my account on the extension's popup window and reloading this page:
```https://eos.io/distribution/``` I didn't see any errors in the background page though did see the same error message ```new BigNumber() not a base 16 number:...``` etc.

When trying to access the EOS distribution page on my other PC I can see my EOS tokens as I should.

**Comment by someanon** [comment]
Also got this bug on [this contract](https://gist.github.com/someanon/e94629e0473a57d207f7130f8f0aa464).

After initalizing it in firefox:
```
window.app = {}
app.web3 = new Web3(web3.currentProvider);
app.ct = app.web3.eth.contract(contractABI).at(contractAddr)
```
and calling `app.ct.candidateName(0, function(e, c) { console.log(e); console.log(c) })` in console i'm getting this throw. But with 1 or 2 as first argument (e.g. `app.ct.candidateName(1, function(e, c) { console.log(e); console.log(c) })`) it works as expected.

You can try yourself this smartcontract at `0x39b93e2782672a7360e4991d4e7070995f324a31` in rinkeby testnet with [this abi](https://gist.github.com/someanon/deb3ffc7d76e60acd2eca808e051717d)

**Comment by someanon** [comment]
Also got this bug on firefox 58.0.1 x64 with Metamask 3.14.1.
```
BigNumber Error: new BigNumber() not a base 16 number: 
Stack trace:
I@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:126016
n/P</<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:131757
e@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:123513
formatOutputString@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:9969
[140]</</_dereq_<[14]</i.prototype.decode/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:14329
[140]</</_dereq_<[14]</i.prototype.decode@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:14181
[140]</</_dereq_<[7]</d.prototype.decodeParams/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:7265
[140]</</_dereq_<[7]</d.prototype.decodeParams@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:7238
[140]</</_dereq_<[31]</c.prototype.unpackOutput@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:37706
[140]</</_dereq_<[31]</c.prototype.call/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:38102
e/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:46834
[140]</</_dereq_<[46]</s.prototype.sendAsync/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:14308:60422
_handle/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:9935:9
once/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:735:9
next@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:5577:20
onlyOnce/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1220:9
once/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:735:9
replenish@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1255:25
iterateeCallback@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1245:17
onlyOnce/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1220:9
createIdRemapMiddleware/</<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:9870:7
_runReturnHandlersUp/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:10030:16
_withoutIndex/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:3358:16
replenish@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1260:17
_eachOfLimit/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1264:9
eachLimit$1@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:3444:5
doLimit/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1294:16
_runReturnHandlersUp@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:10029:7
_runMiddleware/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:9947:16
nextTask@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:5572:9
next@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:5579:9
onlyOnce/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1220:9
checkForCompletion@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:9966:16
nextTask@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:5572:9
next@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:5579:9
onlyOnce/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1220:9
completeRequest@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:10020:9
_asyncMap/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1388:9
once/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:735:9
replenish@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1255:25
iterateeCallback@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1245:17
onlyOnce/<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1220:9
_asyncMap/</<@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:1385:13
end@moz-extension://05c521ca-a598-4ef2-aa2c-b1fa6f1e3f80/scripts/inpage.js:10005:11
```

You can try yourself [this smartcontract](https://gist.github.com/someanon/e94629e0473a57d207f7130f8f0aa464) at `0x39b93e2782672a7360e4991d4e7070995f324a31` in rinkeby testnet with [this abi](https://gist.github.com/someanon/deb3ffc7d76e60acd2eca808e051717d)

After initalizing it in firefox:
```
window.app = {}
app.web3 = new Web3(web3.currentProvider);
app.ct = app.web3.eth.contract(contractABI).at(contractAddr)
```
and calling `app.ct.candidateName(0, function(e, c) { console.log(e); console.log(c) })` i'm getting this throw. But with 1 or 2 as first argument (e.g. `app.ct.candidateName(1, function(e, c) { console.log(e); console.log(c) })`) it works as expected.

**Comment by bdresser** [comment]
Closing due to inactivity - if this is still relevant, feel free to open a new issue.

**Comment by oliverbj** [comment]
I have the exact same issue.

**Comment by lacdael** [comment]
I had this, when I was connected to the wrong network.

I was connected to a mainnet instead of testnet.
