### ISSUE TITLE
[Bug]: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by egorFiNE** [MetaMask/metamask-extension#26243]
### Describe the bug

Sending USDT on BSC to an address crashes MetaMask and makes it unusable even after the restart. I have sent USDT countless times on BSC before so that's a regression of v12. 

The way to reset MetaMask is to restart chrome, switch MetaMask to another network, Reset activity, then back to BSC and again Reset activity and only after that I can use MetaMask again. 

Bug is 100% repeatable.

### Screenshots/Recordings

<img width="1098" alt="Screenshot 2024-07-31 at 11 25 39" src="https://github.com/user-attachments/assets/b4b36faa-2d93-442b-b5c6-e5d223403e20">

### Steps to reproduce

1. Open metamask, enter password
2. Go to Tokens tab
3. Select USDT
4. Click Send
5. Choose address in Contacts
6. Enter a positive amount
7. Click Continue

Boom, `Cannot convert undefined or null to object`

### Error messages or log output

```shell
MetaMask encountered an error
Try again by closing and reopening the popup, or contact support here.
Error details
Message: Cannot convert undefined or null to object

Code: TypeError

Stack:
TypeError: Cannot convert undefined or null to object
  at Function.entries (<anonymous>)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-9.js:1:204169
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/sentry-install.js:1:681)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:252205
  at e.<computed> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/sentry-install.js:1:681)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:251529
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:180624
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:181223
  at g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-7.js:1:108263)
  at ga (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:61316)
  at Cs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:106147)
  at Au (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:92055)
  at Ou (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:91980)
  at Tu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:89328)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47726
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:13158)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47435)
  at eo (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47671)
  at Ji (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47606)
  at $u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:104354)
  at n.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:13158)
  at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:47435)
  at Bu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:104005)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:1:103916
  at B (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:12540)
  at T.port1.onmessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-6.js:3:11284)
```
```


### Detection stage

In production (default)

### Version

12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Hardware wallet

_No response_

### Additional context

_No response_

### Severity

_No response_

**Comment by egorFiNE** [comment]
Additional information: reproducible on all networks, not just BSC.

**Comment by danjm** [comment]
Thanks @egorFiNE 

I have attempted to reproduce this but am not able to. Attached is a video of a successful send of USDT, using version 12 of metamask.

Am I following the same steps that you are following?

https://github.com/user-attachments/assets/6d84bfad-fe26-4641-b189-d1287bbfa9b6

**Comment by egorFiNE** [comment]
@danjm I have just recorded a video with the bug reproduction. Can I send it to you by email?

**Comment by danjm** [comment]
Hey, actually, I think I reproduced it now.

Can you check if the "Show balance and token price checker" toggle in your Settings is off? If so, I think that is required to reproduce this bug.

If you are okay with having that setting turned on, then you can fix the bug by turning the  "Show balance and token price checker" setting on, switching networks and then switching back to your desired network.

If you do not want to use MetaMask with that setting turned on, then you will have to wait for us to publish a bug fix. 

In any case, please do confirm that setting is toggled off, as it will confirm my understanding of the bug. Thanks again for reporting this and for your help, and sorry for the inconvenience of this bug.

**Comment by egorFiNE** [comment]
@danjm yeah, that's it. Toggled it on and it works now.
