### ISSUE TITLE
Fix "Test Snap Dialog test all three snap_dialog types" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26386]
Latest CI failure
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/96107/workflows/92f1acef-038a-4f4d-a7cb-066db69d4944/jobs/3578041/tests

```
NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 4 of 20, Job test-e2e-chrome)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at WindowHandles.getCurrentWindowProperties (test/e2e/background-socket/window-handles.ts:72:20)
    at WindowHandles.switchToHandleAndCheckForProperty (test/e2e/background-socket/window-handles.ts:205:28)
    at WindowHandles.switchToWindowWithProperty (test/e2e/background-socket/window-handles.ts:161:31)
    at async Driver.switchToWindowWithTitle (test/e2e/webdriver/driver.js:932:12)
    at async switchToNotificationWindow (test/e2e/helpers.js:1028:3)
    at async /home/circleci/project/test/e2e/snaps/test-snap-dialog.spec.js:162:9
    at async withFixtures (test/e2e/helpers.js:196:5)
    at async Context.<anonymous> (test/e2e/snaps/test-snap-dialog.spec.js:13:5)
```
Below are my observations:-

- In the failed CI link, navigate to the artifacts. It shows that the dialog was captured, but the switch to the dialog was not possible according to the error message above.

![snaps-dialog](https://github.com/user-attachments/assets/5a53095c-7307-4084-96a7-503135555f5f)

- The same test has passed in the regular build and in the Chrome browser. The passed CI link is mentioned below with a screenshot attached:

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/95206/workflows/bc6dd862-2773-4f4a-8f87-3e729694cb30/jobs/3543822/parallel-runs/2?filterBy=ALL

![image](https://github.com/user-attachments/assets/eacb84f8-f9e7-47c9-ade1-f7e1d39c6064)

- I updated the function from switchToNotificationWindow to switchToWindowWithTitle as part of the PR #26562 and it failed with the below error message.

```
  <testsuite name="Root Suite" timestamp="2024-08-21T02:23:25" tests="0" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Test Snap Dialog" timestamp="2024-08-21T02:23:25" tests="1" file="/home/circleci/project/test/e2e/snaps/test-snap-dialog.spec.js" time="37.976" failures="1">
    <testcase name="Test Snap Dialog test all three snap_dialog types" time="37.971" classname="test all three snap_dialog types">
      <failure message="no such window
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 10 of 20, Job test-e2e-chrome-webpack)" type="NoSuchWindowError"><![CDATA[NoSuchWindowError: no such window
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 10 of 20, Job test-e2e-chrome-webpack)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at WindowHandles.switchToHandleAndCheckForProperty (test/e2e/background-socket/window-handles.ts:204:5)
    at WindowHandles.switchToWindowWithProperty (test/e2e/background-socket/window-handles.ts:161:31)
    at async Driver.switchToWindowWithTitle (test/e2e/webdriver/driver.js:973:12)
    at async /home/circleci/project/test/e2e/snaps/test-snap-dialog.spec.js:162:9
    at async withFixtures (test/e2e/helpers.js:212:5)
    at async Context.<anonymous> (test/e2e/snaps/test-snap-dialog.spec.js:13:5)]]></failure>
    </testcase>
  </testsuite>
</testsuites>
```

Original CI failure when documenting the ticket
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/95206/workflows/bc6dd862-2773-4f4a-8f87-3e729694cb30/jobs/3544347/tests

**Comment by hjetpoluru** [comment]
PR fixed https://github.com/MetaMask/metamask-extension/pull/26598
