### ISSUE TITLE
[Bug]: Import/Watch ERC1155 token not working

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#26424]
### Describe the bug

ERC1155 tokens will give infinite loading when manually imported. After several tries, and locking-unlocking the wallet, the token will show up, but the image will not be displayed even with Display NFT media toggled ON. Trying the Watch ERC1155 asset from testdapp will show the attached console error and does not trigger the app prompt to confirm addition of custom token. This functionality worked in 16.6.0, I tested it together with CS back then. 

### Expected behavior

NFT can be imported as expected, NFT image is displayed and NFT can be watched from Test Dapp.

### Screenshots/Recordings

![image](https://github.com/user-attachments/assets/9d68fd3e-4f67-4b8c-b433-62939f76844a)

https://github.com/user-attachments/assets/e808f18d-bbae-4da9-8e52-7eac1976508d

### Steps to reproduce

1. Load MetaMask, switch to a testnet (e.g. Sepolia)
2. Go to the Test Dapp. 
3. Deploy ERC1155 token --> Mint batch tokens
4. Watch ERC1155 asset - notice it does not trigger a prompt in the app and a console error shows up in the test dapp background console (not MM).
5. Go to the activity list item "Mint Batch" --> View on block explorer
6. Copy token contract address and import NFT - notice it gets stuck in loading and closing with "x" does not help. After locking/unlocking wallet, the token is displayed under NFTs.

### Error messages or log output

```shell
index.js:1523 
Error: MetaMask is not connected/installed, please call eth_requestAccounts to connect first.
    at eval (metamask-sdk.js:5:215686)
    at Generator.next (<anonymous>)
    at eval (metamask-sdk.js:1:717587)
    at new Promise (<anonymous>)
    at yS (metamask-sdk.js:1:717337)
    at E (metamask-sdk.js:5:210648)
    at eval (metamask-sdk.js:5:216006)
    at Generator.next (<anonymous>)
    at eval (metamask-sdk.js:1:717587)
    at new Promise (<anonymous>)
﻿
```

### Detection stage

During release testing

### Version

12.1.0, 12.0.0

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by Gudahtt** [comment]
I'm having trouble reproducing. I tried this with production (v12.0.5), but I followed slightly different testing steps in that I clicked "Use window.ethereum" after connecting to rule out an SDK-related bug. The errors suggest that the SDK might be misconfigured, as the dapp is clearly connected but you're seeing errors from the SDK about it not being connected.

**Comment by sleepytanya** [comment]
I see the same error message in a different case where I try to start the tx with malicious payload:

<img width="505" alt="Screenshot 2024-08-16 at 17 22 02" src="https://github.com/user-attachments/assets/124e221c-93cb-44cb-bce0-a7f1a04f6967">

**Comment by Gudahtt** [comment]
@sleepytanya is this with the Test Dapp? try clicking "Use window.ethereum" first to rule out an SDK issue specific to the test dapp. If window.ethereum works, then this is either a bug with the SDK or with the test-dapp, not with the extension.

**Comment by Gudahtt** [comment]
I was able to reproduce the bug with manual import. Similarly to as described, the form appears unresponsive (no error is shown, but it remains open with an error in the dev console). But after closing and opening the popup, it looks like the NFT was imported, just without the image. The NFT name, id, and description are all correct.

So there are two issues: the NFT import partially fails, and the form is unresponsive.

The form should be responsive even if the import fails (e.g. we should tell the user what happened). And of course this should not have failed.


I'll update this to Sev2 since the feature still partially works, and this isn't especially commonly used. But we should still try to fix this as soon as we can.

I haven't tried reproducing with older versions. I'll leave this as a v12 regression for now, but it might have been introduced earlier than that.

**Comment by sleepytanya** [comment]
@Gudahtt Thank you, "Use window.ethereum" helped! Yes, I was using test dapp, initiating malicious contract interactions using console.

**Comment by sleepytanya** [comment]
@benjisclowder 
Can't reproduce on 12.0.5 and on current `develop`. But sometimes while manually importing ERC 1155 I get this error:

<img width="358" alt="Screenshot 2024-08-19 at 21 34 55" src="https://github.com/user-attachments/assets/0316fc94-fc55-4578-832f-6245f934853e">

**Comment by sleepytanya** [comment]
Tested on 11.16.16 - works fine.

Manual import:


https://github.com/user-attachments/assets/7b98b79d-f92f-4082-92f7-c822a4d01720

'Watch ERC 1155 asset":


https://github.com/user-attachments/assets/1a7430c9-b231-42f7-bf41-d10df41c7f99

**Comment by alfeng6** [comment]
given it works fine from previous testing, I'm closing
