### ISSUE TITLE
Fix "Test Snap Metrics test snap update rejected metric" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26578]
Latest CI link
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/98396/workflows/be9ffb55-3ba2-4b60-9a36-92a18a5f2511/jobs/3662206/tests

```
TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Confirm")])
Wait timed out after 10169ms
  (Ran on CircleCI Node 8 of 24, Job test-e2e-firefox)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://github.com/user-attachments/assets/f81f1660-c144-41f6-ae2f-c66378571322)

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/96587/workflows/b7beffde-c70c-4ee8-9f22-3d840f6e8a3f/jobs/3595672/tests

```
Error: listen EADDRINUSE: address already in use 127.0.0.1:8545.
  (Ran on CircleCI Node 1 of 10, Job test-e2e-firefox-flask)
    at listenSocket (webpack://Ganache/core/lib/src/server.js:193:33)
    at async Promise.allSettled (index 1)
    at Ganache.start (test/e2e/seeder/ganache.ts:23:5)
    at async withFixtures (test/e2e/helpers.js:102:7)
    at async Context.<anonymous> (test/e2e/snaps/test-snap-metrics.spec.js:666:5)
```

**Comment by chloeYue** [comment]
close this ticket as this test is not flaky anymore
