### ISSUE TITLE
Fix "Test Snap Metrics test snap update metric" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26577]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/96587/workflows/b7beffde-c70c-4ee8-9f22-3d840f6e8a3f/jobs/3595672/tests

```
Error: listen EADDRINUSE: address already in use 127.0.0.1:8545.
  (Ran on CircleCI Node 1 of 10, Job test-e2e-firefox-flask)
    at listenSocket (webpack://Ganache/core/lib/src/server.js:193:33)
    at async Promise.allSettled (index 1)
    at Ganache.start (test/e2e/seeder/ganache.ts:23:5)
    at async withFixtures (test/e2e/helpers.js:102:7)
    at async Context.<anonymous> (test/e2e/snaps/test-snap-metrics.spec.js:521:5)
```

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
