### ISSUE TITLE
Fix "Incremental Security Back up Secret Recovery Phrase ..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26608]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/96780/workflows/35899ffb-e3e1-48a0-99b8-21ab76a14095/jobs/3603629/tests

```
Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /home/circleci/project/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,chrome,--output,json,--browser-version,126: error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json): error trying to connect: dns error: failed to lookup address information: Try again
  (Ran on CircleCI Node 7 of 20, Job test-e2e-chrome-webpack)
    at getPath (node_modules/selenium-webdriver/common/driverFinder.js:35:11)
    at thenableWebDriverProxy.createSession (node_modules/selenium-webdriver/chromium.js:696:45)
    at thenableWebDriverProxy.createSession (node_modules/selenium-webdriver/chrome.js:223:13)
    at createDriver (node_modules/selenium-webdriver/index.js:152:33)
    at Builder.build (node_modules/selenium-webdriver/index.js:680:16)
    at ChromeDriver.build (test/e2e/webdriver/chrome.js:106:28)
    at buildBrowserWebDriver (test/e2e/webdriver/index.js:38:33)
    at buildWebDriver (test/e2e/webdriver/index.js:20:13)
    at withFixtures (test/e2e/helpers.js:182:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (test/e2e/tests/account/incremental-security.spec.js:24:5)
```

**Comment by chloeYue** [comment]
Close this ticket as the test is not flaky anymore
