### ISSUE TITLE
Fix "ERC721 NFTs testdapp interaction should prompt users..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26611]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/96870/workflows/4cc4154d-6ffd-47eb-8366-5f6aeddafbad/jobs/3605974/tests

```
StaleElementReferenceError: stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 1 of 20, Job test-e2e-chrome)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async /home/circleci/project/test/e2e/tests/tokens/nft/erc721-interaction.spec.js:246:22
    at async withFixtures (test/e2e/helpers.js:212:5)
    at async Context.<anonymous> (test/e2e/tests/tokens/nft/erc721-interaction.spec.js:205:5)
```

Test level error and CI link
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/96870/workflows/4cc4154d-6ffd-47eb-8366-5f6aeddafbad/jobs/3605974/parallel-runs/1?filterBy=ALL
```
2024-08-22T04:53:52.552Z [driver] Called 'clickElement' with arguments ["[data-testid=\"account-overview__activity-tab\"]"]
2024-08-22T04:53:52.713Z [driver] Called 'waitForSelector' with arguments [{"css":"[data-testid=\"activity-list-item-action\"]","text":"Deposit"}]
Failure on testcase: 'ERC721 NFTs testdapp interaction should prompt users to add their NFTs to their wallet (all at once)', for more information see the artifacts tab in CI

StaleElementReferenceError: stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.182)
```

Potential issue could be on the notification dialog not appearing
<img width="1053" alt="Screenshot 2024-08-22 at 9 22 00 AM" src="https://github.com/user-attachments/assets/49ff38f8-aa69-46da-ba83-87a8c722e502">

**Comment by chloeYue** [comment]
This test is still flaky.
CI failure:
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102315/workflows/651c8afc-5875-4ffb-8915-aff23faa1978/jobs/3812517/tests
