### ISSUE TITLE
[Bug]: Brave browser - Unable to login into MM wallet - ‘Account Id not found’ error

### ISSUE THREAD

**Issue by swatisqa1** [MetaMask/metamask-extension#26623]
### Describe the bug

I’m trying to log into my MM wallet on the Brave Browser on my macbook. When I try to load the login screen, I get the spinning loader icon and no password field appears.

Upon investigation using the Dev Tools and Inspect Element of the MM popup - I see there is an Unhandled exception thrown ‘Account Id not found’.

I was able to log into MM wallet on July 29th ‘24 and since then I have not been able to login. 

Actions tried:
I’ve tried to upgraded to MM Wallet 12.0.0 and 12.0.1 and upgraded my Brave browser and none of those actions helped resolved the error.

PreCondition:
MacOS: 12.7.6
Brave Version: Version 1.68.141 Chromium: 127.0.6533.120 (Official Build) (x86_64)
MetaMask Wallet: 12.0.1

### Expected behavior

See the password field in the MM wallet login screen

### Screenshots/Recordings

<img width="1280" alt="Screen Shot 2024-08-22 at 12 59 35 PM" src="https://github.com/user-attachments/assets/e108f6b6-401f-4bce-9056-66d6baecd1c6">
<img width="1280" alt="Screen Shot 2024-08-22 at 1 01 43 PM" src="https://github.com/user-attachments/assets/5c3d252e-b195-466f-8fa3-8a241cf3eb12">
<img width="1280" alt="Screen Shot 2024-08-22 at 1 00 22 PM" src="https://github.com/user-attachments/assets/7e92795f-c557-4088-b7e3-46cab113ef23">
<img width="1280" alt="Screen Shot 2024-08-22 at 1 00 11 PM" src="https://github.com/user-attachments/assets/ec18566d-fc92-4cdc-9bc1-fbfb5b749b7e">
<img width="1280" alt="Screen Shot 2024-08-22 at 1 02 01 PM" src="https://github.com/user-attachments/assets/22dde322-a468-43a4-8f6d-c87f52bcf612">

### Steps to reproduce

1. Click on Fox icon in Brave Browser
2. Login page tried to load with a spinning icon

### Error messages or log output

```shell
background-6.js:1 Uncaught (in promise) Error: Account Id "fcec9c0a-e719-45be-8926-dcbf868a3209" not found
  at U.getAccountExpect (background-0.js:1:11127)
  at U.getSelectedAccount (background-0.js:1:11211)
  at new At (background-0.js:1:198947)
  at ue (background-6.js:1:6729)
  at se (background-6.js:1:4361)
```

### Detection stage

In production (default)

### Version

12.1.0

### Build type

Other (please specify exactly where you obtained this build in "Additional Context" section)

### Browser

Brave

### Operating system

MacOS

### Additional context

Hello! I'm a prod user of MetaMask wallet and have been locked since July 30th. I'm a QAE so did my own troubleshooting to get to the root cause of seeing an unhandled exception error thrown from MM wallet. I'm happy to help to resolve this issue. :)

### Severity

-This is impacting Production users

**Comment by swatisqa1** [comment]
Any updates here...? Looks like this is a known production issue - please fix when you can. Thanks!

**Comment by swatisqa1** [comment]
Welcome back! Just checking in on this Production Issue - is this fixed in MM wallet version 12.1.1...? Thank you for looking into this! @katkopel @metamaskbot

**Comment by anaamolnar** [comment]
@Gudahtt This is the issue I have been telling you about

**Comment by gantunesr** [comment]
Hi @swatisqa1, we're currently working on this and finding the root cause has been complicated. Can you confirm if this issue persists in latest released version v12.1.3 on your end? If possible, please provide an answer in the new linked issue https://github.com/MetaMask/metamask-extension/issues/26377
