### ISSUE TITLE
Fix "Swap-Send ETH @no-mmi to non-contract address with d..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26637]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/97074/workflows/1c36504d-4969-4968-bb45-203eaade1e92/jobs/3613279/tests

Test scenario - Swap-Send ETH @no-mmi to non-contract address with data that matches swap data signature submits a transaction successfully
Browser - Chrome
Build - Regular extension
Test path - test/e2e/tests/swap-send/swap-send-eth.spec.ts

```
NoSuchWindowError: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=126.0.6478.182)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async thenableWebDriverProxy.findElements (node_modules/selenium-webdriver/lib/webdriver.js:1089:17)
```
console log error 
```
-----Received an error from Chrome-----
Request Storage.getStorageKeyForFrame failed. {"code":-32602,"message":"Frame tree node for given frame not found"}
Request Storage.getStorageKeyForFrame failed. {"code":-32602,"message":"Frame tree node for given frame not found"}
----------End of Chrome error----------
```

**Comment by hjetpoluru** [comment]
Fix in PR #27067
