### ISSUE TITLE
Fix "ERC721 NFTs testdapp interaction should add NFTs to ..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26759]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/97720/workflows/1a1a28d2-9df6-4d5d-b0fb-e8914146cb70/jobs/3637068/tests

```
StaleElementReferenceError: stale element reference: stale element not found in the current frame
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 1 of 20, Job test-e2e-chrome)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async /home/circleci/project/test/e2e/tests/tokens/nft/erc721-interaction.spec.js:58:22
    at async withFixtures (test/e2e/helpers.js:212:5)
    at async Context.<anonymous> (test/e2e/tests/tokens/nft/erc721-interaction.spec.js:17:5)
```

**Comment by chloeYue** [comment]
This test is still flaky: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101772/workflows/fd4789c8-7368-4743-83be-5c957eddfa24/jobs/3789310
