### ISSUE TITLE
[Bug]: Multi RPC - each time there's an attempt to switch between networks, an error in the console is encountered •Uncaught (in promise) common-0. j5:1 TypeError: Cannot perform 'get' on a proxy that has been revoked

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#26835]
### Describe the bug

Each time there's an attempt to switch between networks, an error in the console is displayed, networks can be switched as expected.

### Expected behavior

-

### Screenshots/Recordings

https://github.com/user-attachments/assets/728f9ca6-81ae-4e30-a8b3-6fefeaf924c5

<img width="491" alt="Screenshot 2024-09-02 at 00 44 38" src="https://github.com/user-attachments/assets/ef70c4d2-2d4a-4b5f-8bb9-e5f046845c95">

### Steps to reproduce

1. Switch networks

### Error messages or log output

```shell
Uncaught (in promise) TypeError: Cannot perform 'get' on a proxy that has been revoked
  at G.R (common-0.js:1:566170)
  at common-0.js:1:565369
  at r.ControllerMessenger.publish (background-0.js:1:253283)
  at r.RestrictedControllerMessenger.publish (background-0.js:1:258836)
  at ae.O (common-1.js:1:308810)
  at ae.setActiveNetwork (common-1.js:1:302195)
  at Object.setActiveNetwork (background-0.js:1:197228)
  at i.<anonymous> (background-4.js:3:276634)
  at i.emit (common-5.js:1:185062)
  at S (common-7.js:1:232018)
  at x (common-7.js:1:231848)
  at k.push (common-7.js:1:232635)
  at c._write (common-1.js:1:515872)
  at x (common-7.js:1:246517)
  at common-7.js:1:249617
  at k.write (common-7.js:1:249644)
  at i.l (common-5.js:1:233565)
  at i.emit (common-5.js:1:185062)
  at H (common-5.js:1:227247)
  at F (common-5.js:1:226977)
  at L.push (common-5.js:1:227577)
  at i._onMessage (common-5.js:1:188620)
  at common-5.js:1:188416
```

### Detection stage

On the development branch

### Version

12.0.5

### Build type

None

### Browser

Chrome

### Operating system

MacOS

### Additional context

Build https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/97568/workflows/28d6cb81-d0e8-410f-ae41-7f8b6cc5c5a9/jobs/3631842/artifacts

**Comment by salimtb** [comment]
hey @sleepytanya ,
same here it has been addressed on the latest build.
you can find it [here](https://github.com/MetaMask/metamask-extension/pull/26433#issuecomment-2323795439)

https://github.com/user-attachments/assets/928a4a1d-e333-4f0c-afd2-a941dce996a3

**Comment by bergeron** [comment]
This was resolved in a previous version by https://github.com/MetaMask/core/pull/4286/commits/02e7ff99c640127d9b08c80f0951f1141c16b3c6
