### ISSUE TITLE
Fix "Test Snap Metrics tests snap install metric" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26865]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/98396/workflows/be9ffb55-3ba2-4b60-9a36-92a18a5f2511/jobs/3662206/tests

Test scenario - Test Snap Metrics tests snap install metric

```
Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /home/circleci/project/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,firefox,--output,json,--browser-path,/opt/firefox/firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: dns error: failed to lookup address information: Try again
  (Ran on CircleCI Node 8 of 24, Job test-e2e-firefox)
    at getPath (node_modules/selenium-webdriver/common/driverFinder.js:35:11)
    at thenableWebDriverProxy.createSession (node_modules/selenium-webdriver/firefox.js:594:45)
    at createDriver (node_modules/selenium-webdriver/index.js:152:33)
    at Builder.build (node_modules/selenium-webdriver/index.js:688:16)
    at FirefoxDriver.build (test/e2e/webdriver/firefox.js:97:28)
    at buildBrowserWebDriver (test/e2e/webdriver/index.js:41:34)
    at buildWebDriver (test/e2e/webdriver/index.js:20:13)
    at withFixtures (test/e2e/helpers.js:182:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (test/e2e/snaps/test-snap-metrics.spec.js:170:5)
```
Error message from the console log

```
      <failure message="Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /home/circleci/project/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,firefox,--output,json,--browser-path,/opt/firefox/firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: dns error: failed to lookup address information: Try again
  (Ran on CircleCI Node 8 of 24, Job test-e2e-firefox)" type="Error"><![CDATA[Error: Unable to obtain browser driver.
        For more information on how to install drivers see
        https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /home/circleci/project/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,firefox,--output,json,--browser-path,/opt/firefox/firefox: error sending request for url (https://github.com/mozilla/geckodriver/releases/latest): error trying to connect: dns error: failed to lookup address information: Try again
  (Ran on CircleCI Node 8 of 24, Job test-e2e-firefox)
    at getPath (node_modules/selenium-webdriver/common/driverFinder.js:35:11)
    at thenableWebDriverProxy.createSession (node_modules/selenium-webdriver/firefox.js:594:45)
    at createDriver (node_modules/selenium-webdriver/index.js:152:33)
    at Builder.build (node_modules/selenium-webdriver/index.js:688:16)
    at FirefoxDriver.build (test/e2e/webdriver/firefox.js:97:28)
    at buildBrowserWebDriver (test/e2e/webdriver/index.js:41:34)
    at buildWebDriver (test/e2e/webdriver/index.js:20:13)
    at withFixtures (test/e2e/helpers.js:182:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (test/e2e/snaps/test-snap-metrics.spec.js:170:5)]]></failure>
```

Successful execution on the second retry

```
Executing testcase: 'Test Snap Metrics tests snap install metric'

2024-09-03T08:32:03.184Z [driver] Called 'navigate' with arguments []
2024-09-03T08:32:04.523Z [driver] Called 'fill' with arguments ["#password","correct horse battery staple"]
2024-09-03T08:32:04.712Z [driver] Called 'press' with arguments ["#password",""]
2024-09-03T08:32:04.733Z [driver] Called 'assertElementNotPresent' with arguments ["[data-testid=\"unlock-page\"]"]
2024-09-03T08:32:05.925Z [driver] Called 'openNewPage' with arguments ["https://metamask.github.io/snaps/test-snaps/2.13.0/"]
2024-09-03T08:32:22.663Z [driver] Called 'waitForSelector' with arguments [{"text":"Installed Snaps","tag":"h2"}]
2024-09-03T08:32:22.691Z [driver] Called 'findElement' with arguments ["#connectnotifications"]
2024-09-03T08:32:22.694Z [driver] Called 'scrollToElement' with arguments [{"driver_":{"session_":{},"executor_":{"customCommands_":{},"log_":{"name_":"driver.http.Executor","level_":null,"parent_":{"name_":"driver.http","level_":null,"parent_":{"name_":"driver","level_":null,"parent_":{"name_":""
2024-09-03T08:32:22.698Z [driver] Called 'delay' with arguments [1000]
2024-09-03T08:32:23.698Z [driver] Called 'clickElement' with arguments ["#connectnotifications"]
2024-09-03T08:32:23.977Z [driver] Called 'switchToWindowWithTitle' with arguments ["MetaMask Dialog"]
2024-09-03T08:32:24.105Z [driver] Called 'clickElement' with arguments [{"text":"Connect","tag":"button"}]
2024-09-03T08:32:25.437Z [driver] Called 'waitForSelector' with arguments [{"text":"Confirm"}]
2024-09-03T08:32:26.136Z [driver] Called 'clickElement' with arguments [{"text":"Confirm","tag":"button"}]
2024-09-03T08:32:26.247Z [driver] Called 'waitForSelector' with arguments [{"text":"OK"}]
2024-09-03T08:32:26.281Z [driver] Called 'clickElement' with arguments [{"text":"OK","tag":"button"}]
2024-09-03T08:32:27.037Z [driver] Called 'wait' with arguments [null,10000,true]

Success on testcase: 'Test Snap Metrics tests snap install metric'
```

**Comment by hjetpoluru** [comment]
Console log error means that the failing due to a DNS error, which prevents the test from connecting to the GitHub repository to download the geckodriver (the WebDriver for Firefox).

**Comment by hjetpoluru** [comment]
Closing this ticket as it was an intermittent issue. If it appears again, it should be analyzed, and retry logic should be written to fetch the geckodriver.
