### ISSUE TITLE
Fix "Encrypt Decrypt should show balance correctly as Fia..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26863]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/98302/workflows/ec2f5dcb-72c6-4584-b716-8c0dacff2810/jobs/3658508/tests

Test scenario - Encrypt Decrypt should show balance correctly as Fiat

```
Error: Found element "[data-testid=\"unlock-page\"]" that should not be present
  (Ran on CircleCI Node 11 of 12, Job test-e2e-chrome-mmi)
    at Driver.assertElementNotPresent (test/e2e/webdriver/driver.js:456:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async unlockWallet (test/e2e/helpers.js:969:5)
    at async /home/circleci/project/test/e2e/tests/dapp-interactions/encrypt-decrypt.spec.js:214:9
    at async withFixtures (test/e2e/helpers.js:212:5)
    at async Context.<anonymous> (test/e2e/tests/dapp-interactions/encrypt-decrypt.spec.js:199:5)
```

![image](https://github.com/user-attachments/assets/aa9c45f7-e4e7-41a7-a2b9-2ebabf8600f5)

**Comment by chloeYue** [comment]
Close this ticket as this test is not flaky anymore
