### ISSUE TITLE
Fix "Dapp viewed Event @no-mmi is sent when refreshing da..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26899]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/98663/workflows/e99246eb-772f-4339-aacb-b3ebe039e54f/jobs/3672023/tests

```
Expected values to be strictly equal:
+ actual - expected

+ undefined
- false
  (Ran on CircleCI Node 12 of 20, Job test-e2e-chrome-webpack)
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ undefined
- false
    at /home/circleci/project/test/e2e/tests/metrics/dapp-viewed.spec.js:197:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withFixtures (test/e2e/helpers.js:212:5)
    at async Context.<anonymous> (test/e2e/tests/metrics/dapp-viewed.spec.js:172:5)

      + expected - actual:  failed to generate Mocha diff
```

**Comment by chloeYue** [comment]
this test is still flaky. 
CI failure: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102346/workflows/3d79e5dc-c1ea-4418-acc6-4601394f647e/jobs/3813643

**Comment by hjetpoluru** [comment]
Fix in PR 27381
