### ISSUE TITLE
Fix "Settings Search should find element inside the Gener..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#26934]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/98697/workflows/b9dbe0bf-ad5a-4928-b485-94fe32670f10/jobs/3673422/tests

Build - mmi
Browser - chrome

```
Error: Found element "[data-testid=\"unlock-page\"]" that should not be present
  (Ran on CircleCI Node 9 of 12, Job test-e2e-chrome-mmi)
    at Driver.assertElementNotPresent (test/e2e/webdriver/driver.js:456:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async unlockWallet (test/e2e/helpers.js:969:5)
    at async /home/circleci/project/test/e2e/tests/settings/settings-search.spec.js:30:9
    at async withFixtures (test/e2e/helpers.js:212:5)
    at async Context.<anonymous> (test/e2e/tests/settings/settings-search.spec.js:23:5)
```

![image](https://github.com/user-attachments/assets/0dbaec56-567c-4100-b3f8-53e0d58b6b1d)

**Comment by chloeYue** [comment]
close this test as this test is not flaky anymore
