### ISSUE TITLE
Fix "Settings - general tab @no-mmi validate the change l..." flaky tests

### ISSUE THREAD

**Issue by seaona** [MetaMask/metamask-extension#27020]
Latest CI failure reported on Dec 3rd https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/113658/workflows/815e13da-71ae-40dd-ba4f-4f9deef5b397/jobs/4259856/parallel-runs/16?filterBy=ALL

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/99355/workflows/38f4f9d2-8f7b-4189-bb2a-15b9bab68728/jobs/3698478/tests

Build - Webpack
Browser - Chrome
Test Scenario - Settings - general tab @no-mmi validate the change language functionality
Test Path - /test/e2e/tests/settings/change-language.spec.ts

```
Error: failed to fetch es locale because of TypeError: Failed to fetch
  (Ran on CircleCI Node 14 of 20, Job test-e2e-chrome-webpack)
    at withFixtures (test/e2e/helpers.js:224:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (test/e2e/tests/settings/change-language.spec.ts:2:2706)
```
![image](https://github.com/user-attachments/assets/0d735ad1-bcdb-4288-9cd0-009a3b6c8f7c)

Console error
```
-----Received an error from Chrome-----
failed to fetch es locale because of TypeError: Failed to fetch
----------End of Chrome error----------
```

**Comment by chloeYue** [comment]
this test is still flaky: 
CI failure: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102303/workflows/7ea36a5f-0909-4d0d-be7d-99f391b07c64/jobs/3811931

**Comment by chloeYue** [comment]
close this one because duplicate with https://github.com/MetaMask/metamask-extension/issues/27390

**Comment by hjetpoluru** [comment]
Re-opening this ticket as it still flaky and its not addressed. Here is the link for the latest failure - https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/113658/workflows/815e13da-71ae-40dd-ba4f-4f9deef5b397/jobs/4259856/tests
