### ISSUE TITLE
Fix "Trezor Hardware unlocks the first account" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27105]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/99981/workflows/74b00c47-b958-437d-9e4b-9b9940383de2/jobs/3721933/tests

Test scenario - Trezor Hardware unlocks the first account
Test path - test/e2e/tests/hardware-wallets/trezor-account.spec.js
Build - Webpack

```
Error: listen EADDRINUSE: address already in use 127.0.0.1:8545.
  (Ran on CircleCI Node 17 of 20, Job test-e2e-chrome-webpack)
    at /home/circleci/project/node_modules/ganache/dist/node/1.js:2:5133
    at async Promise.allSettled (index 1)
    at async Ganache.start (test/e2e/seeder/ganache.ts:2:1285)
    at async withFixtures (test/e2e/helpers.js:105:7)
    at async Context.<anonymous> (test/e2e/tests/hardware-wallets/trezor-account.spec.js:64:5)
```

**Comment by chloeYue** [comment]
close this ticket as this test is not flaky anymore
