### ISSUE TITLE
Fix "Account Tracker API Usage should not make eth_call o..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27128]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/100098/workflows/719e41e8-7f60-4096-ac82-faeab6ca6b75/jobs/3726918/tests

Test scenario - Account Tracker API Usage should not make eth_call or eth_getBalance or eth_getBlockByNumber requests after the UI is closed
Test path - test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts
Build - webpack
Browser - Chrome

```
An eth_getBlockByNumber or eth_call or eth_getBalance request has been made to infura after closing the UI
  (Ran on CircleCI Node 11 of 20, Job test-e2e-chrome-webpack)
AssertionError [ERR_ASSERTION]: An eth_getBlockByNumber or eth_call or eth_getBalance request has been made to infura after closing the UI
    at /home/circleci/project/test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts:2:4721
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts:2:3870)

      + expected - actual

      -false
      +true
```

![image](https://github.com/user-attachments/assets/4aec9efe-8848-4315-9d31-53d5452c7264)

Console log
```
Executing testcase: 'Account Tracker API Usage should not make eth_call or eth_getBalance or eth_getBlockByNumber requests after the UI is closed'

2024-09-12T15:58:24.703Z [driver] Called 'navigate' with arguments []
ServerMochaToBackground got a client connection
2024-09-12T15:58:33.244Z [driver] Called 'fill' with arguments ["#password","correct horse battery staple"]
2024-09-12T15:58:34.135Z [driver] Called 'press' with arguments ["#password",""]
2024-09-12T15:58:34.193Z [driver] Called 'assertElementNotPresent' with arguments ["[data-testid=\"unlock-page\"]"]
2024-09-12T15:58:37.209Z [driver] Called 'delay' with arguments [1600]
2024-09-12T15:58:38.810Z [driver] Called 'openNewURL' with arguments ["about:blank"]
2024-09-12T15:58:39.028Z [driver] Called 'delay' with arguments [20000]
Failure on testcase: 'Account Tracker API Usage should not make eth_call or eth_getBalance or eth_getBlockByNumber requests after the UI is closed', for more information see the artifacts tab in CI

AssertionError [ERR_ASSERTION]: An eth_getBlockByNumber or eth_call or eth_getBalance request has been made to infura after closing the UI

ServerMochaToBackground disconnected from client
manifest-flag-mocha-hooks.ts -- afterEach hook
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="55.159" tests="2" failures="1">
  <testsuite name="Root Suite" timestamp="2024-09-12T15:58:04" tests="0" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Account Tracker API Usage" timestamp="2024-09-12T15:58:04" tests="2" file="/home/circleci/project/test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts" time="55.158" failures="1">
    <testcase name="Account Tracker API Usage should not make eth_call or eth_getBalance requests before the UI is opened and should make those requests after the UI is opened" time="18.112" classname="should not make eth_call or eth_getBalance requests before the UI is opened and should make those requests after the UI is opened">
    </testcase>
    <testcase name="Account Tracker API Usage should not make eth_call or eth_getBalance or eth_getBlockByNumber requests after the UI is closed" time="37.023" classname="should not make eth_call or eth_getBalance or eth_getBlockByNumber requests after the UI is closed">
      <failure message="An eth_getBlockByNumber or eth_call or eth_getBalance request has been made to infura after closing the UI
  (Ran on CircleCI Node 11 of 20, Job test-e2e-chrome-webpack)" type="AssertionError"><![CDATA[AssertionError [ERR_ASSERTION]: An eth_getBlockByNumber or eth_call or eth_getBalance request has been made to infura after closing the UI
    at /home/circleci/project/test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts:2:4721
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/tests/api-usage/account-tracker-api-usage.spec.ts:2:3870)

      + expected - actual

      -false
      +true
      ]]></failure>
    </testcase>
  </testsuite>
</testsuites>
retry() received: Exited with code '1'
Error occurred while running tests on chrome: Error: Retry limit reached
Error: Exited with code '1'
    at runInShell (/home/circleci/project/development/lib/run-command.js:134:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/home/circleci/project/test/e2e/run-all.js:268:7)

Exited with code exit status 1

```

**Comment by chloeYue** [comment]
This test is still flaky. CI failure: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102294/workflows/134938c0-c4db-4eb6-af09-06847c066428/jobs/3811490
