### ISSUE TITLE
Fix "MetaMask onboarding @no-mmi should not prevent netwo..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27301]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101355/workflows/8be10911-cef5-4f14-978a-eb342502029c/jobs/3778277/tests

```
Error: A new host not contained in the privacy-snapshot received a network
           request during test execution. Please update the privacy-snapshot
           file by passing the --update-privacy-snapshot option to the test
           command or add the new hosts to the snapshot manually.

           New hosts found: user-storage.api.cx.metamask.io.
  (Ran on CircleCI Node 2 of 20, Job test-e2e-chrome-webpack)
    at withFixtures (test/e2e/helpers.js:264:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Context.<anonymous> (test/e2e/tests/privacy/basic-functionality.spec.js:94:5)
```

**Comment by hjetpoluru** [comment]
URL - user-storage.api.cx.metamask.io has been added privacy snapshot in the [PR](https://github.com/MetaMask/metamask-extension/pull/27292) and hence its fixed and closing the ticket
