### ISSUE TITLE
Fix "Request-queue UI changes should gracefully handle de..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27304]
CI failure link reported on Sept 24
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101984/workflows/4668d4c0-22db-4750-b0b9-3b95f5661ac0/jobs/3798329/tests

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101369/workflows/6c8551cb-1b8c-4ff5-a912-889d65e289b2/jobs/3774008/tests

Build - Regular
Browser - Chrome
Test Scenario - Request-queue UI changes should gracefully handle deleted network @no-mmi
Test Path - /test/e2e/tests/request-queuing/ui.spec.js

```
TypeError: Cannot destructure property 'metamask' of 'notificationWindowState' as it is null.
  (Ran on CircleCI Node 0 of 20, Job test-e2e-chrome)
    at switchToDialogPopoverValidateDetails (test/e2e/tests/request-queuing/ui.spec.js:111:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/circleci/project/test/e2e/tests/request-queuing/ui.spec.js:434:9
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/tests/request-queuing/ui.spec.js:369:5)
```

**Comment by hjetpoluru** [comment]
This flaky test is due to this [change ](https://github.com/MetaMask/metamask-extension/pull/26433/files#diff-b1599783c028717a6eb6907b421be7d3482f9ebb4d7ac2ed8acde927e560d98a) and assigned to @MetaMask/metamask-assets. Please let me know if you require any further assistance.
