### ISSUE TITLE
Fix "Update Network: should delete added rpc url for exis..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27334]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/101672/workflows/e38c0e67-5e2a-4920-b83c-4fdf588ddd2f/jobs/3785936/tests

Build - Regular
Browser - Firefox
Test Scenario - Update Network: should delete added rpc url for existing network
Test Path - /test/e2e/tests/network/update-network.spec.ts

```
ElementClickInterceptedError: Element <button class="mm-box mm-picker-network multichain-app-header__contents__network-picker mm-box--margin-2 mm-box--padding-right-4 mm-box--padding-left-2 mm-box--display-none mm-box--sm:display-flex mm-box--gap-2 mm-box--align-items-center mm-box--background-color-background-alternative mm-box--rounded-pill"> is not clickable at point (218,125) because another element <div class="popover-bg"> obscures it
  (Ran on CircleCI Node 16 of 24, Job test-e2e-firefox)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async element.click (test/e2e/webdriver/driver.js:94:9)
    at async Driver.clickElement (test/e2e/webdriver/driver.js:579:9)
    at async /home/circleci/project/test/e2e/tests/network/update-network.spec.ts:2:6316
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/tests/network/update-network.spec.ts:2:4536)
```

![image](https://github.com/user-attachments/assets/5bb2de44-ffa8-4b71-837e-f4d329c122aa)

**Comment by hjetpoluru** [comment]
Reason for reopening the test scenario:

- The test has flaked again, here is [recent CI link](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/103685/workflows/b86eb89b-d666-4161-880f-3d5b25853519/jobs/3865017/tests#f%5B%E2%80%A6%5D0), and the [fix](https://github.com/MetaMask/metamask-extension/pull/27350) is not helpful.

- With reference to the [comment here](https://github.com/MetaMask/metamask-extension/pull/27437#discussion_r1778432824), the dialog appearing may be due to some incorrect mocks and should be fixed in the test itself, as the dialog does not appear during manual testing of the same scenario. Alternative if that is not possible as suggested by @seaona should be implemented.

**Comment by hjetpoluru** [comment]
Addressed again in this PR https://github.com/MetaMask/metamask-extension/pull/27437
