### ISSUE TITLE
Fix "Update Network: should update added rpc url for exis..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27422]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102184/workflows/bfe4044c-c8e3-4592-b72b-6442957fc42a/jobs/3807212/tests

Build - Regular
Browser - Firefox
Test scenario - Update Network: should update added rpc url for existing network
Test Path - /test/e2e/tests/network/update-network.spec.ts

```
ElementClickInterceptedError: Element <button class="mm-box mm-picker-network multichain-app-header__contents__network-picker mm-box--margin-2 mm-box--padding-right-4 mm-box--padding-left-2 mm-box--display-none mm-box--sm:display-flex mm-box--gap-2 mm-box--align-items-center mm-box--background-color-background-alternative mm-box--rounded-pill"> is not clickable at point (218,125) because another element <div class="popover-bg"> obscures it
  (Ran on CircleCI Node 13 of 24, Job test-e2e-firefox)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async element.click (test/e2e/webdriver/driver.js:94:9)
    at async Driver.clickElement (test/e2e/webdriver/driver.js:579:9)
    at async /home/circleci/project/test/e2e/tests/network/update-network.spec.ts:2:9037
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/tests/network/update-network.spec.ts:2:7120)
```

![image](https://github.com/user-attachments/assets/d1a87e83-3346-4849-9a4b-216d0999fe6c)

**Comment by hjetpoluru** [comment]
Fixed in PR https://github.com/MetaMask/metamask-extension/pull/27437

**Comment by hjetpoluru** [comment]
It has[ flaked again](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/102974/workflows/b7dff65d-661f-4bb6-a8d5-d32ff34be250/jobs/3837339/tests) and re-opening the issue.

**Comment by chloeYue** [comment]
Close this ticket as this test didn't flaky in past 2 weeks
