### ISSUE TITLE
Fix "eth_coinbase executes a eth_coinbase json rpc call" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27850]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/104717/workflows/c5f58758-b81a-41ee-8d76-9babc1327098/jobs/3904591/tests

Build - rpc
Browser - Chrome
Test Scenario - eth_coinbase executes a eth_coinbase json rpc call
Test Path - /test/e2e/json-rpc/eth_coinbase.spec.ts

```
JavascriptError: javascript error: Cannot read properties of null (reading 'querySelector')
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 0 of 1, Job test-e2e-chrome-rpc)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async ChromeDriver.getExtensionIdByName (test/e2e/webdriver/chrome.js:131:12)
    at async ChromeDriver.build (test/e2e/webdriver/chrome.js:108:25)
    at async buildBrowserWebDriver (test/e2e/webdriver/index.js:38:14)
    at async buildWebDriver (test/e2e/webdriver/index.js:20:7)
    at async withFixtures (test/e2e/helpers.js:187:15)
    at async Context.<anonymous> (test/e2e/json-rpc/eth_coinbase.spec.ts:2:1061)
```

**Comment by chloeYue** [comment]
Close this ticket as this test didn't flaky in past 2 weeks
