### ISSUE TITLE
Fix "Vault Decryptor Page is able to decrypt the vault pa..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#27903]
CI failure reported on Nov 19 - ([Vault Decryptor Page is able to decrypt the vault pa...](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/111316/workflows/b6a8fb89-5f4e-41d3-9fa9-025cabb57eaa/jobs/4165846/tests))

```
Waiting for element to be located By(xpath, //h2[contains(text(), "Let's get started")])
Wait timed out after 10139ms
  (Ran on CircleCI Node 0 of 1, Job test-e2e-chrome-vault-decryption)
TimeoutError: Waiting for element to be located By(xpath, //h2[contains(text(), "Let's get started")])
Wait timed out after 10139ms
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/105703/workflows/c277d0fc-f915-4227-9ec3-11cf6add030b/jobs/3945653/tests

Test scenario - Vault Decryptor Page is able to decrypt the vault pasting the text in the vault-decryptor webapp
Test path - /test/e2e/vault-decryption-chrome.spec.js

```
TimeoutError: Waiting for element to be located By(css selector, [data-testid="onboarding-terms-checkbox"])
Wait timed out after 10023ms
  (Ran on CircleCI Node 0 of 1, Job test-e2e-chrome-vault-decryption)
    at /home/circleci/project/node_modules/selenium-webdriver/lib/webdriver.js:929:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

![image](https://github.com/user-attachments/assets/5927a509-e9a6-4218-a593-45830f63fc74)

**Comment by chloeYue** [comment]
Close this ticket as it hasn't flaked in the past 10 days
