### ISSUE TITLE
Fix "Click bridge button @no-mmi loads portfolio tab from..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28070]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/107429/workflows/6bdc94c7-6acc-4671-a1a4-6209c539b830/jobs/4015247/tests

Build - Regular
Browser - Chrome
Test Scenario - Click bridge button @no-mmi loads portfolio tab from asset overview when flag is turned off
Test path - /test/e2e/tests/bridge/bridge-button-opens-portfolio.spec.ts

```
Error: No window found by background script with title: MetaMask Portfolio - Bridge
    at ServerMochaToBackground.receivedMessage (test/e2e/background-socket/server-mocha-to-background.ts:2:2485)
    at ws.onmessage (test/e2e/background-socket/server-mocha-to-background.ts:2:1916)
    at callListener (node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.emit (node:domain:488:12)
    at Receiver.dataMessage (node_modules/ws/lib/receiver.js:596:14)
    at Receiver.getData (node_modules/ws/lib/receiver.js:496:10)
    at Receiver.startLoop (node_modules/ws/lib/receiver.js:167:16)
    at Receiver._write (node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Socket.socketOnData (node_modules/ws/lib/websocket.js:1355:35)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by hjetpoluru** [comment]
After analyzing the flaky test, I observed that the @MetaMask/swaps-engineers (bridge team) has made an effort to mitigate the flakiness but more work is needed to prevent this. Therefore, I have assigned it to @MetaMask/extension-platform.

**Comment by chloeYue** [comment]
still flaky and needs investigation, failure: https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/122847/workflows/4565d974-6e99-44ea-9cad-fbda7a6810b3/jobs/4527497/tests

**Comment by SteP-n-s** [comment]
@hjetpoluru @chloeYue are you still experiencing flakiness? The latest extension builds don't redirect users to portfolio.
