### ISSUE TITLE
Fix "Switch Ethereum Chain for two dapps queues switchEth..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28195]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/108686/workflows/4a9ff2cf-f12b-4087-acb0-be51f32c3c1b/jobs/4065377/tests#failed-test-0

Build -mmi
Browser - chrome
Test scenario - Switch Ethereum Chain for two dapps queues switchEthereumChain request from second dapp after send tx request
Test Path - /test/e2e/json-rpc/switchEthereumChain.spec.js

```
ElementClickInterceptedError: element click intercepted: Element <button class="button btn--rounded btn-primary page-container__footer-button" data-testid="page-container-footer-next">...</button> is not clickable at point (266, 476). Other element would receive the click: <div class="mm-box mm-modal-content mm-box--padding-top-4 mm-box--sm:padding-top-8 mm-box--md:padding-top-12 mm-box--padding-right-4 mm-box--padding-bottom-4 mm-box--sm:padding-bottom-8 mm-box--md:padding-bottom-12 mm-box--padding-left-4 mm-box--display-flex mm-box--justify-content-center mm-box--align-items-flex-start mm-box--width-screen mm-box--height-screen">...</div>
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 0 of 1, Job test-e2e-chrome-rpc-mmi)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async element.click (test/e2e/webdriver/driver.js:96:9)
    at async Driver.clickElement (test/e2e/webdriver/driver.js:601:9)
    at async Driver.clickElementAndWaitForWindowToClose (test/e2e/webdriver/driver.js:963:5)
    at async /home/circleci/project/test/e2e/json-rpc/switchEthereumChain.spec.js:229:9
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/json-rpc/switchEthereumChain.spec.js:106:5)
```

![image](https://github.com/user-attachments/assets/bae5377c-7011-4102-8afc-ae662a189d6d)

**Comment by chloeYue** [comment]
Close this ticket as this test didn't flaky in past 2 weeks
