### ISSUE TITLE
Fix "Token List should sort alphabetically and by decreasing.." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28194]
CI failure reported on Nov 25 ([Token List should sort alphabetically and by decreas...](https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/112366/workflows/3f132a19-03e2-4826-a10e-ae061c9c8916/jobs/4207723/tests))

```
false == true
  (Ran on CircleCI Node 4 of 20, Job test-e2e-chrome-webpack)
AssertionError [ERR_ASSERTION]: false == true
    at /home/circleci/project/test/e2e/tests/tokens/token-sort.spec.ts:2:3675
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withFixtures (test/e2e/helpers.js:220:5)
    at async Context.<anonymous> (test/e2e/tests/tokens/token-sort.spec.ts:2:2158)

      + expected - actual

      -false
      +true

```
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/108675/workflows/2930881a-adee-4317-b81f-cabcd8a96e69/jobs/4064836/tests#failed-test-0

Build- webpack
Browser - chrome
Test Scenario - Token List should sort alphabetically and by decreasing balance
Test Path - /test/e2e/tests/tokens/token-sort.spec.ts

```
JavascriptError: javascript error: Cannot read properties of null (reading 'shadowRoot')
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 11 of 20, Job test-e2e-chrome-webpack)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async ChromeDriver.getExtensionIdByName (test/e2e/webdriver/chrome.js:131:12)
    at async ChromeDriver.build (test/e2e/webdriver/chrome.js:108:25)
    at async buildBrowserWebDriver (test/e2e/webdriver/index.js:38:14)
    at async buildWebDriver (test/e2e/webdriver/index.js:20:7)
    at async withFixtures (test/e2e/helpers.js:187:15)
    at async Context.<anonymous> (test/e2e/tests/tokens/token-sort.spec.ts:2:2091)
```

**Comment by chloeYue** [comment]
Close this ticket as it hasn't flaked in the past 10 days.
