### ISSUE TITLE
[Bug]: Gas fee polling on deleted RPC endpoint on activity tab

### ISSUE THREAD

**Issue by bergeron** [MetaMask/metamask-extension#28247]
### Describe the bug

After sending a transaction, then deleting the RPC endpoint it used, the activity tab is polling gas fees for the network client id that no longer exists.  Resulting in an error like:

```
 Error: No custom network client was found with the ID "79b77f69-6a4b-4f10-ae6f-9caebd138824".
    at NetworkController.getNetworkClientById (js-node_modules_meta…5ad5115.js:10811:19)
    at ControllerMessenger.call (js-node_modules_meta…75ea184.js:28147:16)
    at RestrictedControllerMessenger.call (js-node_modules_meta…5ea184.js:28392:112)
    at GasFeeController._fetchGasFeeEstimateData (js-node_modules_meta…75ea184.js:34486:56)
    at GasFeeController._executePoll (js-node_modules_meta…75ea184.js:34577:20)
    at js-node_modules_meta…5ad5115.js:30377:32
```

I haven't figured out which UI component is doing this, but presumably its taking the network client id from the transaction history state.  It could maybe use the network client id for the chain's default RPC endpoint instead, which would always be available.

I haven't been able to reproduce the error on any pages other than the activity tab.

### Screenshots/Recordings

https://github.com/user-attachments/assets/bde4a84e-b239-4f37-ba4d-0a4b9c4afc61

### Steps to reproduce

1. Send a transaction with some RPC endpoint
2. Delete the RPC endpoint used (can replace it with a different one)
3. Navigate to activity tab
4. Check background for errors

### Detection stage

In production (default)

### Version

12.5.1

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by darkwing** [comment]
Closed by Salim's PR
