### ISSUE TITLE
Fix "Request Queue SwitchChain -> WatchAsset should clear..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28381]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/109849/workflows/4075a033-ef84-46c8-9727-89a5faeb3cce/jobs/4109603/tests

Build - Regular
Browser - Firefox
Test scenario - Request Queue SwitchChain -> WatchAsset should clear subsequent watchAsset after switching chain
Test Path - /test/e2e/tests/request-queuing/switchChain-watchAsset.spec.js

```
Error: waitUntilXWindowHandles timed out polling window handles. Expected: 2, Actual: 3
  (Ran on CircleCI Node 13 of 24, Job test-e2e-firefox)
    at Driver.waitUntilXWindowHandles (test/e2e/webdriver/driver.js:1020:11)
    at async /home/circleci/project/test/e2e/tests/request-queuing/switchChain-watchAsset.spec.js:102:9
    at async withFixtures (test/e2e/helpers.js:217:5)
    at async Context.<anonymous> (test/e2e/tests/request-queuing/switchChain-watchAsset.spec.js:18:5)
```

**Comment by chloeYue** [comment]
Close this ticket as this test didn't flaky in past 2 weeks
