### ISSUE TITLE
Fix "ERC1155 NFTs testdapp interaction should revoke appr..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28484]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/110891/workflows/f9db749d-a3b6-44de-a427-7d0340268362/jobs/4149120/tests

test-e2e-chrome-webpack
Test scenario - ERC1155 NFTs testdapp interaction should revoke approval for a third party address to manage all ERC1155 token 
Test path - test/e2e/tests/tokens/nft/erc1155-interaction.spec.js

```
Error: No window found by background script with title: MetaMask Dialog
    at ServerMochaToBackground.receivedMessage (test/e2e/background-socket/server-mocha-to-background.ts:2:2485)
    at ws.onmessage (test/e2e/background-socket/server-mocha-to-background.ts:2:1916)
    at callListener (node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.emit (node:domain:488:12)
    at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.emit (node:domain:488:12)
    at Receiver.dataMessage (node_modules/ws/lib/receiver.js:596:14)
    at Receiver.getData (node_modules/ws/lib/receiver.js:496:10)
    at Receiver.startLoop (node_modules/ws/lib/receiver.js:167:16)
    at Receiver._write (node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Socket.socketOnData (node_modules/ws/lib/websocket.js:1355:35)
    at Socket.emit (node:events:519:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)
```

**Comment by chloeYue** [comment]
Close this ticket as this test is removed
