### ISSUE TITLE
Fix "Phishing Detection Phishing redirect protections sho..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28544]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/111316/workflows/b6a8fb89-5f4e-41d3-9fa9-025cabb57eaa/jobs/4165843/tests

Test Scenario - Phishing Detection Phishing redirect protections should display the MetaMask Phishing Detection page if a blocked site redirects via HTTP Status Code 200 to another page
Test Path - /test/e2e/tests/phishing-controller/phishing-detection.spec.js

```
UnexpectedAlertOpenError: unexpected alert open: {Alert text : trying to prevent phishing protection}
  (Session info: chrome=126.0.6478.182)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
```

**Comment by chloeYue** [comment]
Close this ticket as this test didn't flaky in past 2 weeks
