### ISSUE TITLE
Fix "Add existing token using search renders the balance for the chosen token" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28665]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/112120/workflows/c7a58fbc-47a8-42ee-98ac-687d37b809dd/jobs/4198264/tests

test-e2e-firefox
Test scenario -Add existing token using search renders the balance for the chosen token
Test path - /home/circleci/project/test/e2e/tests/tokens/add-hide-token.spec.js

```
ElementClickInterceptedError: Element <div class="mm-box selectable-list-item-wrapper"> is not clickable at point (866,482) because another element <div class="popover-bg"> obscures it
  (Ran on CircleCI Node 23 of 24, Job test-e2e-firefox)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async element.click (test/e2e/webdriver/driver.js:96:9)
    at async Driver.clickElement (test/e2e/webdriver/driver.js:601:9)
    at async /home/circleci/project/test/e2e/tests/tokens/add-hide-token.spec.js:136:9
    at async withFixtures (test/e2e/helpers.js:220:5)
    at async Context.<anonymous> (test/e2e/tests/tokens/add-hide-token.spec.js:108:5)
```

![Image](https://github.com/user-attachments/assets/61183fa5-3159-4c40-98c3-9bada47a021a)

**Comment by chloeYue** [comment]
Fixed by ticket https://github.com/MetaMask/metamask-extension/pull/28658
