### ISSUE TITLE
Fix "Add hide token hides the token when clicked" flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28664]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/112120/workflows/c7a58fbc-47a8-42ee-98ac-687d37b809dd/jobs/4198264/tests

test-e2e-firefox
Test scenario - Add hide token hides the token when clicked
Test path - /test/e2e/tests/tokens/add-hide-token.spec.js

```
Expected values to be strictly equal:

1 !== 2

  (Ran on CircleCI Node 23 of 24, Job test-e2e-firefox)
AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

1 !== 2

    at /home/circleci/project/test/e2e/tests/tokens/add-hide-token.spec.js:56:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async withFixtures (test/e2e/helpers.js:220:5)
    at async Context.<anonymous> (test/e2e/tests/tokens/add-hide-token.spec.js:16:5)

      + expected - actual

      -1
      +2
```

**Comment by chloeYue** [comment]
Close this issue as fix has been merged in https://github.com/MetaMask/metamask-extension/pull/28658
