### ISSUE TITLE
Fix "Send ETH from inside MetaMask from dapp using advanc..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28699]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/112323/workflows/1953cc00-9f71-4495-8805-53c26605ac54/jobs/4205988/tests

test-e2e-firefox
Test scenario - Send ETH from inside MetaMask from dapp using advanced gas controls should display the correct gas price on the legacy transaction
Test result - /test/e2e/tests/transaction/send-eth.spec.js
```
StaleElementReferenceError: The element with the reference 0706d80f-e526-4911-b25c-284fb4b14cf9 is stale; either its node document is not the active document, or it is no longer connected to the DOM
  (Ran on CircleCI Node 12 of 24, Job test-e2e-firefox)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
    at async element.fill (test/e2e/webdriver/driver.js:57:5)
    at async editGasFeeForm (test/e2e/helpers.js:564:3)
    at async /home/circleci/project/test/e2e/tests/transaction/send-eth.spec.js:286:13
    at async withFixtures (test/e2e/helpers.js:220:5)
    at async Context.<anonymous> (test/e2e/tests/transaction/send-eth.spec.js:246:9)
```

![image](https://github.com/user-attachments/assets/bab88a2c-d1fa-4c04-9423-b614e7b5733d)

![image](https://github.com/user-attachments/assets/ee34cf9a-cbe0-4e62-819a-d4dd1a72aea2)

![image](https://github.com/user-attachments/assets/48c1e073-be8d-4be6-9c7e-b85ef9c589ed)

**Comment by chloeYue** [comment]
Close this ticket as this test didn't flaky in past 2 weeks
