### ISSUE TITLE
Fix "should swap native token ETH to DAI on Ethereum Main..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28871]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/113672/workflows/12bbeec7-e8c9-4607-b3e8-b29af949f6fe/jobs/4260425/tests

test-e2e-swap-playwright - OPTIONAL
Test scenario - should swap native token ETH to DAI on Ethereum Mainnet'
Test path - swap/specs/swap.spec.ts

```
    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    TimeoutError: page.waitForSelector: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for locator('text=/1 ETH/') to be visible
    ============================================================

       at shared/pageObjects/wallet-page.ts:84

      82 |
      83 |   async waitforTokenBalance(balance: string) {
    > 84 |     await this.page.waitForSelector(`text=/${balance}/`, { timeout: 60000 });
         |                     ^
      85 |   }
      86 | }
      87 |

        at WalletPage.waitforTokenBalance (/root/project/test/e2e/playwright/shared/pageObjects/wallet-page.ts:84:21)
        at /root/project/test/e2e/playwright/swap/specs/swap.spec.ts:78:22

```

**Comment by chloeYue** [comment]
Close this ticket as this test didn't flaky in past 2 weeks
