### ISSUE TITLE
[Bug]: Balance amount dissapears in between send attempts with alert showing up for insufficient balance

### ISSUE THREAD

**Issue by benjisclowder** [MetaMask/metamask-extension#28925]
### Describe the bug

When I attempt to send a new transaction from one account to another on Sepolia network, with an account balance of 0.15 ETH, and enter an amount of 0.01 ETH, then continue on the confirmation screen, I get the network fee alert, with insufficient balance error and I am not allowed to continue on the confirmation screen. Then, as I exit the confirmation screen, I see the balance shows as 0. After adding other accounts, the balance finally shows up again, and attempting to repeat the process brings it back at 0 balance. 

Later debugging: Changing the infura project ID to the one we use in production solved the initial issue (of balance disappearing) but caused the same alert to show in a different scenario, deploying erc-20 contrat from the test dapp but without balance disappearing.. See video attached.

### Expected behavior

Transaction can be confirmed when I have balance in the account and no alert shows up.

### Screenshots/Recordings

Scenario 1. 
https://github.com/user-attachments/assets/a146aed3-aac4-4a75-97f9-5b6cd7f1f3c3

Scenario 2.
https://github.com/user-attachments/assets/a3dc57cb-3e5d-474d-85b2-ded213bbcf88

### Steps to reproduce

1. Load MM (with balance on Sepolia network)
2. Create a few accounts
3. Send a transaction to one of the new accounts and continue to the confirmation screen
4. Notice the network fee alert and review alert button instead of confirm button that does not allow to proceed (sometimes it takes around 15 seconds until the alert shows up, and in some tries it also dissapears and you can again press confirm)
5. Cancel transaction and return to main screen
6. Notice balance has become 0 when canceling a transaction where the network alert shows up

+ Later steps for contract interaction:

1. Load MM (with balance on Sepolia)
2. Load TestDapp and connect to the current MM account
3. Deploy erc-20 contract
4. Notice it takes a few seconds after when nothing happens, then transaction shows up in activity list as unapproved - without notification prompt
5. Click on the activity list item - confirmation screen shows up with network fee alert (same as in the above behavior) - no console errors.

### Error messages or log output

```shell
UI:
Insufficient funds
You do not have enough ETH in your account to pay for network fees.

console:

Error: No metadata found for 'overrideContentSecurityPolicyHeader'

+ 

Error: PollingBlockTracker - encountered an error while attempting to update latest block:
{
  "code": -32603,
  "message": "Request is being rate limited.",
  "stack": "Error: Request is being rate limited.\n    at JsonRpcError (chrome-extension://iacnodifdbmcfamifcjbbjeliengfhnc/common-2.js:15647:13)\n    at getJsonRpcError (chrome-extension://iacnodifdbmcfamifcjbbjeliengfhnc/common-2.js:16026:12)\n    at Object.internal (chrome-extension://iacnodifdbmcfamifcjbbjeliengfhnc/common-2.js:15892:24)\n    at createInternalError (chrome-extension://iacnodifdbmcfamifcjbbjeliengfhnc/common-2.js:14596:35)\n    at createRatelimitError (chrome-extension://iacnodifdbmcfamifcjbbjeliengfhnc/common-2.js:14579:12)\n    at performFetch (chrome-extension://iacnodifdbmcfamifcjbbjeliengfhnc/common-2.js:14551:23)\n    at async chrome-extension://iacnodifdbmcfamifcjbbjeliengfhnc/common-2.js:14491:17"
}
  at JsonRpcError (classes.cjs:33:1)
  at getJsonRpcError (errors.cjs:176:1)
  at Object.internal (errors.cjs:42:1)
  at createInternalError (create-infura-middleware.js:160:1)
  at createRatelimitError (create-infura-middleware.js:143:1)
  at performFetch (create-infura-middleware.js:115:1)
  at async create-infura-middleware.js:55:1
```

### Detection stage

In production (default)

### Version

12.7.2

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by benjisclowder** [comment]
Changing the infura project ID to the one we use in production solved the issue.

**Comment by benjisclowder** [comment]
Adding enough tokens to the account to exceed max fee set by the TestDapp allows the transaction to be sent successfully, with no alert shown.
