### ISSUE TITLE
Fix "Malicious Confirmation Signature - Bad Domain @no-mm..." flaky tests

### ISSUE THREAD

**Issue by hjetpoluru** [MetaMask/metamask-extension#28994]
https://app.circleci.com/pipelines/github/MetaMask/metamask-extension/114155/workflows/8ab265c7-2cfa-49b1-8a69-a6f3d5dec027/jobs/4279240/tests

Test scenario - Malicious Confirmation Signature - Bad Domain @no-mmi initiates and rejects from alert friction modal
Test path - /test/e2e/tests/confirmations/signatures/malicious-signatures.spec.ts

```
WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=126.0.6478.182)
  (Ran on CircleCI Node 15 of 20, Job test-e2e-chrome)
    at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async thenableWebDriverProxy.execute (node_modules/selenium-webdriver/lib/webdriver.js:745:17)
```

**Comment by pnarayanaswamy** [comment]
Looks like this was a chrome crash on CI. Cannot reproduce.
