### ISSUE TITLE
[Bug]:  Metamask injecting web3 despite not connected to site

### ISSUE THREAD

**Issue by polus-arcticus** [MetaMask/metamask-extension#28999]
### Describe the bug

Connect to site with metamask triggers "Cannot call write after stream was destroyed error" "Lost connection to metamask premature close" now even when disconnecting metamask from the extension it is still injecting web3 into the site

### Expected behavior

Disconnecting a site should stop metamask from injecting to window.etherum

### Screenshots/Recordings

![Image](https://github.com/user-attachments/assets/cbdaf443-32e9-4899-af4a-0735a5912ca9)
![Image](https://github.com/user-attachments/assets/493373d3-63a0-4279-a608-e140fccb65d1)
![Image](https://github.com/user-attachments/assets/a596c3fc-9baa-4dfc-8035-89f37fbfbcac)

### Steps to reproduce

Connect to site.
See stream error in console
disconnect from site via extension
type window.ethereum in console, see isMetamask = true

### Error messages or log output

```shell
@	index-D3wThEB3.js:107
(anonymous)	@	index-D3wThEB3.js:107
withRetry	@	index-D3wThEB3.js:107
withDedupe.enabled	@	index-D3wThEB3.js:107
withDedupe	@	index-D3wThEB3.js:107
(anonymous)	@	index-D3wThEB3.js:107
(anonymous)	@	index-D3wThEB3.js:107
withCache	@	index-D3wThEB3.js:107
getBlockNumber$1	@	index-D3wThEB3.js:107
(anonymous)	@	index-D3wThEB3.js:108
getBlockNumber	@	index-D3wThEB3.js:110
queryFn	@	index-D3wThEB3.js:126
tt	@	index-D3wThEB3.js:70
bt	@	index-D3wThEB3.js:70
start	@	index-D3wThEB3.js:70
fetch	@	index-D3wThEB3.js:70
Qs	@	index-D3wThEB3.js:70
fetch	@	index-D3wThEB3.js:70
refetch	@	index-D3wThEB3.js:70
onFocus	@	index-D3wThEB3.js:70
(anonymous)	@	index-D3wThEB3.js:70
(anonymous)	@	index-D3wThEB3.js:70
nt	@	index-D3wThEB3.js:70
onFocus	@	index-D3wThEB3.js:70
(anonymous)	@	index-D3wThEB3.js:70
await in (anonymous)		
(anonymous)	@	index-D3wThEB3.js:70
onFocus	@	index-D3wThEB3.js:70
(anonymous)	@	index-D3wThEB3.js:70
b	@	index-D3wThEB3.js:70


inpage.js:1 MetaMask: Lost connection to "MetaMask RpcProvider".
Error: Premature close
    at new s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:12:10750)
    at c.p (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:12:44973)
    at a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:10:30446)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:12:42848)
    at g.run (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:12:10145)
    at p (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:12:9632)


lockdown-install.js:1 Error: Premature close
(anonymous)	@	lockdown-install.js:1
error		
(anonymous)	@	lockdown-install.js:1
(anonymous)	@	lockdown-install.js:1
globalThis.lockdown	@	lockdown-install.js:1
(anonymous)	@	lockdown-run.js:4
```

### Detection stage

In production (default)

### Version

12.8.0

### Build type

None

### Browser

Chrome

### Operating system

Linux

**Comment by benjisclowder** [comment]
Same as this Sentry issue: #22490

**Comment by gauthierpetetin** [comment]
Hi @polus-arcticus , thanks for reporting this issue. Could you please tell us more about steps to reproduce?
What site do you connect to in order to see these stream errors in console?

**Comment by polus-arcticus** [comment]
Hey @gauthierpetetin thanks for having a look at this issue!

Claude and I made a reproduable example here

https://github.com/polus-arcticus/metamask-28999

to note is that this pattern works fine for rainbow wallet, it seems to be metamasks stream duplex that panics when repeat calls are made.

While we just get warnings (200 - 400) here to the failure, when you start adding more logic eventually it just overloads the rpc and crashes

if you want to see how the stream crashes it the error reproduces without fail
on https://github.com/hashchan/hashchan when connected to a supported network

**Comment by Gudahtt** [comment]
Note that 'disconnecting' (i.e. revoking permissions) from a site **is not** supposed to prevent `window.ethereum` from being injected. `window.ethereum` is used to request permissions in the first place. It must be there for a site to connect (i.e. request permissions) in the first place.

**Comment by polus-arcticus** [comment]
> Note that 'disconnecting' (i.e. revoking permissions) from a site **is not** supposed to prevent `window.ethereum` from being injected. `window.ethereum` is used to request permissions in the first place. It must be there for a site to connect (i.e. request permissions) in the first place.

Oh yes i should be clearer, as seen from one of the screenshots up there, metamask is not connected but the ui still managed to fetch my account
