### ISSUE TITLE
Trying to connect my my explorer.nodestake.org account to my MetaMask

### ISSUE THREAD

**Issue by zdavatz** [MetaMask/metamask-extension#29096]
### Describe the bug

1. I am trying to connect my MetaMask account in explorer.nodestake.org
2. ![Image](https://github.com/user-attachments/assets/d215dabf-67ea-4d17-aca2-dc6989747005)
3. ![Image](https://github.com/user-attachments/assets/e2910fa6-062e-4c24-84d5-3ece525c96ca)
4. getting above error.

### Expected behavior

5. Connect to the MetaMask wallet.

### Steps to reproduce

1. Goto you Nodestake account.
2. https://explorer.nodestake.org/
3. Try to connect the MetaMask Wallet.
4. Does not work. 

### Error messages or log output

```shell
{ "code": -32603, "message": "Invalid chainId", "stack": "Error: Invalid chainId\n at validateChainId (eval at <anonymous> (eval at makeEvaluate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/snaps/index.html:6368:27)), <anonymous>:382924:17)\n at async onRpcRequest (eval at <anonymous> (eval at makeEvaluate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/snaps/index.html:6368:27)), <anonymous>:386805:15)\n at async l.executeInSnapContext (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/snaps/bundle.js:9:51211)\n at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/snaps/bundle.js:9:46655\n at async Object.snapRpc (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/snaps/bundle.js:9:51932)\n at async l.onCommandRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/snaps/bundle.js:9:47986)" }.
```

### Detection stage

In production (default)

### Version

12.8.1

### Build type

None

### Browser

Chrome

### Operating system

Linux

### Severity

Critical

**Comment by DanielTech21** [comment]
Hi @zdavatz 

Thank you for reporting this error.
Our team will look into this and advise you on the next steps.

**Comment by darkwing** [comment]
@zdavatz I was able to connect without issue in the latest version of MetaMask (12.12).  Could you attempt again please?  If not, any further information would be helpful.

**Comment by zdavatz** [comment]
Ok, let me test again 🙏🏼

**Comment by zdavatz** [comment]
1. Sorry, guys, this is still not working:
2. ![Image](https://github.com/user-attachments/assets/9564261b-647b-4034-9336-29a1bd9b1881)
