### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by nithya2609** [MetaMask/metamask-extension#2969]
Hi,
i get the below error for gulp build

 Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (C:\Users\nspriya\clfa\node_modules\vinyl-fs\lib\dest\prepare.js:16:17)
    at DestroyableTransform.Transform._read (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_transform.js:170:83)
    at doWrite (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (C:\Users\nspriya\clfa\node_modules\duplexify\index.js:212:22)
    at doWrite (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_writable.js:406:64)
    at writeOrBuffer (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_writable.js:395:5)
    at Pumpify.Writable.write (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_writable.js:322:11)
    at Transform.ondata (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at Transform.emit (events.js:188:7)
    at addChunk (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_readable.js:284:12)
    at readableAddChunk (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_readable.js:271:11)
    at Transform.Readable.push (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_readable.js:238:10)
    at Transform.push (C:\Users\nspriya\clfa\node_modules\readable-stream\lib\_stream_transform.js:146:32)

i dont have vinyl dependency in my package.json

**Comment by Zanibas** [comment]
Hi, what commands are you running in order to setup the repository?

**Comment by nithya2609** [comment]
hi,
thanks for the response. the error resolved by using gulp local 4.0.0 alpha 2 instead of 3.
did this by using 
"gulp": "git://github.com/gulpjs/gulp.git#6d71a658c61edb3090221579d8f97dbe086ba2ed".

**Comment by kumavis** [comment]
This is a good point, we do have gulp pointed at a mutable pre-release branch `gulp#4.0`
