### ISSUE TITLE
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'metamask-config' exceeded the quota.

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3071]
https://sentry.io/metamask/metamask/issues/439078556/

```
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'metamask-config' exceeded the quota.
  at LocalStorageStore._putState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:76821:34)
  at LocalStorageStore.putState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:76537:12)
  at ObsStoreStream._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:76670:21)
  at doWrite (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:80795:64)
  at writeOrBuffer (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:80784:5)
...
(9 additional frame(s) were not displayed)
```

**Comment by tmashuang** [comment]
Function in `chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:76537:12` is: 
```
function pbkdf2 (password, salt, iterations, keylen, digest) {
  if (!Buffer.isBuffer(password)) password = Buffer.from(password, defaultEncoding)
  if (!Buffer.isBuffer(salt)) salt = Buffer.from(salt, defaultEncoding)

  checkParameters(iterations, keylen)

  digest = digest || 'sha1'

  var hmac = new Hmac(digest, password, salt.length)

  var DK = Buffer.allocUnsafe(keylen)
  var block1 = Buffer.allocUnsafe(salt.length + 4)
  salt.copy(block1, 0, 0, salt.length)

  var destPos = 0
  var hLen = sizes[digest]
  var l = Math.ceil(keylen / hLen)

  for (var i = 1; i <= l; i++) {
    block1.writeUInt32BE(i, salt.length)

    var T = hmac.run(block1, hmac.ipad1)
    var U = T

    for (var j = 1; j < iterations; j++) {
      U = hmac.run(U, hmac.ipad2)
      for (var k = 0; k < hLen; k++) T[k] ^= U[k]
    }

    T.copy(DK, destPos)
    destPos += hLen
  }

  return DK
}
```

**Comment by kumavis** [comment]
We released a version that uses `extension.storage.local` to address this issue - however we have not yet removed writing to localStorage

**Comment by kumavis** [comment]
localStorage writing was removed here https://github.com/MetaMask/metamask-extension/pull/3732
