### ISSUE TITLE
UI - Shapeshift - JSON parse issue

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3072]
https://sentry.io/metamask/metamask/issues/439095888/

```
Invariant Violation: Objects are not valid as a React child (found: SyntaxError: Unexpected token < in JSON at position 0). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `ShapeshiftForm`.
  at invariant (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:40958:15)
  at traverseAllChildrenImpl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:69831:56)
  at traverseAllChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:69859:10)
  at flattenChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:68529:5)
  at ReactDOMComponent._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:64631:28)
...
(45 additional frame(s) were not displayed)
```

**Comment by bdresser** [comment]
won't fix, since we're moving to the new UI
