### ISSUE TITLE
UI (old) - _this.props.onClick is not a function

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3084]
https://sentry.io/metamask/metamask/issues/439098090/

```
TypeError: _this.props.onClick is not a function
  at onClick (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:99119:26)
  at HTMLUnknownElement.boundFunc (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:63269:9)
  at HTMLUnknownElement.d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:659:26)
  at Object.ReactErrorUtils.invokeGuardedCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:63275:16)
  at executeDispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:57292:21)
...
(14 additional frame(s) were not displayed)
```

**Comment by danjm** [comment]
This should have been fixed by https://github.com/MetaMask/metamask-extension/pull/3350
