### ISSUE TITLE
UI (old + NewUI) - ShapeShift - TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3087]
https://sentry.io/metamask/metamask/issues/439113153/

```
TypeError: Cannot read property 'split' of undefined
  at ShapeshiftForm.renderMain (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:100080:30)
  at ShapeshiftForm.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:100074:63)
  at measureLifeCyclePerf (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:58822:12)
  at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:59541:25)
  at ReactCompositeComponentWrapper._renderValidatedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:59568:32)
...
(44 additional frame(s) were not displayed)
```

**Comment by Zanibas** [comment]
This is actually an issue I think with the newUI. The source token textbox is not responsive to selecting any other currency besides BTC.
