### ISSUE TITLE
UI (old) - Import JSON key  -  TypeError: Cannot read property 'fileContents' of null

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3089]
https://sentry.io/metamask/metamask/issues/439123116/

```
TypeError: Cannot read property 'fileContents' of null
  at JsonImportSubview.createNewKeychain (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:94796:28)
  at HTMLUnknownElement.boundFunc (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:63269:9)
  at HTMLUnknownElement.d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:659:26)
  at Object.ReactErrorUtils.invokeGuardedCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:63275:16)
  at executeDispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:57292:21)
...
(14 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
must be coming from here https://github.com/MetaMask/metamask-extension/blob/1a4f982739a09a4fd757b5f45fcaeef1a93dd4a3/ui/app/accounts/import/json.js#L84

**Comment by kumavis** [comment]
Chose P1 because it affects key mgmt functionality
