### ISSUE TITLE
Unexpected error when submitting transactions: JSON RPC

### ISSUE THREAD

**Issue by drewstone** [MetaMask/metamask-extension#3125]
I'm using MetaMask to interface with a contract on my web application. It does fine in calling state variables of the contracts and returning these values, but when I try to submit transactions I get odd JSON RPC errors:

My contracts are wrapped using `truffle-contract` as well.

```
Error: Error: Error: [ethjs-query] while formatting outputs from RPC 'undefined' for method  
 'sendRawTransaction' Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 66 utf8  
 byte hex (chars: a-fA-F) string, is 0 bytes at TransactionStateManger.<anonymous> (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2211:39) at  
 TransactionStateManger.g (chrome-
extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:61201:16) at  
 TransactionStateManger.EventEmitter.emit (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:61117:17) at  
 TransactionStateManger._setTxStatus (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5469:14) at  
 TransactionStateManger.setTxStatusFailed (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5443:12) at TransactionController._callee6$ (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2474:37) at tryCatch  
 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:81323:40) at  
 Generator.invoke [as _invoke] (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:81557:22) at  
 Generator.prototype.(anonymous function) [as throw] (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:81375:21) at step (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:18684:30) at chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:18697:13 at <anonymous>  
 at TransactionStateManger.<anonymous> (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2211:39) at  
 TransactionStateManger.g (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:61201:16) at  
 TransactionStateManger.EventEmitter.emit (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:61117:17) at  
 TransactionStateManger._setTxStatus (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5469:14) at  
 TransactionStateManger.setTxStatusFailed (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5443:12) at  
 TransactionController._callee6$ (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2474:37) at tryCatch  
 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:81323:40) at  
 Generator.invoke [as _invoke] (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:81557:22) at  
 Generator.prototype.(anonymous function) [as throw] (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:81375:21) at step (chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:18684:30) at chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:18697:13 at <anonymous>  
 at Object.InvalidResponse (http://localhost:3000/static/js/bundle.js:161092:16) at  
 http://localhost:3000/static/js/bundle.js:164527:36 at chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9935:9 at chrome- 
 extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:735:16 at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5577:29) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1220:16 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:735:16 at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1255:25) at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1245:17) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1220:16 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9870:7 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:10030:16 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3358:16 at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1260:17) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1264:9 at eachLimit$1 (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:3444:24) at Object.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1294:16) at RpcEngine._runReturnHandlersUp (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:10029:13) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9947:22 at nextTask (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5572:14) at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5579:9) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1220:16 at checkForCompletion (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:9966:16) at nextTask (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5572:14) at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:5579:9) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1220:16 at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:10020:9) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1388:9 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:735:16 at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1255:25) at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1245:17) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1220:16 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:1385:13 at end (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:10005:11) From previous event: at step (http://localhost:3000/static/js/bundle.js:170990:404) at http://localhost:3000/static/js/bundle.js:170990:519 From previous event: at Object.<anonymous> (http://localhost:3000/static/js/bundle.js:170990:99) at Object.addTask (http://localhost:3000/static/js/bundle.js:171087:22) at addTask (http://localhost:3000/static/js/bundle.js:167430:26) at Object.addTask (http://localhost:3000/static/js/bundle.js:123901:35) at HomePage.handleFormSubmit (http://localhost:3000/static/js/bundle.js:168762:18) at Object../node_modules/react-dom/lib/ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:89426:16) at executeDispatch (http://localhost:3000/static/js/bundle.js:83036:21) at Object.executeDispatchesInOrder (http://localhost:3000/static/js/bundle.js:83059:5) at executeDispatchesAndRelease (http://localhost:3000/static/js/bundle.js:82445:22) at executeDispatchesAndReleaseTopLevel (http://localhost:3000/static/js/bundle.js:82456:10) at Array.forEach (<anonymous>) at forEachAccumulated (http://localhost:3000/static/js/bundle.js:95341:9) at Object.processEventQueue (http://localhost:3000/static/js/bundle.js:82656:7) at runEventQueueInBatch (http://localhost:3000/static/js/bundle.js:89461:18) at Object.handleTopLevel [as _handleTopLevel] (http://localhost:3000/static/js/bundle.js:89471:5) at handleTopLevelImpl (http://localhost:3000/static/js/bundle.js:89559:24) at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:3000/static/js/bundle.js:94537:20) at Object.batchedUpdates (http://localhost:3000/static/js/bundle.js:89171:26) at Object.batchedUpdates (http://localhost:3000/static/js/bundle.js:92474:27) at dispatchEvent (http://localhost:3000/static/js/bundle.js:89634:20)"
```

I am running MetaMask on a custom local network using Ganache as the underlying local network. I deploy the contracts using truffle. The error happens in my code here:
```javascript
let result = await protocol.createTask(...args, { from: web3.eth.coinbase });
```

**Comment by drewstone** [comment]
Might this be because MetaMask returns callbacks?

**Comment by drewstone** [comment]
This seems to be a problem with Ganache.

**Comment by lukeaus** [comment]
I also had this issue. This issue does not appear in v1.0.2

**Comment by jsphLim** [comment]
I meet this probleam too,Do anybody know how to solve it?

**Comment by loktarjugg** [comment]
I have the same problem here
Ganache: 1.1.0-beta.0 (ON MACOS HIGH SIERRA)

**Comment by PablosOne** [comment]
Same issue here on the latest Ganache windows app.
Is there any solution yet? It was working fine some days ago.

**Comment by shenzhun** [comment]
I meet the same problem too. Not sure how to fix it.

**Comment by vmandal** [comment]
Same issue in Ganache Linux app

**Comment by sevriugin** [comment]
The same problem with MacOS Ganache 1.1.0-beta.0

**Comment by hiteshjoshi1** [comment]
How do we know this is a Ganache issue? Have you tried with others and they work?

**Comment by krasnopv** [comment]
I fix it with Reset my Account under 127.0.0.1:7545 network:
Settings -> [Reset Account]

**Comment by mesqueeb** [comment]
@krasnopv this fixed it for me!

**Comment by vmandal** [comment]
I went on to use Ganache-cli it started to work good.
Then I came back to use Ganache GUI than this also worked good. 
So it must be reset to fix the issue. 
Btw, I has a lower version of nodejs than recommended. I upgraded nodejs as well before the trials.

**Comment by ethan-deng** [comment]
Yes, each account need to be selected and select "Reset Account".

**Comment by bjornharvold** [comment]
I get this error as well. Ganache v1.0.beta.0 Reset all my accounts in MetaMask. Still cannot make a transaction.

```
Error: Error: Error: [ethjs-query] while formatting outputs from RPC 'undefined' for method 'sendRawTransaction' Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 66 utf8 byte hex (chars: a-fA-F) string, is 0 bytes
    at TransactionStateManger.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2216:39)
    at TransactionStateManger.g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:69757:16)
    at TransactionStateManger.EventEmitter.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:69673:17)
    at TransactionStateManger._setTxStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5488:14)
    at TransactionStateManger.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:5448:12)
    at TransactionController._callee6$ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:2479:37)
```

**Comment by kyriediculous** [comment]
Resetting the account works for me.

**Comment by rrubo** [comment]
Set the Custom RPC "http://127.0.0.1:7545", and it'll work.

**Comment by bdresser** [comment]
Hey folks - ganache has fixed quite a few errors in the past year and we've made some changes to our custom RPC feature. I'm closing this issue due to inactivity, please let me know if you're still having trouble!

**Comment by tomsoft1** [comment]
Have same kind of problems, switching to ganache-cli solved the issue
