### ISSUE TITLE
Network controller crashing on start up and provider change

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3262]
On `uat`, on starting up or switching networks, my background console shows this error from the `RpcBlockTracker.AsyncEventEmitter` class, in its `emit` function:

```
AsyncEventEmitter.js:46 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11497:11
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11917:9
    at eachLimit (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11785:36)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11845:16
    at RpcBlockTracker.AsyncEventEmitter.emit (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11493:3)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:91004:7
    at new Promise (<anonymous>)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:90987:10
    at ret (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:91031:34)
    at RpcBlockTracker._callee3$ (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:56978:39)
    at tryCatch (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:20983:40)
    at Generator.invoke [as _invoke] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21217:22)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21035:21)
    at step (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:18613:30)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:18631:14
    at new Promise (<anonymous>)
    at new F (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:19122:28)
    at RpcBlockTracker.<anonymous> (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:18610:12)
    at RpcBlockTracker._setTrackingBlock (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:56989:22)
    at RpcBlockTracker._callee2$ (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:56908:55)
    at tryCatch (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:20983:40)
    at Generator.invoke [as _invoke] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21217:22)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21035:21)
```

**Comment by danfinlay** [comment]
This error is actually happening in `master`, too. I think it may be causing the block gas limit to stop updating.

**Comment by danfinlay** [comment]
I see this error happening specifically when changing the provider in the provider menu. It is being thrown from the `AsyncEventEmitter` class, in its `emit` function.

Ah, in fact, it's `at RpcBlockTracker.AsyncEventEmitter.emit`.

Fuller trace:

```
AsyncEventEmitter.js:46 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11497:11
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at iterateeCallback (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11898:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12044:16
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11505:14
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:12120:16
    at replenish (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11913:17)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11917:9
    at eachLimit (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11785:36)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11845:16
    at RpcBlockTracker.AsyncEventEmitter.emit (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:11493:3)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:91004:7
    at new Promise (<anonymous>)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:90987:10
    at ret (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:91031:34)
    at RpcBlockTracker._callee3$ (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:56978:39)
    at tryCatch (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:20983:40)
    at Generator.invoke [as _invoke] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21217:22)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21035:21)
    at step (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:18613:30)
    at chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:18631:14
    at new Promise (<anonymous>)
    at new F (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:19122:28)
    at RpcBlockTracker.<anonymous> (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:18610:12)
    at RpcBlockTracker._setTrackingBlock (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:56989:22)
    at RpcBlockTracker._callee2$ (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:56908:55)
    at tryCatch (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:20983:40)
    at Generator.invoke [as _invoke] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21217:22)
    at Generator.prototype.(anonymous function) [as next] (chrome-extension://ebjbdknjcgcbchkagneicjfpneaghdhb/scripts/background.js:21035:21)
```

**Comment by danjm** [comment]
@danfinlay can you confirm whether this was an issue with your local build? And if so, it can be closed, correct?
