### ISSUE TITLE
Error with metamask when adding watch in an Event

### ISSUE THREAD

**Issue by jbpin** [MetaMask/metamask-extension#3325]
Sorry for the format. 

I try to add a watch on an event sent by my contract and I got this error 

```
Error: Error: [ethjs-rpc] rpc error with payload {"id":8378175129114,"jsonrpc":"2.0","params":[{"fromBlock":"0x1c146b","toBlock":"0x1c146b","address":"0x5bdba6b53cc94da5d3efb0240bef4450cb15ad6e","topics":["0x86348afa02de935ee90cb70342d9c7b498fecb1752ee73a4915040ee5985343c",null]}],"method":"eth_getLogs"} Error: InfuraProvider - cannot complete request. All retries exhausted.
Original Error:
SyntaxError: Unexpected token i in JSON at position 0


    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:69126:28
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:91174:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17383:16
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17212:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17399:16
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:93644:9)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:91154:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17517:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17232:17)
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17217:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17399:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:91156:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17517:16
    at replenish (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17232:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17236:9
    at eachLimit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16926:36)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:17140:16
    at end (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:91151:5)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:93935:29
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:72345:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:11758:16
    at next (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:16600:29)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12243:16
    at completeRequest (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:72427:20)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12411:9
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:11758:16
    at iterateeCallback (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12261:17)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12243:16
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:12408:13
    at end (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:72412:27)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:39417:9
    at d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:8365:26)

```

Here is the call
```
contract.MyEvent().watch((err, event) => {
    console.log(err, event);
});
```

**Comment by kumavis** [comment]
I think this was related to an Infura availability event
