### ISSUE TITLE
TypeError: Cannot read property 'nonce' of undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3683]
https://sentry.io/metamask/metamask/issues/500500533/

```
TypeError: Cannot read property 'nonce' of undefined
  at g.showRetryButton (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1916191)
  at g.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1918382)
  at c._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1372318)
  at c._renderValidatedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1372425)
  at c.performInitialMount (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1368308)
...
(45 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
Duplicate of https://github.com/MetaMask/metamask-extension/issues/3686
