### ISSUE TITLE
UI - history list - TxParams is undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3686]
https://sentry.io/metamask/metamask/issues/500832862/

```
TypeError: Cannot read property 'to' of undefined
  at U.renderTransactionListItem (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2248791)
  at Array.map (<anonymous>)
  at U.renderTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2248452)
  at U.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2248309)
  at c._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1372318)
...
(44 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
txlist is actually "history item list", most of which are txs

likely txParams is missing, so maybe shapeshift or signature

**Comment by kumavis** [comment]
https://sentry.io/metamask/metamask/issues/500500533/

**Comment by kumavis** [comment]
https://sentry.io/metamask/metamask/issues/501156771/
