### ISSUE TITLE
TypeError: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3687]
https://sentry.io/metamask/metamask/issues/500747237/

```
TypeError: Cannot read property 'key' of undefined
  at p.createKeyringOnEnter (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2045217)
  at onKeyPress (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2044827)
  at Object.i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1409079)
  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1350000)
  at Object.executeDispatchesInOrder (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1350729)
...
(12 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
import/json.js -> createKeyringOnEnter

**Comment by kumavis** [comment]
related? #3675
