### ISSUE TITLE
Handle Shapeshift POST fails (500)

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3688]
https://sentry.io/metamask/metamask/issues/474892576/

```
Invariant Violation: Objects are not valid as a React child (found: SyntaxError: Unexpected token < in JSON at position 0).
  at t.exports (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1462282)
  at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1464998)
  at t.exports (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1465093)
  at t.exports (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1454674)
  at K._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1420551)
...
(45 additional frame(s) were not displayed)
```

**Comment by danfinlay** [comment]
Probably just needs a try/catch statement to handle this.
