### ISSUE TITLE
TypeError: Cannot read property 'valueTracker' of null

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3691]
https://sentry.io/metamask/metamask/issues/500952152/

```
TypeError: Cannot read property 'valueTracker' of null
  at o (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1458614)
  at Object.stopTracking (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1459524)
  at K.unmountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1385120)
  at Object.unmountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1425738)
  at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1363986)
...
(39 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
related to `.hex-input` so must be on old ui
some React error, seems infrequent
