### ISSUE TITLE
AddTokenButton - 'address' of undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3692]
https://sentry.io/metamask/metamask/issues/476296400/

```
TypeError: Cannot read property 'address' of undefined
  at getTokenAddressFromTokenObject (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2324301)
  at addTokens (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2078067)
  at onClick (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2083453)
  at Object.i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1409079)
  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1350000)
...
(13 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
some vague ideas:
- failing if tokens dont support symbol field?
- selected account is not in identities map?
- we have multiple "selected account" states (view vs background)?
- `currentAccount` vs `app.metamask.currentAccount`?
