### ISSUE TITLE
TypeError: u.map is not a function

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3693]
https://sentry.io/metamask/metamask/issues/500503422/

```
TypeError: u.map is not a function
  at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:58763)
  at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:59721)
  at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:60235)
  at c._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1372318)
  at c._renderValidatedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1372425)
...
(16 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
First time flow

**Comment by danjm** [comment]
This problem was eliminated when we switched to the new buy ether modal in https://github.com/MetaMask/metamask-extension/pull/3680 (the code that caused this problem is no longer used)
