### ISSUE TITLE
ui bug - Undefined keyring (?)

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3696]
https://sentry.io/metamask/metamask/issues/500801352/

```
TypeError: Cannot read property 'type' of undefined
  at b.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:2254831)
  at c._renderValidatedComponentWithoutOwnerOrContext (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1372318)
  at c._renderValidatedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1372425)
  at c.performInitialMount (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1368308)
  at c.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/popup.js:1:1367354)
...
(45 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
possibly related #3675

**Comment by kumavis** [comment]
a few `x.type`s found in both new ui and old ui
- provider.type
- keyring.type
- action.type
