### ISSUE TITLE
Error: [ethjs-rpc] gas required exceeds allowance or always failing transaction

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3748]
https://sentry.io/metamask/metamask/issues/504975579/

```
Error: [ethjs-rpc] rpc error with payload {"id":8089766453697,"jsonrpc":"2.0","params":[{"from":"0xad17c0764fce5b14a421de4af327fcece69d9c98","to":"0x6d626e483d308e6e9eb4e81139c9749697cda229","value":"0x8ac7230489e80000","gas":"0x44218a","gasPrice":"0x3b9aca00"}],"method":"eth_estimateGas"} Error: gas required exceeds allowance or always failing transaction
  at None (metamask/scripts/background.js:1:840098)
  at None (metamask/scripts/background.js:1:1332450)
  at None (metamask/scripts/background.js:1:354722)
  at h (metamask/scripts/background.js:1:352536)
  at None (metamask/scripts/background.js:1:354972)
...
(28 additional frame(s) were not displayed)
```

**Comment by bdresser** [comment]
closing - haven't seen in three months

**Comment by joelamouche** [comment]
<img width="692" alt="capture d ecran 2018-07-25 a 16 12 16" src="https://user-images.githubusercontent.com/16758383/43224853-8a986848-9025-11e8-97b7-9a73f2bfb3d2.png">

I got this error after calling estimaGas like this:
`
    let estimate = await conceptInstance.methods.makeAssessment(cost, size, startTime, endTime).estimateGas({from: userAddress, gas: 3000000})`
