### ISSUE TITLE
Error: [ethjs-contract] while formatting incoming raw call data

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3769]
https://sentry.io/metamask/metamask/issues/505625896/

```
Error: [ethjs-contract] while formatting incoming raw call data "0x454f530000000000000000000000000000000000000000000000000000000000" Error: Number can only safely store up to 53 bits
  at protoCallback (node_modules/ethjs-contract/lib/index.js:76:1)
  at callback (node_modules/eth-token-tracker/node_modules/ethjs-query/lib/index.js:65:1)
  at callback (node_modules/ethjs-query/node_modules/ethjs-rpc/lib/index.js:63:1)
  at apply (node_modules/web3-stream-provider/index.js:68:1)
  at wrapped (node_modules/raven-js/src/raven.js:375:1)
```

**Comment by kumavis** [comment]
something with tokens i assume `ethjs-contract`

**Comment by bdresser** [comment]
This error doesn't exist in Sentry anmore
