### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3827]
https://sentry.io/metamask/metamask/issues/506756211/

```
RangeError: Maximum call stack size exceeded
  at Array.push (<anonymous>)
  at Promise (node_modules/await-semaphore/index.js:29:1)
  at new Promise (<anonymous>)
  at acquire (node_modules/await-semaphore/index.js:18:1)
  at call (node_modules/eth-json-rpc-filters/index.js:39:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by bdresser** [comment]
hasn't been seen since 4.4.0 a month or so ago 😅
