### ISSUE TITLE
Version from 02nd April  error : Error: Error: chainId: 4 in txParams is not a string

### ISSUE THREAD

**Issue by sylvi2000** [MetaMask/metamask-extension#3841]
I am trying to make operation on my contract, as I did yesterday without problems. After upgrade I get the exception, any ideas  what to do?:

Error: Error: chainId: 4 in txParams is not a string at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:246:3389 at Array.forEach () at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:246:3330) at e.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:246:2823) at t. (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:141:7541) at L (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:17730:4382) at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:17730:4170) at Generator.t.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:17730:4561) at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:531:350) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:531:454 at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:445:27853) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:445:60227 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:336:855 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:2363 at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:20595) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5238 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:2363 at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5514) at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5436) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:18:5238

**Comment by fjchen7** [comment]
Same problem here.

**Comment by MchlG** [comment]
Same issue here. Confirmed that ETH transfer directly from Metamask works but when using Metamask with MEW I get this error

**Comment by frankwei98** [comment]
same issue on ropsten and kovan

**Comment by phejimlin** [comment]
Same issue for Ropsten Test Net.

**Comment by jaggedsoft** [comment]
Same problem here. Cannot send tokens or interact with a contract

**Comment by Cryptonicles** [comment]
when will this be back online?
