### ISSUE TITLE
Conversion util: new BigNumber() not a base 16 number: undefined

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3913]
https://sentry.io/metamask/metamask/issues/512798488/

```
BigNumber Error: new BigNumber() not a base 16 number: undefined
  at W (node_modules/bignumber.js/bignumber.js:1:1)
  at None (node_modules/bignumber.js/bignumber.js:1:1)
  at new $ (node_modules/bignumber.js/bignumber.js:1:1)
  at multiplyCurrencies (ui/app/conversion-util.js:169:22)
  at getGasTotal (ui/app/components/send/send-utils.js:67:10)
...
(45 additional frame(s) were not displayed)
```

**Comment by danjm** [comment]
This happens when we try to calculate gas total when either `gas` (i.e. 'gas limit') or `gasPrice` are undefined on `txParams`

**Comment by danjm** [comment]
Solution: show loading screen until gas and gasPrice are available
