### ISSUE TITLE
Empty Vault Anomoly

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3919]
https://sentry.io/metamask/metamask/issues/517831185/

```
Error: MetaMask Migration Error #22: Migrator - migration returned empty data
  at r.<anonymous> (app/scripts/lib/migrator/index.js:27:39)
  at L (node_modules/regenerator-runtime/runtime.js:1:1)
  at Generator._invoke (node_modules/regenerator-runtime/runtime.js:1:1)
  at Generator.t.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:1:1)
  at n (node_modules/babel-runtime/helpers/asyncToGenerator.js:1:1)
...
(1 additional frame(s) were not displayed)
```

**Comment by bdresser** [comment]
hasn't been seen since 4.5.5 about a month ago
