### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by kumavis** [MetaMask/metamask-extension#3983]
https://sentry.io/metamask/metamask/issues/513034903/

This all seems related to eth-block-tracker's asyncEventEmitter that we decided needs to be removed.

```
RangeError: Maximum call stack size exceeded
  at Promise (node_modules/await-semaphore/index.js:1:1)
  at new Promise (<anonymous>)
  at Mutex.acquire (node_modules/await-semaphore/index.js:1:1)
  at r.l (node_modules/eth-json-rpc-filters/index.js:1:1)
  at None (node_modules/eth-block-tracker/node_modules/async-eventemitter/lib/AsyncEventEmitter.js:1:1)
...
(45 additional frame(s) were not displayed)
```

**Comment by kumavis** [comment]
closing as old and not enough info
