### ISSUE TITLE
UI - Error: [ethjs-rpc] rpc error with payload {"id":6744058272094,"jsonrpc":"2.0","params":[{"to":"0xe1892f9...

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#4973]
https://sentry.io/metamask/metamask/issues/580570061/

```
Error: [ethjs-rpc] rpc error with payload {"id":6744058272094,"jsonrpc":"2.0","params":[{"to":"0xe1892f9259a36de1fa2f7c4431ff0b5880cfa8b1","data":"0x70a082310000000000000000000000005e9fe300582a22ff70d5a326fdb31e5d2b3957f9"},"latest"],"method":"eth_call"} null
  at None (metamask/ui.js:1:1092442)
  at None (metamask/ui.js:1:2399534)
  at o (metamask/ui.js:1:1713231)
```

**Comment by jennypollack** [comment]
Sentry link fails to load data. 
No current Sentry issues match.
