### ISSUE TITLE
Blank screen after logging in

### ISSUE THREAD

**Issue by funyug** [MetaMask/metamask-extension#5041]
I am getting a blank screen after clicking on login. This happened while i was doing the solution on https://ethernaut.zeppelin.solutions/level/0x68756ad5e1039e4f3b895cfaa16a3a79a5a73c59 and accidentally passed a hex instead of a string in the transaction data field. The metamask popup opened but was only white screen. Since then i have not been able to use metamask past the login screen. Everytime i login i see a white screen. The console of the metamask has the following errors:

Uncaught (in promise) TypeError: e.slice is not a function
    at Object.decodeMethod (ui.js:1)
    at E.getAddressText (ui.js:1)
    at E.render (ui.js:1)
    at ui.js:1
    at Q (ui.js:1)
    at d._renderValidatedComponentWithoutOwnerOrContext (ui.js:1)
    at d._renderValidatedComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at le.mountChildren (ui.js:1)
    at le._createInitialChildren (ui.js:1)
    at le.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at le.mountChildren (ui.js:1)
    at le._createInitialChildren (ui.js:1)
    at le.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at le.mountChildren (ui.js:1)
    at le._createInitialChildren (ui.js:1)
    at le.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
    at d.mountComponent (ui.js:1)
    at Object.mountComponent (ui.js:1)
    at d.performInitialMount (ui.js:1)
4ui.js:1 Uncaught TypeError: Cannot read property '__reactInternalInstance$r39aijomlb9' of null
    at Object.h [as getClosestInstanceFromNode] (ui.js:1)
    at d (ui.js:1)
    at f (ui.js:1)
    at l.perform (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at dispatchEvent (ui.js:1)
    at HTMLImageElement.o (ui.js:1)
ui.js:1 Uncaught TypeError: Cannot read property '_currentElement' of null
    at d._updateRenderedComponent (ui.js:1)
    at d._performComponentUpdate (ui.js:1)
    at d.updateComponent (ui.js:1)
    at d.receiveComponent (ui.js:1)
    at Object.receiveComponent (ui.js:1)
    at d._updateRenderedComponent (ui.js:1)
    at d._performComponentUpdate (ui.js:1)
    at d.updateComponent (ui.js:1)
    at d.receiveComponent (ui.js:1)
    at Object.receiveComponent (ui.js:1)
    at d._updateRenderedComponent (ui.js:1)
    at d._performComponentUpdate (ui.js:1)
    at d.updateComponent (ui.js:1)
    at d.receiveComponent (ui.js:1)
    at Object.receiveComponent (ui.js:1)
    at d._updateRenderedComponent (ui.js:1)
    at d._performComponentUpdate (ui.js:1)
    at d.updateComponent (ui.js:1)
    at d.receiveComponent (ui.js:1)
    at Object.receiveComponent (ui.js:1)
    at Object.updateChildren (ui.js:1)
    at le._reconcilerUpdateChildren (ui.js:1)
    at le._updateChildren (ui.js:1)
    at le.updateChildren (ui.js:1)
    at le._updateDOMChildren (ui.js:1)
    at le.updateComponent (ui.js:1)
    at le.receiveComponent (ui.js:1)
    at Object.receiveComponent (ui.js:1)
    at Object.updateChildren (ui.js:1)
    at le._reconcilerUpdateChildren (ui.js:1)
    at le._updateChildren (ui.js:1)
    at le.updateChildren (ui.js:1)
    at le._updateDOMChildren (ui.js:1)
    at le.updateComponent (ui.js:1)
    at le.receiveComponent (ui.js:1)
    at Object.receiveComponent (ui.js:1)
    at d._updateRenderedComponent (ui.js:1)
    at d._performComponentUpdate (ui.js:1)
    at d.updateComponent (ui.js:1)
    at d.receiveComponent (ui.js:1)
    at Object.receiveComponent (ui.js:1)
    at d._updateRenderedComponent (ui.js:1)
    at d._performComponentUpdate (ui.js:1)
    at d.updateComponent (ui.js:1)
    at d.performUpdateIfNecessary (ui.js:1)
    at Object.performUpdateIfNecessary (ui.js:1)
    at U (ui.js:1)
    at perform (ui.js:1)
    at y.perform (ui.js:1)
    at y.perform (ui.js:1)
popup.html:1 Error in event handler for (unknown): TypeError: Cannot read property '_currentElement' of null
    at d._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1929041)
    at d._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1928719)
    at d.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1927871)
    at d.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1926347)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at d._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1929157)
    at d._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1928719)
    at d.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1927871)
    at d.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1926347)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at d._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1929157)
    at d._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1928719)
    at d.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1927871)
    at d.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1926347)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at d._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1929157)
    at d._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1928719)
    at d.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1927871)
    at d.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1926347)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1915245)
    at le._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2001563)
    at le._updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2002843)
    at le.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2002741)
    at le._updateDOMChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1948941)
    at le.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1946754)
    at le.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1946307)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1915245)
    at le._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2001563)
    at le._updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2002843)
    at le.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2002741)
    at le._updateDOMChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1948941)
    at le.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1946754)
    at le.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1946307)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at d._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1929157)
    at d._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1928719)
    at d.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1927871)
    at d.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1926347)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at d._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1929157)
    at d._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1928719)
    at d.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1927871)
    at d.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1926347)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2008911)
    at d._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1929157)
    at d._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1928719)
    at d.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1927871)
    at d.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1926347)

I am on the ropsten network. The extension works on other networks but not ropsten anymore.

Steps to reproduce:
1. Go to https://ethernaut.zeppelin.solutions/level/0x68756ad5e1039e4f3b895cfaa16a3a79a5a73c59
2. Click on get new instance.
3. After the transaction is confirmed, open the console and type contract.sendTransaction({data:0xdd365b8b})

Note: This is happening after selecting the try out new metamask option. Works in old one.

**Comment by jennypollack** [comment]
I believe this should be fixed by now, thanks for reporting @funyug!
