### ISSUE TITLE
web3.eth.filter(options).get does not invoke callback - seems to timeout with large block ranges?

### ISSUE THREAD

**Issue by Schwartz10** [MetaMask/metamask-extension#5137]
Filing this issue after a conversation with @kumavis, see below for our conversation:

I’m having trouble using web3 filters when writing a nodejs script to get event data from a contract - the same code used in the script works great in our web application, the only differences (i see) are (1) the runtime environment and (2) in our web app we use the `window.web3` object (from metamask) and in nodejs script I'm instantiating web3 directly from infura endpoint.

The goal is to collect all the badges that have been minted in a smart contract by using `filter.get` and then output this info into a new file:

```
const web3 = new Web3(new Web3.providers.HttpProvider('https://mainnet.infura.io/<access-key>'));
const options = {
  fromBlock: '5985366', // block# of deployed contract
  toBlock: 'latest',
  address: '0xc45e027f0f9d7e90e612be02d4e710a632a9dba9',
};
const filter = web3.eth.filter(options);
filter.get((err, response) => {
  if (err) console.log('ERROR', err)
  else console.log('RESPONSE', response)
});
```

The interesting thing is that I'm not even seeing the 'ERROR' or 'RESPONSE' parts of the console logs, the script just ends with no logs whatsoever.

When I experimented with the `filter.watch` method (which wouldn't actually be helpful in this situation), I do get an error:

```
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/path/contracts-badges/node_modules/web3/lib/web3/errors.js:38:16)
    at XMLHttpRequest.request.onreadystatechange (/path/contracts-badges/node_modules/web3/lib/web3/httpprovider.js:125:24)
    at XMLHttpRequestEventTarget.dispatchEvent (/path/contracts-badges/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/path/contracts-badges/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/jpschwartz/Documents/ConsenSys/Ujo/contracts-badges/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/path/contracts-badges/node_modules/xhr2/lib/xhr2.js:469:24)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by kenshyx** [comment]
Can confirm this happens sometimes when filtering contract events with a 5k block interval. Also I've noticed that metamask is much slower than before .

**Comment by Schwartz10** [comment]
^^ I've also noticed this slowdown as of a couple days ago

**Comment by tmashuang** [comment]
Closing due to lack of activity. We currently limit to 10,000 results.
