### ISSUE TITLE
iframe.postMessage spam

### ISSUE THREAD

**Issue by serapath** [MetaMask/metamask-extension#5286]
Hello, I am working on my app and it contains multiple iframes which communicate with the parent window.
I receive a lot of "spam messages" like `{target: "inpage", data: "SYN"}` and `{target: "contentscript", data: "SYN"}`. They are received by the parent window and all the iframes and it took me some time to find out what causes this. It turns out the metamask extension is sending those messages on and to all the frames...

What is this about? Is there another solution?
My messages actually also had a `data` property, so i got `"SYN"` and `"ACK"` messages which caused errors in my app and made me wonder and debug.
Now I need to check messages and guess if they are from my app or from metamask, this feels like a fragile situation to be in.

**Comment by danfinlay** [comment]
The `SYN` and `ACK` messages are related to the setup handshake when MetaMask is first connecting to a Dapp:
https://github.com/kumavis/post-message-stream/blob/master/index.js#L24

The easiest way to work around this noise is ignore messages with `target: 'inpage'` or 'target: 'contentscript'`, but we also shouldn't be emitting messages in a way that you hear, so I'll leave this open so we can address it.

**Comment by W3stside** [comment]
hi guys - this error is getting bubbled up into our app Error handling and causing crashes. I looked briefly at the link @danfinlay sent thru but am still unclear. What is the reason for this change?

**Comment by W3stside** [comment]
follow up - so I traced the error to some prototype methods we've added and are importing in a top level component. The specfic error is:
```
contracts.ts?aa82:186 Contract initialisation error:  DOMException: Failed to execute 'postMessage' on 'Window': function getLast() {
  return this[this.length - 1];
} could not be cloned.
    at i._write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:113048)
    at v (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:131903)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:135015
    at i.g.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:135042)
    at e.exports.y (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:124283)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:35213
    at e.exports.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:35283)
    at w (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:119122)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/inpage.js:1:118937)
    at e.exports.b.push (chrome- ...
```

where the `getLast` function is the `prototype` method we are adding. 

Any ideas how to mitigate this? No previous issues with this method and other MM versions before 4.10

Thanks.

**Comment by serapath** [comment]
Ok, I think I figured out how to prevent the spam. You just have to write something like:
```js
// example iframe
const iframe = document.createElement('iframe')
iframe.setAttribtute('src', 'https://example.com')
document.body.appendChild(iframe)
const iwindow = iframe.contentWindow

// example event listener
window.addEventListener('message', event => {
  if (event.source === iwindow) { // filters out ALL messages from other sources than `iwindow`
    // no metamask messages will get logged here
    console.log(event.data)
  }
})
```

**Comment by tmashuang** [comment]
Closing due to inactivity and seems the solution is sufficient enough.
