### ISSUE TITLE
Error when signing messages using a Ledger-connected wallet

### ISSUE THREAD

**Issue by weijiekoh** [MetaMask/metamask-extension#5319]
**Describe the bug**

When you use personal_sign, eth_signTypedData, or eth_signTypedData_v3 with a Ledger Nano S wallet connected to MetaMask, this error shows up in the console:

```
inpage.js:1 MetaMask - RPC Error: Error: MetaMask Message Signature: TypeError: a._getWalletForAccount is not a function
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:124951)
    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:607322)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608886
    at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608956)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127814)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127537)
    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:154138)
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592069)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1591857)
    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592248)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413929)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414025 
{code: -32603, message: "Error: MetaMask Message Signature: TypeError: a._g…beogaeaoehlefnkodbefgpgknn/background.js:1:414025"}
code: -32603
message: "Error: MetaMask Message Signature: TypeError: a._getWalletForAccount is not a function↵    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:124951)↵    at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:607322)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608886↵    at t.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:608956)↵    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127814)↵    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:127537)↵    at t.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:154138)↵    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592069)↵    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1591857)↵    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1592248)↵    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413929)↵    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414025"
__proto__: Object
```

**To Reproduce**
1. Go to [https://danfinlay.github.io/js-eth-personal-sign-examples/](https://danfinlay.github.io/js-eth-personal-sign-examples/)
2. Connect your Ledger to MetaMask
2. Have the browser console open
3. Click on personal_sign and/or "sign typed data"
4. See errors

**Expected behavior**
It should behave the same way as it does with a non-Ledger MetaMask wallet.

**Browser details (please complete the following information):**
 - Kubuntu Linux
 - MetaMask Version 4.10.0
 - New UI

**Comment by tomcbean** [comment]
With v4.14.0 I'm seeing "Not supported on this device" error with eth_sign.

**Comment by brunobar79** [comment]
@weijiekoh  Thanks for reporting!  

Regarding Personal Sign not working on that example it's related to #5523 (that msg has non unicode chars). If you try personal_ecRecover you should see it works (pretty much the same except with a unicode message).

Regarding signTypedData, it's not supported in hardware wallets yet but at least now we're throwing the right error message (see #5792)

**Comment by brunobar79** [comment]
@weijiekoh It needs to be supported in the hardware wallet firmware since it requires the private keys to sign the message (and hardware wallet don’t expose it).

We’ll add support on our end as soon as Trezor and Ledger does it

**Comment by sidsverma** [comment]
@brunobar79 does ledger also have the same issue with signing with hex data as in trezor(#5218)?
