### ISSUE TITLE
MetaMask 4.16.0 got stuck on login

### ISSUE THREAD

**Issue by k06a** [MetaMask/metamask-extension#5586]
**Describe the bug**
Got stuck on login after restart. Previously got stuck on transaction signing.

**To Reproduce**
1. Use MetaMask with 20 account for a 20-30 transactions in a few hours

**Expected behavior**
Do not stuck

**Screenshots**
<img width="371" alt="image" src="https://user-images.githubusercontent.com/702124/47368218-e73c1a80-d6e9-11e8-9433-3f2dfbec37b5.png">

**Browser details (please complete the following information):**
 - OS: macOS 10.14
 - Browser: Google Chrome 69.0.3497.100
 - MetaMask Version: 4.16.0
 - New Beta UI?

**Additional context**
Reinstalling MetaMaks helps for a few hours.

**Comment by bdresser** [comment]
@k06a anything in your UI console or background console? 
Check the UI by right-clicking inside the extension then click "inspect"
Check the background by visiting `chrome://extensions`, enable developer mode in the top-right, then click `background page`

**Comment by k06a** [comment]
5.0.0 version:
```
Error in event handler for (unknown): BigNumber Error: new BigNumber() not a base 16 number: null
    at $ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:684225)
    at C (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:689708)
    at new G (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:681723)
    at hex (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3757289)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2026911
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2017314
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2026918
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1991372
    at t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1991101)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1974485
    at t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1990747)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2044824
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1991509
    at t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1990747)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998739
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998751
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998751
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998751
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998751
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998751
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998751
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1998751
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:1987983
    at conversionGTE (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3759909)
    at A (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3642353)
    at getGasFeeErrorObject (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3644918)
    at t.value (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3630056)
    at e.notifyAll (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2160731)
    at d.close (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2251553)
    at d.closeAll (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2278081)
    at d.perform (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2277576)
    at y.perform (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2277493)
    at y.perform (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2258642)
    at Object._ [as flushBatchedUpdates] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2258811)
    at closeAll (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2278081)
    at c.perform (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2277576)
    at Object.batchedUpdates (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2233598)
    at Object.e [as enqueueUpdate] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2259145)
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2255633)
    at Object.enqueueSetState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2256654)
    at o.s.setState (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2543114)
    at o.onStateChange (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2363812)
    at Object.notify (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2372907)
    at e.notifyNestedSubs (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2372535)
    at o.onStateChange (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2363830)
    at b (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2610790)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2602393
    at Object.dispatch (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2606267)
    at a.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:4072213)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:900289
ui.js:1 Uncaught Error: new BigNumber() not a base 16 number: null
    at $ (ui.js:1)
    at C (ui.js:1)
    at new G (ui.js:1)
    at hex (ui.js:1)
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at conversionGTE (ui.js:1)
    at A (ui.js:1)
    at getGasFeeErrorObject (ui.js:1)
    at t.value (ui.js:1)
    at e.notifyAll (ui.js:1)
    at d.close (ui.js:1)
    at d.closeAll (ui.js:1)
    at d.perform (ui.js:1)
    at y.perform (ui.js:1)
    at y.perform (ui.js:1)
    at _ (ui.js:1)
    at y.close (ui.js:1)
    at y.closeAll (ui.js:1)
    at y.perform (ui.js:1)
    at y.perform (ui.js:1)
    at Object._ [as flushBatchedUpdates] (ui.js:1)
    at closeAll (ui.js:1)
    at c.perform (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at dispatchEvent (ui.js:1)
    at HTMLDocument.r (ui.js:1)
18ui.js:1 Uncaught Error: new BigNumber() not a base 16 number: null
    at $ (ui.js:1)
    at C (ui.js:1)
    at new G (ui.js:1)
    at hex (ui.js:1)
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at conversionGTE (ui.js:1)
    at A (ui.js:1)
    at U.validate (ui.js:1)
    at U.convertAndSetGasPrice (ui.js:1)
    at onChange (ui.js:1)
    at d.setValue (ui.js:1)
    at onClick (ui.js:1)
    at Object.o (ui.js:1)
    at s (ui.js:1)
    at Object.executeDispatchesInOrder (ui.js:1)
    at d (ui.js:1)
    at p (ui.js:1)
    at Array.forEach (<anonymous>)
    at t.exports (ui.js:1)
    at Object.processEventQueue (ui.js:1)
    at ui.js:1
    at Object.handleTopLevel [as _handleTopLevel] (ui.js:1)
    at p (ui.js:1)
    at c.perform (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at dispatchEvent (ui.js:1)
    at HTMLDocument.r (ui.js:1)
ui.js:1 Uncaught Error: new BigNumber() not a base 16 number: null
    at $ (ui.js:1)
    at C (ui.js:1)
    at new G (ui.js:1)
    at hex (ui.js:1)
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at ui.js:1
    at t (ui.js:1)
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at ui.js:1
    at conversionGTE (ui.js:1)
    at A (ui.js:1)
    at U.validate (ui.js:1)
    at U.convertAndSetGasPrice (ui.js:1)
    at onChange (ui.js:1)
    at d.setValue (ui.js:1)
    at onClick (ui.js:1)
    at Object.o (ui.js:1)
    at s (ui.js:1)
    at Object.executeDispatchesInOrder (ui.js:1)
    at d (ui.js:1)
    at p (ui.js:1)
    at Array.forEach (<anonymous>)
    at t.exports (ui.js:1)
    at Object.processEventQueue (ui.js:1)
    at ui.js:1
    at Object.handleTopLevel [as _handleTopLevel] (ui.js:1)
    at p (ui.js:1)
    at c.perform (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at Object.batchedUpdates (ui.js:1)
    at dispatchEvent (ui.js:1)
    at HTMLDocument.r (ui.js:1)
```

**Comment by whymarrh** [comment]
ping @k06a are you still having issues with the latest version of MetaMask?

**Comment by k06a** [comment]
Nope
