### ISSUE TITLE
EthQuery - RPC Error, stack trace included - Metamask 4.16.0

### ISSUE THREAD

**Issue by roschler** [MetaMask/metamask-extension#5594]
While using Metamask 4.16.0, it entered the state where it started queuing transactions instead of popping up the pop-up dialog, a problem that is mentioned in these related issues:

https://github.com/MetaMask/metamask-extension/issues/4006
https://github.com/OriginProtocol/origin/issues/386

In this occurrence I clicked on the Ubuntu Bionic Task manager and discovered an instance of the Metamask client window _that had gotten buried in the Z-order of the all the app windows_ I had open at the time (i.e. - it was underneath another app's windows, completely invisible).  Being a typical developer I have quite a few at any time.

As a test, I clicked on the button in my dApp that triggers a Metamask session through a Web3JS call.  When I did this, I got an alert box with the stack trace shown below (note, this stack trace also appeared in the Metamask pop-up so I was able to cut and paste it here):

`EthQuery - RPC Error - Error: Fake error for generating stack trace at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:123395) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:123643 at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603139) at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1602927) at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603318) at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418589) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418730 at new Promise (<anonymous>) at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418524 at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:124061) at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:907988) at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414398) at r.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414506) at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:907980) at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413688) at r.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413829) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:907873 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402268 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389957 at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389482) at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389390) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389192 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389982 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402296 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899616 at new Promise (<anonymous>) at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899590 at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603139) at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1602927) at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603318) at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418589) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418730 at new Promise (<anonymous>) at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418524 at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899763) at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:904835) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899796 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402268 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389957 at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389482) at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389390) at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389192 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389982 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402296 at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899616 at new Promise (<anonymous>) at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822)
`

It looks like some kind of a nested client instance issue but I'm just guessing of course.  I hope this helps with your debugging efforts.

**Browser details (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu 18.04 Bionic
 - Browser [e.g. chrome, safari]: Chrome Version 70.0.3538.67 (Official Build) (64-bit)
 - MetaMask Version [e.g. 4.9.0]: 4.16.0
 - Old UI or New / Beta UI?: New UI

**Comment by bdresser** [comment]
thanks for the thorough writeup @roschler, we'll take a look.

**Comment by tmashuang** [comment]
Closing due to inactivity, if the issue has persisted in the latest version please open a new issue.
