### ISSUE TITLE
Fake error for generating stack trace

### ISSUE THREAD

**Issue by wbt** [MetaMask/metamask-extension#5642]
**Describe the bug**
I have a dapp and recently had a string of pageloads where the Javascript was interrupted causing pageload-as-expected to fail.  Examining the console, I saw several errors like this:

![Fake error for generating stack trace](https://user-images.githubusercontent.com/563406/47811055-2df9c800-dd1b-11e8-97d7-3d27161a3b72.png)

For screen reader / copy and paste purposes, that's: 
```
MetaMask - RPC Error: Error: Fake error for generating stack trace
    at a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:123395)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:123643
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603139)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1602927)
    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603318)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418589)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418730
    at new Promise (<anonymous>)
    at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418524
    at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:124061)
    at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:907988)
    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414398)
    at r.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:414506)
    at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:907980)
    at e (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413688)
    at r.default (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:413829)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:907873
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402268
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389957
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389482)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389390)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389192
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389982
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402296
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899616
    at new Promise (<anonymous>)
    at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899590
    at _ (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603139)
    at Generator._invoke (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1602927)
    at Generator.e.(anonymous function) [as next] (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1603318)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418589)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418730
    at new Promise (<anonymous>)
    at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:418524
    at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899763)
    at n (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:904835)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899796
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402268
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389957
    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389482)
    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389390)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389192
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:389982
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1402296
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:899616
    at new Promise (<anonymous>)
    at new t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:656822) Object
t @ inpage.js:1
```

Every other error looked like that.  The alternating errors were the console log message output by my code catching an error on a call to `myContract.deployed()`, where `err.message == "Error: Fake error for generating stack trace"` indicating that this fake error is bubbling up into user code. 

This happened several times in a row earlier today, but unfortunately I do not currently have a reliable way to reproduce the bug for testing.  It seems like an error that was just thrown by MetaMask to get some information for testing and development, but maybe should not have been left in production code.   It looks like it may have been introduced [here](https://github.com/MetaMask/metamask-extension/pull/5539/files#diff-968c777a5abfe9558d5a4ee1af43dff1) or more specifically [here](https://github.com/MetaMask/metamask-extension/commit/70c45ae8be4827415c218a8b527fd0a6d420a7ba) in PR #5522  about two weeks ago.

**Expected behavior**
There are no fake errors being generated by MetaMask that bubble up to the using application. 

**Browser details:**
 - OS: Windows 10
 - Browser: Chrome 70.0.3538.77 (Official Build) (64-bit) (cohort: 70_77_Win)
 - MetaMask Version: 4.16.0
 - New / Beta UI

**Comment by tmashuang** [comment]
Closing this due to a lack of activity. Source of the error is coming from https://github.com/MetaMask/metamask-extension/blob/92971d3c87fb778b5900e84bf4129f7c483ba98a/app/scripts/lib/setupFetchDebugging.js#L34 which we use during the initialization of the background. https://github.com/MetaMask/metamask-extension/blob/ee415058ccb3c78f480611343402f2a0b331381f/app/scripts/background.js#L10

Possible that this is dead code since the addition of the middleware stack.

**Comment by wbt** [comment]
I would not recommend closing this issue until that line 34 is removed from the code.  If it is dead code, it should be easily safely removable.
