### ISSUE TITLE
how to develop the MetaMask UI ?

### ISSUE THREAD

**Issue by liwei00wade** [MetaMask/metamask-extension#5905]
How to develop the MetaMask UI  ?

Now , I run  command "./node_modules/gulp/bin/gulp.js   build " to see view;
It cost me much time.

**Comment by bdresser** [comment]
you can just run `npm i` then `npm start`! See https://github.com/MetaMask/metamask-extension#development, we will have more robust documentation coming shortly

**Comment by liwei00wade** [comment]
wade@wade-work:~/goWorkSpace/src/wade/metamask-extension$ npm  start 

> metamask-crx@0.0.0 start /home/wade/goWorkSpace/src/wade/metamask-extension
> gulp dev:extension

[10:43:10] Using gulpfile ~/goWorkSpace/src/wade/metamask-extension/gulpfile.js
[10:43:10] Starting 'dev:extension'...
[10:43:10] Starting 'clean'...
[10:43:10] Finished 'clean' after 84 ms
[10:43:10] Starting 'dev:scss'...
[10:43:11] Finished 'dev:scss' after 1.17 s
[10:43:11] Starting 'dev:extension:js'...
[10:43:11] Starting 'dev:copy'...
[10:43:11] Starting 'dev:reload'...
[10:43:11] Starting 'dev:extension:js:inpage'...
[10:43:11] Starting 'dev:copy:locales'...
[10:43:11] Starting 'dev:copy:images'...
[10:43:11] Starting 'dev:copy:contractImages'...
[10:43:11] Starting 'dev:copy:fonts'...
[10:43:11] Starting 'dev:copy:vendor'...
[10:43:11] Starting 'dev:copy:reload'...
[10:43:11] Starting 'dev:copy:html'...
[10:43:11] Starting 'dev:copy:manifest'...
[10:43:11] Starting 'dev:copy:html:mascara'...
[10:43:11] Finished 'dev:copy:html:mascara' after 199 ms
[10:43:11] Finished 'dev:copy:manifest' after 273 ms
[10:43:14] Finished 'dev:copy:reload' after 2.5 s
[10:43:14] Finished 'dev:copy:vendor' after 2.54 s
[10:43:14] Finished 'dev:copy:html' after 2.64 s
[10:43:15] Finished 'dev:copy:locales' after 3.93 s
[10:43:15] Finished 'dev:copy:fonts' after 4.05 s
[10:43:16] 2008799 bytes written (4.58 seconds)
[10:43:16] Finished 'dev:copy:images' after 4.76 s
[10:43:16] Finished 'dev:extension:js:inpage' after 4.77 s
[10:43:16] Starting 'dev:extension:js:contentscript'...
[10:43:16] Starting 'dev:extension:js:background'...
[10:43:16] Starting 'dev:extension:js:ui'...
[10:43:16] Starting 'dev:extension:js:phishing-detect'...
[10:43:32] 1896785 bytes written (16.60 seconds)
[10:43:34] Finished 'dev:extension:js:contentscript' after 19 s
[10:43:38] 1887718 bytes written (22.06 seconds)
[10:43:39] Finished 'dev:extension:js:phishing-detect' after 23 s
[10:43:40] Finished 'dev:copy:contractImages' after 29 s
[10:43:40] Starting 'manifest:chrome'...
[10:43:41] Finished 'manifest:chrome' after 320 ms
[10:43:41] Starting 'manifest:opera'...
[10:43:41] Finished 'manifest:opera' after 188 ms
[10:43:41] Finished 'dev:copy' after 30 s
[10:43:44] 14185209 bytes written (28.53 seconds)
[10:43:46] Finished 'dev:extension:js:background' after 30 s
Error: Cannot find module '@babel/runtime/core-js/map' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/keys' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/number/min-safe-integer' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/keys' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/utils'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/keys' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/keys' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/number/is-nan' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/styles'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/FormControl'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Input'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Select'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/keys' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/utils'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Input'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Menu'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/ButtonBase'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/ButtonBase'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/MenuList'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Popover'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/ButtonBase'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Grow'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Modal'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/keys' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Modal'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/List'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Portal'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/RootRef'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
Error: Cannot find module '@babel/runtime/core-js/object/get-prototype-of' from '/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/@material-ui/core/Fade'
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/wade/goWorkSpace/src/wade/metamask-extension/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
^Cwade@wade-work:~/goWorkSpace/src/wade/metamask-extension$ ^C
