### ISSUE TITLE
sha3 failed to compile on windows

### ISSUE THREAD

**Issue by wighawag** [MetaMask/metamask-extension#6042]
Context:

building metamask from source

**Describe the bug**
when running ```npm install``` on windows 10 (64bit) machine I get the following error

```
...
c:\dev\projects\wighawag\metamask-extension\node_modules\sha3\src\addon.cpp(59): error C2661: 'v8::Function::NewInstance': no overloaded function takes 2 arguments [C:\dev\projects\wighawag\metamask-e xtension\node_modules\sha3\build\sha3.vcxproj]
...
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\PortableApps\nvm\v10.14.2\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\PortableApps\\nvm\\v10.14.2\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\projects\wighawag\metamask-extension\node_modules\sha3
gyp ERR! node -v v10.14.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN @babel/register@7.0.0 requires a peer of @babel/core@^7.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/core@1.0.0 requires a peer of react@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN @material-ui/core@1.0.0 requires a peer of react-dom@^16.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-merge-patch@4.1.0 requires a peer of ajv@>=6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gulp-stylelint@7.0.0 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@7.0.1 requires a peer of webpack@^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.1.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-standard@18.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wighawag\AppData\Roaming\npm-cache\_logs\2019-01-17T14_40_51_142Z-debug.log
```

**To Reproduce**
1. ```npm install```

**Additional context**
I upgraded sha3 to version 2.0.0 and it works

**Comment by whymarrh** [comment]
We've done a lot of work on our docs and tooling in recent months, please do let us know if you're still running into issues with installs (now using Yarn)

**Comment by raymanyoung** [comment]
I am hitting the same issue and apparently MSBuild 15 is not in VS2019 installation. 

Still trying to figure out the solution
