### ISSUE TITLE
Can't approve localhost with 5.3.4

### ISSUE THREAD

**Issue by ferrouswheel** [MetaMask/metamask-extension#6086]
I am locally developing a dapp, and metamask asks me to approve it. This is all as expected.

This dapp, hosted at localhost:8080, was originally approved yesterday but I was asked to approve again about an hour ago. I tried to approve it, but metamask becomes unresponsive.

I checked the extension version and it's 5.3.4. Which was released just a few hours ago. Nothing else in my environment changed as far as I can tell.

The developer console for the extension reports this error whenever I try to click "Approve"

```
background.js:1 Setting up Sentry Remote Error Reporting: SENTRY_DSN_PROD
background.js:1 Injecting MetaMask Mesh testing client
inpage.js:1 ATTENTION: In an effort to improve user privacy, MetaMask stopped exposing user accounts to dapps if "privacy mode" is enabled on November 2nd, 2018. Dapps should now call provider.enable() in order to view and use accounts. Please see https://bit.ly/2QQHXvF for complete information and up-to-date example code.
(anonymous) @ inpage.js:1
partialRollout.js:28 MetaMask Mesh Testing - threshold not matched -- skipping test
_generated_background_page.html:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:51888
background.js:1 TypeError: Cannot read property 'origin' of undefined
    at e.value (background.js:1)
    at c.apply (background.js:1)
    at c.handle (background.js:1)
    at a.handle (background.js:1)
    at a.write (background.js:1)
    at s.m (background.js:1)
    at background.js:1
    at s.a.emit (background.js:1)
    at _ (background.js:1)
    at w (background.js:1)
    at s.v.push (background.js:1)
    at t.exports._write (background.js:1)
    at v (background.js:1)
    at background.js:1
    at t.exports.g.write (background.js:1)
    at o.m (background.js:1)
    at background.js:1
    at o.a.emit (background.js:1)
    at _ (background.js:1)
    at w (background.js:1)
    at o.v.push (background.js:1)
    at o._onMessage (background.js:1)
    at EventImpl.dispatchToListener (extensions::event_bindings:403)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387)
    at EventImpl.dispatch (extensions::event_bindings:409)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at dispatchOnMessage (extensions::messaging:392)
```

Chrome Version 71.0.3578.98 (Official Build) (64-bit) on OSX.

Tried restarting Chrome, rebooting, etc.

Let me know if any further details are needed.

**Comment by danfinlay** [comment]
Dang, if anyone else experiences this, please email our support team support@metamask.io

If you include your MetaMask logs it will help us figure out what happened:
https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-New-UI-

**Comment by brunobar79** [comment]
Since the first error that appears is: `_generated_background_page.html:1 Error in event handler for runtime.onMessage: TypeError: Cannot read property 'id' of undefined
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:51888
` , which clearly blows up the background.js process, that sounds like something introduced by #6006,   potentially here: https://github.com/MetaMask/metamask-extension/pull/6006/files#diff-2cecef7b138cca58d13810de6d1191aeR33

where we're assuming tab is always defined before doing `tab.id`

CC: @bitpshr

**Comment by danfinlay** [comment]
We have confirmed this is only a problem when using the old UI, which we are deprecating on Monday. Please restart your browser, switch to the new UI, and then try again!

**Comment by ferrouswheel** [comment]
Thanks for your quick response and resolution 👍
