### ISSUE TITLE
Cannot read property 'isZero' of undefined

### ISSUE THREAD

**Issue by whymarrh** [MetaMask/metamask-extension#6897]
Sentry Issue: [METAMASK-6XT3](https://sentry.io/metamask/metamask/issues/1097465156/)

```
TypeError: Cannot read property 'isZero' of undefined
  at ? (app/scripts/controllers/detect-tokens.js:50:22)
  at Array.forEach(<anonymous>)
  at callback(app/scripts/controllers/detect-tokens.js:48:22)
  at callback(node_modules/web3/lib/web3/function.js:151:1)
  at callback(node_modules/web3/lib/web3/method.js:142:1)
  at cb(node_modules/abi-decoder/node_modules/web3/lib/web3/requestmanager.js:89:1)
  at apply(node_modules/json-rpc-engine/src/index.js:52:7)
  at apply(node_modules/async/dist/async.js:473:1)
  at next(node_modules/async/dist/async.js:5315:1)
  at apply(node_modules/async/dist/async.js:958:1)
  at callback(node_modules/async/dist/async.js:473:1)
  at replenish(node_modules/async/dist/async.js:993:1)
  at iterateeCallback(node_modules/async/dist/async.js:983:1)
  at apply(node_modules/async/dist/async.js:958:1)
  at callback(node_modules/async/dist/async.js:473:1)
  at replenish(node_modules/async/dist/async.js:993:1)
  at iterateeCallback(node_modules/async/dist/async.js:983:1)
  at nextHandlerSignalDone(node_modules/async/dist/async.js:958:1)
  at apply(node_modules/eth-json-rpc-filters/node_modules/json-rpc-engine/src/createAsyncMiddleware.js:21:11)
  at apply(node_modules/timers-browserify/main.js:62:1)
  at run(node_modules/browserify/node_modules/process/browser.js:153:1)
  at drainQueue(node_modules/browserify/node_modules/process/browser.js:123:1)

```

**Comment by whymarrh** [comment]
I've seen this a few times locally and I believe it to be one of the reasons we see balances stop updating:

<img width="1169" alt="" src="https://user-images.githubusercontent.com/1623628/61734754-21137d80-ad5d-11e9-8be5-0b43930ef5a8.png">

**Comment by whymarrh** [comment]
See also: [METAMASK-55XT](https://sentry.io/metamask/metamask/issues/920294180/)
