### ISSUE TITLE
Possible memory leak in forceResolvedRequest

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#6998]
User Funfair-JOSH claims this stack trace resulted in an app freeze. We should at least raise the event listener limit, and investigate that it causes no loops/leaks.

```
background.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 forceResolvedRequest:docs.google.com listeners added. Use emitter.setMaxListeners() to increase limit
    at f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1453393)
    at t.exports.s.addListener (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1455660)
    at t.exports.setupUntrustedCommunication (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:123134)
    at m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:6572)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:6361
```

**Comment by whymarrh** [comment]
The logic for reloading pages and the listeners for `forceResolvedRequest:${domain}` have been removed on `develop`.
