### ISSUE TITLE
chrome extension lose any response

### ISSUE THREAD

**Issue by qiluge** [MetaMask/metamask-extension#7398]
**Describe the bug**

**To Reproduce**
hello, my metamask chrome extension lose response
it is white
![image](https://user-images.githubusercontent.com/19525062/68739053-e0e54d00-0622-11ea-8775-f2d4ddb83f9a.png)

while I restart chrome, it seems normal
![image](https://user-images.githubusercontent.com/19525062/68739064-e773c480-0622-11ea-8589-f47d2172c951.png)

but while I input password and click log in button

![image](https://user-images.githubusercontent.com/19525062/68739071-ee023c00-0622-11ea-933a-f2625a9c1e09.png)

after I unlock my wallet, I can't send any token. If i click the send button, the page has not any response: click send, deposit button, click tx detail, there are not any response. And I cannot send any erc20 token.

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - MetaMask Version 7.4.0

**Comment by qiluge** [comment]
hello, I noticed that you updated the version yesterday. I think the new version has some problem. Because I remove my extension and reinstall failed. After I import my mnemonics, it display "can't restore seed", and then I click “all complete” button, the page has not any change. I have blocked at following page now, please help me solve the problem. Where can I find the old version?
![image](https://user-images.githubusercontent.com/19525062/68740697-9960c000-0626-11ea-8e94-c9407b533728.png)

**Comment by qiluge** [comment]
while I create new mnemonics, it is also cannot open wallet. The page is the same with above.

**Comment by qiluge** [comment]
click send button, chrome catch these error:
![image](https://user-images.githubusercontent.com/19525062/68742366-f6f70b80-062a-11ea-9959-0aea22048dcc.png)

**Comment by qiluge** [comment]
the main error is following:
```
ui.js:1 Setting up Sentry Remote Error Reporting: SENTRY_DSN_PROD
ui.js:1 Translator - Unable to find value of key "localhost" for locale "zh_CN"
r.getMessage @ ui.js:1
ui.js:1 Translator - Unable to find value of key "myAccounts" for locale "zh_CN"
r.getMessage @ ui.js:1
ui.js:1 Uncaught (in promise) BigNumber Error: times() not a number: null
    at Q (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:671076)
    at T (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:676561)
    at new K (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:668981)
    at K.M.times.M.mul (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:680627)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2061180
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2038689
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2034480
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2073652
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2063937
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2073660
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2037880
    at t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2037608)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2020878
    at t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2037248)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2091738
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2038023
    at t (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2037248)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2045278
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2045290
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2045290
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2045290
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2045290
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2045290
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2034480
    at conversionUtil (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3124652)
    at r.getValueFromWeiHex (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:3120547)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:1:2995862
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1327266
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1328511
    at Object.run (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1321929)
    at i.initSelector (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1322110)
    at new Connect(l) (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1320495)
    at u._constructComponentWithoutOwner (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1135783)
    at u._constructComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1135650)
    at u.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1134805)
    at Object.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193579)
    at u.performInitialMount (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1136606)
    at u.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1135491)
    at Object.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193579)
    at u.performInitialMount (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1136606)
    at u.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1135491)
    at Object.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193579)
    at Q.mountChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1188891)
    at Q._createInitialChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1150504)
    at Q.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1148726)
    at Object.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193579)
    at Q.mountChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1188891)
    at Q._createInitialChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1150504)
    at Q.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1148726)
    at Object.mountComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193579)
home.html#:1 Error in event handler: TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193732)
    at u.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1136694)
    at Object.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193732)
    at u.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1136694)
    at Object.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193732)
    at u.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1136694)
    at Object.getHostNode (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193732)
    at Q._updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189898)
    at Q.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189483)
    at Q._updateDOMChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1152925)
    at Q.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1151102)
    at Q.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1150655)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193975)
    at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1132058)
    at Q._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1188648)
    at Q._updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189585)
    at Q.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189483)
    at Q._updateDOMChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1152925)
    at Q.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1151102)
    at Q.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1150655)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193975)
    at u._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1139930)
    at u._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1139687)
    at updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1138965)
    at u.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1138092)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193975)
    at u._updateRenderedComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1139930)
    at u._performComponentUpdate (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1139687)
    at updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1138965)
    at u.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1138092)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193975)
    at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1132058)
    at Q._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1188648)
    at Q._updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189585)
    at Q.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189483)
    at Q._updateDOMChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1152925)
    at Q.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1151102)
    at Q.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1150655)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193975)
    at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1132058)
    at Q._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1188648)
    at Q._updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189585)
    at Q.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189483)
    at Q._updateDOMChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1152925)
    at Q.updateComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1151102)
    at Q.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1150655)
    at Object.receiveComponent (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1193975)
    at Object.updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1132058)
    at Q._reconcilerUpdateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1188648)
    at Q._updateChildren (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:1:1189585)
sentry.io/:1 Failed to load resource: the server responded with a status of 429 (TOO MANY REQUESTS)
ui.js:1 Uncaught TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (ui-libs.js:1)
    at u.getHostNode (ui-libs.js:1)
    at Object.getHostNode (ui-libs.js:1)
    at u.getHostNode (ui-libs.js:1)
    at Object.getHostNode (ui-libs.js:1)
    at u.getHostNode (ui-libs.js:1)
    at Object.getHostNode (ui-libs.js:1)
    at Q._updateChildren (ui-libs.js:1)
    at Q.updateChildren (ui-libs.js:1)
    at Q._updateDOMChildren (ui-libs.js:1)
    at Q.updateComponent (ui-libs.js:1)
    at Q.receiveComponent (ui-libs.js:1)
    at Object.receiveComponent (ui-libs.js:1)
    at Object.updateChildren (ui-libs.js:1)
    at Q._reconcilerUpdateChildren (ui-libs.js:1)
    at Q._updateChildren (ui-libs.js:1)
    at Q.updateChildren (ui-libs.js:1)
    at Q._updateDOMChildren (ui-libs.js:1)
    at Q.updateComponent (ui-libs.js:1)
    at Q.receiveComponent (ui-libs.js:1)
    at Object.receiveComponent (ui-libs.js:1)
    at u._updateRenderedComponent (ui-libs.js:1)
    at u._performComponentUpdate (ui-libs.js:1)
    at updateComponent (ui-libs.js:1)
    at u.receiveComponent (ui-libs.js:1)
    at Object.receiveComponent (ui-libs.js:1)
    at u._updateRenderedComponent (ui-libs.js:1)
    at u._performComponentUpdate (ui-libs.js:1)
    at updateComponent (ui-libs.js:1)
    at u.receiveComponent (ui-libs.js:1)
    at Object.receiveComponent (ui-libs.js:1)
    at Object.updateChildren (ui-libs.js:1)
    at Q._reconcilerUpdateChildren (ui-libs.js:1)
    at Q._updateChildren (ui-libs.js:1)
    at Q.updateChildren (ui-libs.js:1)
    at Q._updateDOMChildren (ui-libs.js:1)
    at Q.updateComponent (ui-libs.js:1)
    at Q.receiveComponent (ui-libs.js:1)
    at Object.receiveComponent (ui-libs.js:1)
    at Object.updateChildren (ui-libs.js:1)
    at Q._reconcilerUpdateChildren (ui-libs.js:1)
    at Q._updateChildren (ui-libs.js:1)
    at Q.updateChildren (ui-libs.js:1)
    at Q._updateDOMChildren (ui-libs.js:1)
    at Q.updateComponent (ui-libs.js:1)
    at Q.receiveComponent (ui-libs.js:1)
    at Object.receiveComponent (ui-libs.js:1)
    at Object.updateChildren (ui-libs.js:1)
    at Q._reconcilerUpdateChildren (ui-libs.js:1)
    at Q._updateChildren (ui-libs.js:1)
getHostNode @ ui-libs.js:1
getHostNode @ ui-libs.js:1
getHostNode @ ui-libs.js:1
getHostNode @ ui-libs.js:1
getHostNode @ ui-libs.js:1
getHostNode @ ui-libs.js:1
getHostNode @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_reconcilerUpdateChildren @ ui-libs.js:1
_updateChildren @ ui-libs.js:1
updateChildren @ ui-libs.js:1
_updateDOMChildren @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
receiveComponent @ ui-libs.js:1
_updateRenderedComponent @ ui-libs.js:1
_performComponentUpdate @ ui-libs.js:1
updateComponent @ ui-libs.js:1
performUpdateIfNecessary @ ui-libs.js:1
performUpdateIfNecessary @ ui-libs.js:1
_ @ ui-libs.js:1
perform @ ui-libs.js:1
perform @ ui-libs.js:1
perform @ ui-libs.js:1
x @ ui-libs.js:1
closeAll @ ui-libs.js:1
perform @ ui-libs.js:1
batchedUpdates @ ui-libs.js:1
batchedUpdates @ ui-libs.js:1
dispatchEvent @ ui-libs.js:1
n @ ui.js:1
Show 163 more frames
ui.js:1 POST https://sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7 429 (TOO MANY REQUESTS)
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
u @ ui.js:1
t.captureEvent @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
u @ ui.js:1
t.sendEvent @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
i @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
a @ ui.js:1
Promise.then (async)
u @ ui.js:1
a @ ui.js:1
Promise.then (async)
u @ ui.js:1
(anonymous) @ ui.js:1
i @ ui.js:1
e.processEvent @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
i @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
i @ ui.js:1
e.captureEvent @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
a @ ui.js:1
Promise.then (async)
u @ ui.js:1
(anonymous) @ ui.js:1
i @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
i @ ui.js:1
e.captureException @ ui.js:1
e.invokeClientAsync @ ui.js:1
e.captureException @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
(anonymous) @ ui.js:1
u @ ui.js:1
(anonymous) @ ui.js:1
e.withScope @ ui.js:1
a @ ui.js:1
r.withScope @ ui.js:1
n @ ui.js:1
```

**Comment by qiluge** [comment]
the old version 7.4.0, 7.3.1 has the same problem

**Comment by qiluge** [comment]
?

**Comment by usetech-llc** [comment]
I'm getting the same problem on Chrome/MacOS. Opera works.

**Comment by piersandro** [comment]
Same here.

**Comment by digulla** [comment]
I'm also getting this problem but when trying to send a transaction. Connecting to the network works. But when I call a method that changes stat using `truffle-contract`, I get a window which displays the fox and a busy icon. After a fraction of a second, the window goes blank with the errors in the browser console as above (https://github.com/MetaMask/metamask-extension/issues/7398#issuecomment-553278392)

This makes MetaMask useless for me.

A similar problem was mentioned in #7195 That issue links a pull request that was merged but the issue itself is still open.

**Comment by digulla** [comment]
After restarting chrome, the extension works again. I can see the transactions that I tried to send. Below the prices in ETH, I see the text "No conversion rate".

Looks like the PR for #7195 didn't fix the issue for all cases.

**Comment by qiluge** [comment]
my metamask work normally at now.

**Comment by digulla** [comment]
It's not working at all for me. When I retry a failed transaction, it hangs again:

Setting up Sentry Remote Error Reporting: SENTRY_DSN_PROD
ui.js:1 Translator - Unable to find value of key "localhost" for locale "de"
r.getMessage @ ui.js:1
ui.js:1 [ethjs-rpc] rpc error with payload {"id":8768367288656,"jsonrpc":"2.0","params":["0xf9010c108504a817c800830f424094826026d3fcefb7ac43d16853a0f19bc34339cae180b8a429523ffa0000000000000000000000003f6398b050b553412261f74deb28f8571897f40b0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000015e0000000000000000000000000000000000000000000000000000000000000019636f6d2e736368696e646c65722e646f6f72732e64656c617900000000000000822d45a091fe9be84cccb3e8596405adcd659fdffc8655d8c8b2a0ba518d7324de6f6bf0a02cc6685ccdc9b4beae19f35c6ebd046039cdb7db861efdff755d846cb3da9c83"],"method":"eth_sendRawTransaction"} [object Object]
(anonymous) @ ui.js:1
ui.js:1 Translator - Unable to find value of key "details" for locale "de"
r.getMessage @ ui.js:1
ui.js:1 Translator - Unable to find value of key "retryTransaction" for locale "de"
r.getMessage @ ui.js:1
ui.js:1 Cannot read property 'reduce' of undefined
(anonymous) @ ui.js:1
notification.html#:1 Uncaught (in promise) Object
sentry.io/api/273505/store/?sentry_key=3567c198f8a8412082d32655da2961d0&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Unknown Status Code)

I'm trying to develop code against a private network started with ganache-cli.

**Comment by digulla** [comment]
Plus useless error messages like 

MetaMask - RPC Error: "message" must be a nonempty string. Object

in my app's browser console.

**Comment by qiluge** [comment]
maybe you can broadcast the raw tx at ethscan, so that you can check is your tx's error.

**Comment by digulla** [comment]
I poked some more at it. Seems that it's the isse where RPC doesn't show the error message from the VM (https://github.com/ethereum/EIPs/issues/136). But even so, MetaMask shouldn't just stop working when there is a problem with RPC, the contract, connecting to the blockchain, or getting conversion rates.

All possible errors should be handled gracefully: Display them and move on.

**Comment by tmashuang** [comment]
Fixed in latest version.
