### ISSUE TITLE
eth_signTypedData is throwing

### ISSUE THREAD

**Issue by RichAyotte** [MetaMask/metamask-extension#7857]
**Describe the bug**
When signing data with eth_signTypedData, MetaMask throws with:
```json
{
  "code": -32603,
  "message": "e.toLowerCase is not a function",
  "data": {
    "originalError": {}
  },
  "stack": "TypeError: e.toLowerCase is not a function\n    at m (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1206762)\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background.js:1:1204581"
}
```

**To Reproduce**
Pass the following to `eth_signTypedData`.

```json
[
  "0xd5bC77131adf70B8b091F44F40C5A991709395B8",
  {
    "types": {
      "EIP712Domain": [
        {
          "name": "name",
          "type": "string"
        },
        {
          "name": "version",
          "type": "string"
        },
        {
          "name": "chainId",
          "type": "uint256"
        },
        {
          "name": "verifyingContract",
          "type": "address"
        }
      ],
      "Permit": [
        {
          "name": "holder",
          "type": "address"
        },
        {
          "name": "spender",
          "type": "address"
        },
        {
          "name": "nonce",
          "type": "uint256"
        },
        {
          "name": "expiry",
          "type": "uint256"
        },
        {
          "name": "allowed",
          "type": "bool"
        }
      ]
    },
    "primaryType": "Permit",
    "domain": {
      "name": "Dai Stablecoin",
      "version": "1",
      "chainId": 1,
      "verifyingContract": "0x6b175474e89094c44da98b954eedeac495271d0f"
    },
    "message": {
      "holder": "0xd5bC77131adf70B8b091F44F40C5A991709395B8",
      "spender": "0x95B90DbA0516FD2aa991A2F4afa7817546ffB06d",
      "nonce": 0,
      "expiry": 0,
      "allowed": true
    }
  }
]
```

**Expected behavior**
Extension to not throw.

**Screenshots**
![image](https://user-images.githubusercontent.com/294987/72626039-efe4c600-3917-11ea-9fae-057878b269f4.png)

**Browser details (please complete the following information):**
 - Debian Sid
 - Chrome Version 80.0.3987.53 (Official Build) beta (64-bit)
 - MetaMask Version 7.7.2

**Comment by RichAyotte** [comment]
I just tried sending a JSON payload to `eth_signTypedData_V4` and it works!

**Comment by wilwade** [comment]
Note that for me it needed `eth_signTypedData_v4` with the lowercase `v`.
