### ISSUE TITLE
Error: Parsing file ..../node_modules/p-limit/index.js: Unexpected token (30:10)

### ISSUE THREAD

**Issue by kevholder** [MetaMask/metamask-extension#9366]
I tried to introduce a dependency to https://github.com/sindresorhus/p-limit#readme but getting the following error when running `yarn start`:

```
scripts:core:dev:contentscript: [16:17:54] scripts:core:dev:contentscript: 4147512 bytes written (2.15 seconds)
scripts:core:dev:background: scripts:core:dev:background: Error: Parsing file ..../node_modules/p-limit/index.js: Unexpected token (30:10)
    at Deps.parseDeps (/metamask-extension/node_modules/module-deps/index.js:510:15)
    at getDeps (/metamask-extension/node_modules/module-deps/index.js:438:44)
    at /metamask-extension/node_modules/module-deps/index.js:421:38
    at ConcatStream.<anonymous> (/metamask-extension/node_modules/concat-stream/index.js:37:43)
    at ConcatStream.emit (events.js:203:15)
    at ConcatStream.EventEmitter.emit (domain.js:448:20)
    at finishMaybe (/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:607:14)
    at endWritable (/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:615:3)
    at ConcatStream.Writable.end (/metamask-extension/node_modules/readable-stream/lib/_stream_writable.js:571:41)
    at DuplexWrapper.onend (/metamask-extension/node_modules/readable-stream/lib/_stream_readable.js:570:10)
```

The error seems to be due to the fact that p-limit uses following syntax: `try {} catch {}` instead of `try {} catch (err) {}`...  How can I update build settings to support this syntax?

**Comment by tmashuang** [comment]
Depends on how it's being implemented, seems that you might be using it incorrectly. As this is not an direct issue with any current implementation I am closing.

**Comment by kevholder** [comment]
@tmashuang I'm writing a pull request, I wanted to use the `p-limit` package but I'm getting that error during the build. You don't know how to fix this build error? It looks related to using an older version of browserify.

**Comment by kevholder** [comment]
FWIW, I was able to fix the error by changing the browserify script:

```diff
--- a/development/build/scripts.js
+++ b/development/build/scripts.js
@@ -289,6 +289,14 @@ function createScriptTasks ({ browserPlatforms, livereload }) {

     let bundler = browserify(browserifyOpts)
       .transform('babelify')
+      .transform('babelify', {
+        // otherwise, parse error from "p-limit" package
+        only: [
+          './**/node_modules/p-limit',
+        ],
+        global: true,
+        plugins: ['@babel/plugin-proposal-optional-catch-binding'],
+      })
```
