### ISSUE TITLE
Account Can not be Opened when typing several incorrect password

### ISSUE THREAD

**Issue by cloud8little** [MetaMask/metamask-extension#9453]
**Describe the bug**
```
Error Details
Message: Cannot read property 'balance' of undefined

Code: TypeError

Stack:
TypeError: Cannot read property 'balance' of undefined
    at r.isBalanceCached (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:180:1163239)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:135:22626
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:135:23120
    at E (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:180:494323)
    at ca (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:59367)
    at Pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:104449)
    at bl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:90053)
    at pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:89978)
    at ol (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:87326)
    at el (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:84094)
    at Vl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:112010)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:113243
    at ul (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:87674)
    at Xl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:113228)
    at render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:115151)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:180:1214290
```

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go to account -> and security -> seed phrase ->input incorrect password
2. Close and try to send tx.

**Expected behavior**

**Screenshots**
![e686b510fe6565412fd211e6bcd281b](https://user-images.githubusercontent.com/34291844/93966457-59667f80-fd97-11ea-821e-85907e64eda6.png)

**Browser details (please complete the following information):**
 - OS: Windows10  
 - Browser [e.g. Chrome Version 85.0.4183.102 
 - MetaMask Version 8.0.10

**Comment by tmashuang** [comment]
Can you add more context to the type of accounts that you have? Do you have any imported accounts via JSON file or with a private key? Also, do you have any hardware wallets connected as well?

**Comment by cloud8little** [comment]
> Can you add more context to the type of accounts that you have? Do you have any imported accounts via JSON file or with a private key? Also, do you have any hardware wallets connected as well?

1. accounts with private key and new create wallet through metamask.
2. no hardware wallet connected.
3. I've recovered by resetting wallet and when create a new account, the old accounts recovered! It is weird but finally I got them back.

**Comment by ovidiupurice** [comment]
Hi all,
Found a workaround!

1. I've allowed the extension in incognito mode
2. Click on the extension
3. Entered the correct password and working again in normal mode.

(I personally couldn't closed my chrome browsers the my work in progress)

**Comment by tmashuang** [comment]
Closing as user has solved the issue themselves.
