### ISSUE TITLE
Cannot read property 'label' of undefined

### ISSUE THREAD

**Issue by sc0Vu** [MetaMask/metamask-extension#9464]
**Describe the bug**

When I try to connect my metamask wallet to uniswap application or any other dapp.

**To Reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1. Go dapp
2. Click on connect to metamask wallet
3. Click Next

**Expected behavior**

Should connect to metamask wallet.

**Screenshots**
None.

**Browser details (please complete the following information):**
 - OS: Darwin 10.15.1
 - Browser Chrome Version 85.0.4183.102 (Official Build) (64-bit)
 - MetaMask Version 8.0.10

**Additional context (Error Messages, etc.)**
```
Message: Cannot read property 'label' of undefined

Code: TypeError

Stack:
TypeError: Cannot read property 'label' of undefined
    at d.getAccountDescriptor (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:180:408209)
    at d.getTitle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:180:409130)
    at d.render (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:180:409229)
    at $a (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:70734)
    at Xa (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:70529)
    at Pu (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:105704)
    at bl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:90053)
    at pl (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:89978)
    at ol (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:87326)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45768
    at r.unstable_runWithPriority (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:220:3472)
    at Gi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45477)
    at Xi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45713)
    at Yi (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:45648)
    at ue (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:114525)
    at Tr (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui-libs.js:117:29321)
    at HTMLDocument.u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/ui.js:55:120400)
```

**Comment by tmashuang** [comment]
This error refers to an issue with when trying to get an address from the identities object or the selectedAddress, which is how address/accounts are organized. This seems to indicate that the selectedAddress cannot be selected because the associated identity does not exist on the object. There can be a number of possible ways that this can happen, and might involve external accounts/imported/hw wallets. If you are willing, open a [MetaMask Support Ticket](https://metamask.zendesk.com/hc/en-us/requests/new) with your state logs attached, [How to Download State Logs](https://metamask.zendesk.com/hc/en-us/articles/360015289832-How-to-Download-State-Logs-). and reference the ticket number here. We can better understand why/how this happened and potentially issue a fix.

**Comment by sc0Vu** [comment]
It turns out I got anther issue with metamask. Recently I had updated my mac to 10.15, and when I try to unlock my account, it always show: `MetamaskController - No HD Key Tree found`. I couldn't unlock account, but eventually it show the unlocked view.

Also it seems getting even worse after I click `create account`, my old account just gone. So I started to watch background console. I checked the whole storage in application, including local storage, index db, session storage. I couldn't find my encrypted wallet. It was all empty.

Then I checked the google chrome directory, the storage was empty.

Not sure what happened in my metamask (I typed wrong password for couple of times, but it should not happend this situation).

**Comment by tmashuang** [comment]
Could be related to #9453. Both are effecting login with incorrect passwords but on different views. Both are having a selected identity, or selectedAddress, missing. I'd like to ask the same question to you as over in #9453.
> Can you add more context to the type of accounts that you have? Do you have any imported accounts via JSON file or with a private key? Also, do you have any hardware wallets connected as well?

**Comment by tmashuang** [comment]
I am going to close this as a stale issue.
